### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["

### ISSUE THREAD

**Issue by l7810** [JSQLParser/JSqlParser#1001]
**Describe the bug**
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["

**To Reproduce**
1. Example SQL
`select count(0) from (SELECT id, [name], dydm, py, wb, jlzt FROM ZDDMK where jlzt=0) tmp_count`
2. Exception
`### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.4.jar:3.5.4]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149) ~[mybatis-3.5.4.jar:3.5.4]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.4.jar:3.5.4]
	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.4.jar:2.0.4]
	... 112 common frames omitted
Caused by: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:106) ~[pagehelper-5.1.11.jar:na]
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:84) ~[pagehelper-5.1.11.jar:na]
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:112) ~[pagehelper-5.1.11.jar:na]
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:98) ~[pagehelper-5.1.11.jar:na]
	at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:168) ~[pagehelper-5.1.11.jar:na]
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:104) ~[pagehelper-5.1.11.jar:na]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.4.jar:3.5.4]
	at com.sun.proxy.$Proxy384.query(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.4.jar:3.5.4]
	... 117 common frames omitted
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40) ~[jsqlparser-3.1.jar:na]
	at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:104) ~[pagehelper-5.1.11.jar:na]
	... 125 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
    at line 3, column 11.

Was expecting one of:

    "!"
    "("
    "*"
    "+"
    "-"
    ":"
    "?"
    "@"
    "@@"
    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "DESCRIBE"
    "DO"
    "DOUBLE"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "GROUP_CONCAT"
    "IF"
    "IIF"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "LEFT"
    "LIMIT"
    "MATCH"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NOT"
    "NULL"
    "NULLS"
    "OFFSET"
    "OPEN"
    "OPTIMIZE"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SESSION"
    "SET"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "ZONE"
    "{"
    "{d"
    "{t"
    "{ts"
    "~"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:4470) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:4259) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3760) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49) ~[jsqlparser-3.1.jar:na]
	... 127 common frames omitted`

**System**
 - SQLServer 2008 R2
- JDK 1.8.0-201
- JSqlParser 3.1

**Comment by l7810** [comment]
Please don't forget that there is SQLServer

**Comment by wumpz** [comment]
Since version 3 JSqlParser differs two kinds of uses of brackets. 
1. array index syntax like **a[4]**
2. square bracket quotation for object names (like in sqlserver)

these two cases are are mutually exclusive.

Therefore we decided to make 1 the default behaviour and 2 has to be switched on. You have to switch on square bracket quotation. Look into this little test. That should help you:

```java
@Test
    public void testMultiPartTableNameWithServerNameAndSchemaName() throws Exception {
        final String statement = "SELECT columnName FROM [server-name\\server-instance]..schemaName.tableName";
        assertSqlCanBeParsedAndDeparsed(statement, false,
                parser -> parser.withSquareBracketQuotation(true));
    }
```

**Comment by wumpz** [comment]
You need to call this **withSquareBracketQuotation** on your parser. 
There are already some methods in **CCJSqlParserUtil** that provides a consumer to give you access to the parser.

**Comment by wumpz** [comment]
Can we close this?

**Comment by l7810** [comment]
Thank you!
