### ISSUE TITLE
Parser hangs in some queries

### ISSUE THREAD

**Issue by serge-rider** [JSQLParser/JSqlParser#1013]
Parser hangs during parse of a query with big number of comas.

**Steps to reproduce** 
Parse query 
`SELECT * FROM ((((((((((((((((tblA))))))))))))))))`

Parser hangs (loops infinitely consuming 100% of cpu)

This issue was reported in https://github.com/dbeaver/dbeaver/issues/9054

Stack from the thread dump:
```
java.lang.Thread.State: RUNNABLE
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_add_error_token(CCJSqlParser.java:24965)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:24895)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_385(CCJSqlParser.java:18292)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_515(CCJSqlParser.java:18130)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_421(CCJSqlParser.java:18138)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_354(CCJSqlParser.java:24089)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_193(CCJSqlParser.java:24132)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_502(CCJSqlParser.java:22742)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22907)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_562(CCJSqlParser.java:22767)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22856)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_561(CCJSqlParser.java:22816)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_498(CCJSqlParser.java:22852)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_388(CCJSqlParser.java:22896)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_275(CCJSqlParser.java:22938)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_129(CCJSqlParser.java:22428)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_47(CCJSqlParser.java:22730)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_rescan_token(CCJSqlParser.java:25106)
	  at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25025)
	  at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4281)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4255)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:12580)
	  at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5840)
	  at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4055)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4264)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	  at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3916)
	  at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	  at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
```

**System**

- Any database
- Java 11
- JSQLParser 3.2

**Comment by AnEmortalKid** [comment]
@serge-rider can you capture the same parsing with the DEBUG_PARSER flag enabled?

**Comment by serge-rider** [comment]
@AnEmortalKid I could try. 
How can I do this? Do I need to rebuild JSQLParser from sources?

**Comment by AnEmortalKid** [comment]
@serge-rider yeah you'd have to clone the repo and rebuild with these: https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-parsing#visualize-parsing

**Comment by serge-rider** [comment]
The interesting part is that it hangs in generateParseException, not in the parse itself.

Here is the debug info:
```
Call:	Statement
  Call:	SingleStatement
    Call:	Select
      Call:	SelectBody
        Call:	SetOperationList
          Call:	PlainSelect
            Consumed token: <<K_SELECT>: "SELECT" at line 1 column 1>
            Call:	getOracleHint
            Return: getOracleHint
            Call:	SelectItemsList
              Call:	SelectItem
                Consumed token: <"*" at line 1 column 8>
              Return: SelectItem
            Return: SelectItemsList
            Consumed token: <"FROM" at line 1 column 10>
            Call:	FromItem
              Consumed token: <"(" at line 1 column 15>
              Call:	SubSelect
                Call:	SelectBody
                  Call:	SetOperationList
                    Consumed token: <"(" at line 1 column 16>
                    Call:	SelectBody
                      Call:	SetOperationList
                        Consumed token: <"(" at line 1 column 17>
                        Call:	SelectBody
                          Call:	SetOperationList
                            Consumed token: <"(" at line 1 column 18>
                            Call:	SelectBody
                              Call:	SetOperationList
                                Consumed token: <"(" at line 1 column 19>
                                Call:	SelectBody
                                  Call:	SetOperationList
                                    Consumed token: <"(" at line 1 column 20>
                                    Call:	SelectBody
                                      Call:	SetOperationList
                                        Consumed token: <"(" at line 1 column 21>
                                        Call:	SelectBody
                                          Call:	SetOperationList
                                            Consumed token: <"(" at line 1 column 22>
                                            Call:	SelectBody
                                              Call:	SetOperationList
                                                Consumed token: <"(" at line 1 column 23>
                                                Call:	SelectBody
                                                  Call:	SetOperationList
                                                    Consumed token: <"(" at line 1 column 24>
                                                    Call:	SelectBody
                                                      Call:	SetOperationList
                                                        Consumed token: <"(" at line 1 column 25>
                                                        Call:	SelectBody
                                                          Call:	SetOperationList
                                                            Consumed token: <"(" at line 1 column 26>
                                                            Call:	SelectBody
                                                              Call:	SetOperationList
                                                                Consumed token: <"(" at line 1 column 27>
                                                                Call:	SelectBody
                                                                  Call:	SetOperationList
                                                                    Consumed token: <"(" at line 1 column 28>
                                                                    Call:	SelectBody
                                                                      Call:	SetOperationList
                                                                        Consumed token: <"(" at line 1 column 29>
                                                                        Call:	SelectBody
                                                                          Call:	SetOperationList
                                                                            Consumed token: <"(" at line 1 column 30>
                                                                            Call:	SelectBody
                                                                              Call:	SetOperationList
```

**Comment by wumpz** [comment]
OK. That rings a bell. Sometimes ago I had to deal with parenthesis expression in the selected items list:

    SELECT ((((((((((((((((tblA)))))))))))))))) FROM mytable

This one now parses fast. I have to dig into this. Maybe a similar change would be sufficient here. If I remember right, there was quite a grammar refactoring needed. 

@AnEmortalKid I want to avoid duplicate effort. Did you do something on this?

**Comment by AnEmortalKid** [comment]
Negative @wumpz. I was just trying to gather more data! Go for it.

**Comment by serge-rider** [comment]
Any updates?
There are many cases when it hangs because of big number of parenthesis.

Is there any workaround for this issue?
Thank you.

**Comment by Wisser** [comment]
@serge-rider as a workaround I have overridden the method CCJSqlParser#generateParseException(), so that in case of an error a simplified error message is generated. See https://github.com/Wisser/Jailer/commit/065c6df670272958ace715578800e684248e6780
(In the error message the "Was expecting: ..." part is therefore missing).

It is probably the method _CCJSqlParser#jj_rescan_token()_, which in some cases takes an exorbitant amount of computing time. Since this method is only called if an error occurs, the workaround should work in all cases.

I am of course still interested in a fix.

**Comment by wumpz** [comment]
Sorry. It's a bit late.

I included a test for

    SELECT * FROM (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((tblA)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

This one now parses in <0.2 secs.

**Comment by serge-rider** [comment]
Thank you!
