### ISSUE TITLE
JSON type in MySQL not supported in v3.2

### ISSUE THREAD

**Issue by FoxInNorth** [JSQLParser/JSqlParser#1020]
Hi Sir,
     For JSON column type in MySQL, it is supported in JSqlparser v3.0.
     But when I upgrade to v3.2, I found there was error when parsed. 
     For example:
       `create table test.json_test (c1 int primary key, c2 varchar(20) not null, c3 json default null );`
     Above table creation SQL is not parsed successfully in JSqlparser v3.2.
     Error message:
     
      Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "json" "JSON"
    at line 27, column 9.

Was expecting one of:

    "BINARY"
    "BIT"
    "CHAR"
    "CHARACTER"
    "DOUBLE"
    "INTERVAL"
    "SET"
    "SIGNED"
    "UNSIGNED"
    "XML"
    <DT_ZONE>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColDataType(CCJSqlParser.java:13882)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnDefinition(CCJSqlParser.java:12885)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:13636)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:177)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	... 29 more

**Comment by wumpz** [comment]
This should be a simple extension. Pull requests are welcome.

**Comment by manticore-projects** [comment]
[Tested with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4BcCmBnNA6AVlgPYB2A+pjrABQBQsDsAxgIyPsCSAclO3+wAUQHALIQQATVgBpMBPqMANMwBMfAGrjgACXE0VABgCU7LgHleXAKrJkChsqYBmPgCkAyma79+AETAAYhA2ljZ2RrQA3EA+) and it works flawlessly.
