### ISSUE TITLE
CREATE TABLE - default-values on columns

### ISSUE THREAD

**Issue by gitmotte** [JSQLParser/JSqlParser#1022]
```
   CREATE TABLE myschema.tableName (
                id bigint NOT NULL DEFAULT nextval('myschema.mysequence'::regclass), 
                bool_col boolean NOT NULL DEFAULT false, 
                int_col integer NOT NULL DEFAULT 0)
```
Default-Values not supported currently 
* boolean (true|false) 
* nextval (postgresql syntax)

```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "nextval" "NEXTVAL"
    at line 1, column 61.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "::"
    "="
    "ASC"
    "BY"
    "CASCADE"
    "CHECK"
    "COLLATE"
    "COMMENT"
    "COMMIT"
    "CONSTRAINT"
    "DEFAULT"
    "DELETE"
    "DESC"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:59)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:88)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:74)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:59)
	at net.sf.jsqlparser.statement.create.CreateTableTest.testCreateTableWithDefault(CreateTableTest.java:677)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "nextval" "NEXTVAL"
    at line 1, column 61.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "::"
    "="
    "ASC"
    "BY"
    "CASCADE"
    "CHECK"
    "COLLATE"
    "COMMENT"
    "COMMIT"
    "CONSTRAINT"
    "DEFAULT"
    "DELETE"
    "DESC"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25083)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24927)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:13665)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:175)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:79)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:163)
	... 28 more

```

**Comment by mo3000** [comment]
I was looking into this but things got more complecated than I thought.
- there's no boolean keyword so I created one.
- default defination in column is usually diffrent from table's "default". So I rename the original ```CreateParameter``` to ```CreateTableParameter``` for table only. Then created a  new  ```CreateParameter``` with a different "default" part like:
```
List<String> CreateParameter():
{
    String retval = "";
    Token tk = null;
    Token tk2 = null;
...
            tk=<K_PRIMARY> { param.add(tk.image); }
            |
            <K_DEFAULT> {param.add("DEFAULT");}
                (
                    (tk=<K_NULL> | tk=<S_DOUBLE> | tk=<S_LONG> | tk=<K_FALSE> | tk=<K_TRUE> | tk=<S_CHAR_LITERAL> | tk=<K_TIME_KEY_EXPR>) {param.add(tk.image);}
                    |
                    ("+" {retval = "+";} | "-" {retval = "-";}) ?
                    (
                       tk=<S_LONG> { retval += tk.image; }
                       |
                       tk=<S_DOUBLE> { retval += tk.image; }
                    )
                    {param.add(retval);}
                    // place a new nextval() here
                )
            |
            tk=<K_FOREIGN> { param.add(tk.image); }
...
```

If someone write a new NextValExpression(), place it to the comment above.
sql 
```sql
CREATE TABLE T1 (isok boolean DEFAULT true);
CREATE TABLE T1 (isok boolean DEFAULT false);
```
will work due to this change (copy from a working branch), but then I realized default value can be expressions. as in the mysql manual:
```sql
CREATE TABLE t1 (
  -- literal defaults
  i INT         DEFAULT 0,
  c VARCHAR(10) DEFAULT '',
  -- expression defaults
  f FLOAT       DEFAULT (RAND() * RAND()),
  b BINARY(16)  DEFAULT (UUID_TO_BIN(UUID())),
  d DATE        DEFAULT (CURRENT_DATE + INTERVAL 1 YEAR),
  p POINT       DEFAULT (Point(0,0)),
  j JSON        DEFAULT (JSON_ARRAY())
);
```
That's too hard for me, so I write down things I got and leave it to you guys -_-!.

**Comment by gitmotte** [comment]
Thank you for your thoughts, I didn't have the time to handle it myself because it is so complex. But I have placed a marker branch with a simple test case ... there are several syntax variants of nextval out there and other expressions may be allowed as well, as you have already noticed.
