### ISSUE TITLE
Dynamic queries having tokens in square brackets

### ISSUE THREAD

**Issue by amitkumarwali** [JSQLParser/JSqlParser#1031]
**Describe the bug**
SQL statements which have tokens as part of the query end up in error. 

**To Reproduce**
1. Example SQL
`select 
	spr.column_1,
	spr.column_2,
	spr.column_3,
	spr.column_4,
	spr.column_5,
	spr.column_6
from 
	spr_table spr
where 
	spr.column_1 > 0 and [WHERECLAUSE]`

2. Exception

 
```
 net.sf.jsqlparser.JSQLParserException
 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
 	at com.scanner.JsqlParserExample.main(JsqlParserExample.java:12)
 Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
     at line 21, column 1.
 
 Was expecting one of:
 
     "!"
     "("
     "NOT"
 
 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
 	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:7606)
 	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:7475)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:7446)
 	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:6425)
 	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3794)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:479)
 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:135)
 	... 1 more
 Caused by:
 net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
     at line 21, column 1.
 
Was expecting one of:
 
     "!"
     "("
     "NOT"
 
 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
 	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:7606)
 	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:7475)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:7446)
 	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:6425)
 	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3794)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642)
 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
 	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:479)
 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:135)
 	
```

**Expected behavior**
The parser should attempt to fetch/extract/parse as much details as possible. In the above example, DML operation and the table name could have been extracted.

**System**
 - Database = ORACLE
- Java Version = 1.8
- JSqlParser version = tested with 3.1 & 3.2

**Comment by amitkumarwali** [comment]
Some more examples -


`update metadata set [setclause] where metadata_id = ? [wherecondition]`


`update document_info set identifier = ?, version = ?, dt_id = ? dt_tm = ? [setClause] [setClauseForSetInfo] [setClauseForValidationVal] where  document_info_id = ?`


`INSERT INTO metadata ([$COLUMNS]) VALUES ([$VALUES])`


`delete from long_text_table where text_id in (select [0] from [1] where event_text_id in (?) and [2] > 0.0)`

**Comment by amitkumarwali** [comment]
Yes, they are not part of the SQL because they can have a dynamic value, which will be decided during the runtime.

I'll probably explain my use case and that should clarify why I have this issue reported -

So what I'm trying to achieve is, I'm interested in finding out the list of tables an application is accessing. The application(s) which i'm talking about are the ones which store queries in a .sql file. From application stand point, it loads the required query, replace the token, execute the query. From my use case point, I want to parse these .sql files and find out the tables that they are querying too.

Since JSQLParser is designed for such a thing and basically gives what i'm looking for, I was able to parser many queries which were simple, moderate and complex types. However, queries which had tokens (like the ones above), i see that JSQL parser fails it. Probably, it would be wrong to say that such queries are incorrect/invalid, as they depend on some value to be substituted on-the-go, but are in a state which requires replacing of the token to form a query that can be executed. If JSQLParser could support such queries, then it would be a perfect tool to parse any kind of queries, be it dynamic or static ones.

Hope that explains why I have this issue logged.

**Comment by wumpz** [comment]
Those queries with this query tokens are indeed incorrect from JSqlParsers perspective, because to this parser it is all SQL. Therefore it interprets those bracket parts like I described above. 
First you should replace those parts with a valid SQL and then send it through JSqlParser.

**Comment by wumpz** [comment]
So can we close this?
