### ISSUE TITLE
jsqlparser can not parser the sql which is drop sequence xxxx

### ISSUE THREAD

**Issue by liweiboy** [JSQLParser/JSqlParser#1036]
**Describe the bug**
jsqlparser can not parser the sql which is drop sequence xxx; 

**To Reproduce**
1. Example SQL
`DROP SEQUENCE SEQ_SYS_LOG_162`
2. Exception
`Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:151)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
	... 78 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SEQUENCE" "SEQUENCE"
    at line 1, column 6.

Was expecting one of:

    "INDEX"
    "SCHEMA"
    "TABLE"
    "VIEW"
    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.Drop(CCJSqlParser.java:14635)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:187)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:498)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:149)
	... 79 more`
**Expected behavior**

**System**

1. Database = ORACLE11g
2. Java Version = 1.8
3. JSqlParser version = tested with 3.2

**Comment by wumpz** [comment]
You are right. Create / Alter was implemented. Do you want to provide this? PRs are welcome.

**Comment by AnEmortalKid** [comment]
Fixed by #1037 , this can be closed
