### ISSUE TITLE
Unable to parse table name with grave accent(`)

### ISSUE THREAD

**Issue by liyanliang1994** [JSQLParser/JSqlParser#1047]
**Describe the bug**
Unable to parse table name with grave accent(`)

**To Reproduce**
1. ``select * from `t```;``
2. Parsing this SQL using JSqlParser with this statements
3. Exception
```
Caused by: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 19.  Encountered: "`" (96), after : "`"
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:4724)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:24885)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_26(CCJSqlParser.java:18586)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_213(CCJSqlParser.java:18624)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_415(CCJSqlParser.java:21894)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_346(CCJSqlParser.java:21929)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_180(CCJSqlParser.java:21974)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_132(CCJSqlParser.java:21527)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_50(CCJSqlParser.java:22712)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_50(CCJSqlParser.java:16574)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5952)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4055)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4264)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3916)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:498)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:149)
	... 1 more
```

**Expected behavior**
Should parse the statement successfully

**System**
 - Database you are using: MySQL
- Java Version: 1.8
- JSqlParser version: 3.2

**Comment by wumpz** [comment]
Do I understand you right, that your table name is actually **t`** and the other backticks are used to quote the whole name?

One way to achieve this is to change the enclosing to double quotes:

    select * from "t`"

**Comment by liyanliang1994** [comment]
Yes, the table name is actually t\`. PostgreSQL uses `"` to quote the table name. But MySQL seems only support `.

**Comment by wumpz** [comment]
Why this name? Imho it's a bad idea. However, jsqlparser is not able to parse this.

**Comment by manticore-projects** [comment]
Closed as "won't change".
