### ISSUE TITLE
fails parsing referential action

### ISSUE THREAD

**Issue by jahlbornG** [JSQLParser/JSqlParser#1081]
**Describe the bug**
Although the code seems like it supports referential actions on constraints, it is failing for me.

**To Reproduce**

ALTER TABLE my_table ADD CONSTRAINT my_table_fk FOREIGN KEY (some_column) REFERENCES other_table (other_column) ON UPDATE NO ACTION ON DELETE NO ACTION;

**Expected behavior**
Should parse the expression successfully, instead generates:

~~~~~
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:151)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "UPDATE" "UPDATE"
    at line 6, column 127.

Was expecting:

    "DELETE"

  at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
  at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
  at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:15215)
  at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:15669)
  at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:159)
  at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:578)
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:149)
  ... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "UPDATE" "UPDATE"
    at line 6, column 127.

Was expecting:

    "DELETE"

  at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
  at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
  at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:15215)
  at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:15669)
  at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:159)
  at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:578)
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:149)
~~~~~

**System**
- version 3.2 of jsqlparser.

**Comment by jahlbornG** [comment]
realized this is fixed in the latest snapshot
