### ISSUE TITLE
MySQL Unique Keys

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#109]
```SQL
CREATE TABLE animals (
id INT NOT NULL,
name VARCHAR(100)
UNIQUE KEY (id));
```
unique is not supported

**Comment by wumpz** [comment]
The statement is parsed using JSqlParser 0.9.3 - Snapshot or did you mean something different? Is there an exception?

**Comment by frankred** [comment]
I'm Using 0.9.3 Snapshot but it seems like UNIQUE is not working.

The quotation mark ``` ` ``` is not working too

```sql
CREATE TABLE `wp_commentmeta` (\n  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `meta_key` varchar(255) DEFAULT NULL,\n  `meta_value` longtext,\n  PRIMARY KEY (`meta_id`),\n  KEY `comment_id` (`comment_id`),\n  KEY `meta_key` (`meta_key`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8;CREATE TABLE `wp_comments` (\n  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `comment_author` tinytext NOT NULL,\n  `comment_author_email` varchar(100) NOT NULL DEFAULT '',\n  `comment_author_url` varchar(200) NOT NULL DEFAULT '',\n  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',\n  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `comment_content` text NOT NULL,\n  `comment_karma` int(11) NOT NULL DEFAULT '0',\n  `comment_approved` varchar(20) NOT NULL DEFAULT '1',\n  `comment_agent` varchar(255) NOT NULL DEFAULT '',\n  `comment_type` varchar(20) NOT NULL DEFAULT '',\n  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  PRIMARY KEY (`comment_ID`),\n  KEY `comment_post_ID` (`comment_post_ID`),\n  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),\n  KEY `comment_date_gmt` (`comment_date_gmt`),\n  KEY `comment_parent` (`comment_parent`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;CREATE TABLE `wp_links` (\n  `link_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `link_url` varchar(255) NOT NULL DEFAULT '',\n  `link_name` varchar(255) NOT NULL DEFAULT '',\n  `link_image` varchar(255) NOT NULL DEFAULT '',\n  `link_target` varchar(25) NOT NULL DEFAULT '',\n  `link_description` varchar(255) NOT NULL DEFAULT '',\n  `link_visible` varchar(20) NOT NULL DEFAULT 'Y',\n  `link_owner` bigint(20) unsigned NOT NULL DEFAULT '1',\n  `link_rating` int(11) NOT NULL DEFAULT '0',\n  `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `link_rel` varchar(255) NOT NULL DEFAULT '',\n  `link_notes` mediumtext NOT NULL,\n  `link_rss` varchar(255) NOT NULL DEFAULT '',\n  PRIMARY KEY (`link_id`),\n  KEY `link_visible` (`link_visible`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8;CREATE TABLE `wp_options` (\n  `option_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `option_name` varchar(64) NOT NULL DEFAULT '',\n  `option_value` longtext NOT NULL,\n  `autoload` varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (`option_id`),\n  UNIQUE KEY `option_name` (`option_name`)\n) ENGINE=InnoDB AUTO_INCREMENT=402 DEFAULT CHARSET=utf8;CREATE TABLE `wp_postmeta` (\n  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `meta_key` varchar(255) DEFAULT NULL,\n  `meta_value` longtext,\n  PRIMARY KEY (`meta_id`),\n  KEY `post_id` (`post_id`),\n  KEY `meta_key` (`meta_key`)\n) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;CREATE TABLE `wp_posts` (\n  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `post_content` longtext NOT NULL,\n  `post_title` text NOT NULL,\n  `post_excerpt` text NOT NULL,\n  `post_status` varchar(20) NOT NULL DEFAULT 'publish',\n  `comment_status` varchar(20) NOT NULL DEFAULT 'open',\n  `ping_status` varchar(20) NOT NULL DEFAULT 'open',\n  `post_password` varchar(20) NOT NULL DEFAULT '',\n  `post_name` varchar(200) NOT NULL DEFAULT '',\n  `to_ping` text NOT NULL,\n  `pinged` text NOT NULL,\n  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `post_content_filtered` longtext NOT NULL,\n  `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `guid` varchar(255) NOT NULL DEFAULT '',\n  `menu_order` int(11) NOT NULL DEFAULT '0',\n  `post_type` varchar(20) NOT NULL DEFAULT 'post',\n  `post_mime_type` varchar(100) NOT NULL DEFAULT '',\n  `comment_count` bigint(20) NOT NULL DEFAULT '0',\n  PRIMARY KEY (`ID`),\n  KEY `post_name` (`post_name`),\n  KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),\n  KEY `post_parent` (`post_parent`),\n  KEY `post_author` (`post_author`)\n) ENGINE=InnoDB AUTO_INCREMENT=55004 DEFAULT CHARSET=utf8;CREATE TABLE `wp_term_relationships` (\n  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `term_order` int(11) NOT NULL DEFAULT '0',\n  PRIMARY KEY (`object_id`,`term_taxonomy_id`),\n  KEY `term_taxonomy_id` (`term_taxonomy_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8;CREATE TABLE `wp_term_taxonomy` (\n  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `taxonomy` varchar(32) NOT NULL DEFAULT '',\n  `description` longtext NOT NULL,\n  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `count` bigint(20) NOT NULL DEFAULT '0',\n  PRIMARY KEY (`term_taxonomy_id`),\n  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),\n  KEY `taxonomy` (`taxonomy`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;CREATE TABLE `wp_terms` (\n  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `name` varchar(200) NOT NULL DEFAULT '',\n  `slug` varchar(200) NOT NULL DEFAULT '',\n  `term_group` bigint(10) NOT NULL DEFAULT '0',\n  PRIMARY KEY (`term_id`),\n  UNIQUE KEY `slug` (`slug`),\n  KEY `name` (`name`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;CREATE TABLE `wp_usermeta` (\n  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',\n  `meta_key` varchar(255) DEFAULT NULL,\n  `meta_value` longtext,\n  PRIMARY KEY (`umeta_id`),\n  KEY `user_id` (`user_id`),\n  KEY `meta_key` (`meta_key`)\n) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;CREATE TABLE `wp_users` (\n  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `user_login` varchar(60) NOT NULL DEFAULT '',\n  `user_pass` varchar(64) NOT NULL DEFAULT '',\n  `user_nicename` varchar(50) NOT NULL DEFAULT '',\n  `user_email` varchar(100) NOT NULL DEFAULT '',\n  `user_url` varchar(100) NOT NULL DEFAULT '',\n  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  `user_activation_key` varchar(60) NOT NULL DEFAULT '',\n  `user_status` int(11) NOT NULL DEFAULT '0',\n  `display_name` varchar(250) NOT NULL DEFAULT '',\n  PRIMARY KEY (`ID`),\n  KEY `user_login_key` (`user_login`),\n  KEY `user_nicename` (`user_nicename`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
```

After I remove all  ``` ` ``` I got the following exception:

```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:111)
	at sanbox.BUDataColumnsFinder.main(BUDataColumnsFinder.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "UNIQUE" "UNIQUE "" at line 52, column 3.
```


Here is my pom

```
        <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>0.9.3-SNAPSHOT</version>
        </dependency>
```

**Comment by wumpz** [comment]
The  quotation you mentioned should work. There are testcases. Give me some time for your sql.

**Comment by frankred** [comment]
Wow thank you so much! <3 JSQLParser
