### ISSUE TITLE
Exception While parsing Create query in version 4.0

### ISSUE THREAD

**Issue by syed72** [JSQLParser/JSqlParser#1125]
Below is the exception caused when trying to parse CREATE TABLE query...
Can someone help?
Note: Same Query is working in Version 3.2

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CREATE" "CREATE"
    at line 1, column 1.

Was expecting one of:

    "CASCADE"
    "NO"
    "RESTRICT"
    "SET"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377)
	at net.sf.jsqlparser.parser.CCJSqlParser.Action(CCJSqlParser.java:14960)

Thanks

**Comment by syed72** [comment]
Using java - 8
Even i used CCJSqlParserUtil.newParse(InputStream is), then also parsing gets failed.

**Comment by wumpz** [comment]
At least since 2017 something like this is supported:

    CREATE TABLE testtab ("test" varchar (255), "test2" varchar (255));

I assume there is a different problem.

**Comment by wumpz** [comment]
What is your concrete query?
