### ISSUE TITLE
Parser hangs on query with multiple "case when" statements

### ISSUE THREAD

**Issue by ShadelessFox** [JSQLParser/JSqlParser#1127]
**Describe the bug**
Our users experience problems running queries which contain multiple "case when" statements: dbeaver/dbeaver#10704

**To Reproduce**
Use the following query:
```
create or replace view v_name as
select f1,   f2, 
case when f3 <5   then 5    else 
case when f3 <=10 then 10 else
case when f3 <=15 then 15 else
case when f3 <=20 then 20 else
case when f3 <=25 then 25 else
case when f3 <=30 then 30 else
case when f3<=35 then 35 else
case when f3<=40 then 40 else
case when f3<=50 then 50 else
case when f3<=60 then 60 else
case when f3<=70 then 70 else
case when f3<=80 then 80 else
case when f3<=90 then 90 else
case when f3<=100 then 100 else
case when f3<=120 then 120 else
case when f3<=150 then 150 else
case when f3>150  then 999 end 
end end end end end end end end end end end end end end end end as ff, 
max(year(current_timestamp)) yy,
group by 1,2;
```
The parser keep cycling around here:
```
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameWithoutValue_1322_5_415(CCJSqlParser.java:19376)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectName_1350_6_295(CCJSqlParser.java:19173)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectName_1350_5_133(CCJSqlParser.java:19181)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameExt_1380_7_308(CCJSqlParser.java:18983)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameExt_1380_5_147(CCJSqlParser.java:19013)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameList_1294_5_226(CCJSqlParser.java:19715)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_InternalFunction_3754_5_437(CCJSqlParser.java:22938)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Function_3731_11_354(CCJSqlParser.java:22969)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Function_3729_5_171(CCJSqlParser.java:22999)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_PrimaryExpression_3244_11_270(CCJSqlParser.java:25193)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_PrimaryExpression_3217_5_117(CCJSqlParser.java:25432)
```

**System**
- Database you are using: Vertica 10
- Java Version: 11.0.8
- JSqlParser version: 4.0.0

**Comment by manticore-projects** [comment]
Solved in 4.1.
