### ISSUE TITLE
Alter - Drop FK and PK not working

### ISSUE THREAD

**Issue by syed72** [JSQLParser/JSqlParser#1129]
**Alter - Drop FK and PK not working**

Sample Query -  ALTER TABLE child_table1 DROP FOREIGN KEY abc_column

got below exception while trying to parse above query to drop FK or PK...

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FOREIGN" "FOREIGN"
    at line 1, column 24.

Was expecting one of:

    "COLUMN"
    "CONSTRAINT"
    "INDEX"
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:16472)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:16563)

**System**
 - Database you are using -  Mysql 5.7
- Java Version - 1.8
- JSqlParser version - 4.0
- 
Please address this issue asap

**Comment by syed72** [comment]
Any Idea when 4.1 will be released?
