### ISSUE TITLE
Parser error using PostgreSQL ALL operator

### ISSUE THREAD

**Issue by ricardocorrent** [JSQLParser/JSqlParser#1140]
**Describe the bug**
Attempting to parse SQL Select containing PostgreSQL all operator with (subquery)

**To Reproduce**
1. Example SQL
`SELECT * FROM table t0 WHERE t0.id != all(?::uuid[]);`
2. Parsing this SQL using JSqlParser with this statements
`Statement statement = CCJSqlParserUtil.parse(sql);`
3. Exception
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "!=" <OP_NOTEQUALSBANG>
    at line 1, column 465.

Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "OR"
    "ORDER"
    "START"
    "UNION"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538) ~[jsqlparser-4.0.jar:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377) ~[jsqlparser-4.0.jar:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91) ~[jsqlparser-4.0.jar:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:163) ~[jsqlparser-4.0.jar:?]
```

**Expected behavior**
Parsing of sql

**System**
 - Database you are using: **Postgres 12.5** 
- Java Version **1.8**
- JSqlParser version **4**

**Comment by wumpz** [comment]
JSqlParser should accept this `all` as a function name. I think this is a keyword collision. I will look into it.

**Comment by wumpz** [comment]
Sorry. It took a while.
