### ISSUE TITLE
ALTER TABLE ADD FOREIGN KEY fails on Table Schema

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1156]
Valid at least in H2 and Oracle:
```sql
-- ALTER TABLE ADD FOREIGN KEY
ALTER TABLE cfe.ledger_acc_entry_manual
ADD FOREIGN KEY (id_manual_posting_batch) REFERENCES cfe.manual_posting_batch(id_manual_posting_batch);
```

```java
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "." "."
    at line 2, column 57.

Was expecting one of:

    "("
    ","
    ";"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:188)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:176)
```

I will try to fix it in the JavaCC Parser and send a PR.

**Comment by manticore-projects** [comment]
Fixed in PR #1153.
