### ISSUE TITLE
Unrecognized keyword `BINARY` in MySQL

### ISSUE THREAD

**Issue by ImSejin** [JSQLParser/JSqlParser#1198]
**Describe the bug**
I use query interceptor of MyBatis. When a query contains `BINARY` keyword, parser fails.

**To Reproduce**
1. Example SQL
```sql
CREATE TABLE IF NOT EXISTS AUTHOR
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(30) NOT NULL COMMENT 'Human name',
    COUNTRY   VARCHAR(50) NOT NULL,
    BIRTHDATE DATE
);

INSERT INTO AUTHOR (NAME, COUNTRY, BIRTHDATE)
VALUES ('Aliko Dangote', 'Colombia', '1963-10-31'),
       ('Bill Gates', 'United States America', '1955-12-03'),
       ('Reifival Canni', 'Barbados', '1877-01-11'),
       ('Yihnoh Shuneim', 'Belarus', '2016-08-08'),
       ('Koreze Grizzlysnow', 'Belgium', '1632-01-21')
```

2. Parsing this SQL using JSqlParser with this statements
```sql
SELECT * FROM AUTHOR WHERE 1 AND NAME LIKE CONCAT('%', TRIM(BINARY(?)), '%') -- failed
```
```sql
SELECT * FROM AUTHOR WHERE 1 AND NAME LIKE CONCAT('%', TRIM(BINARY ?), '%') -- failed
```
```sql
SELECT * FROM AUTHOR WHERE 1 AND NAME LIKE CONCAT('%', TRIM(?), '%') -- succeeded
```

3. Exception
```java
### Error querying database.  Cause: java.lang.RuntimeException: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 52.

Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "CONNECT"
    "ESCAPE"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "OR"
    "ORDER"
    "START"
    "UNION"
    "["
    "^"
    "|"
    <EOF>

### Cause: java.lang.RuntimeException: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 52.

Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "CONNECT"
    "ESCAPE"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "OR"
    "ORDER"
    "START"
    "UNION"
    "["
    "^"
    "|"
    <EOF>
] with root cause

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 52.

Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "CONNECT"
    "ESCAPE"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "OR"
    "ORDER"
    "START"
    "UNION"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538) ~[jsqlparser-4.0.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377) ~[jsqlparser-4.0.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91) ~[jsqlparser-4.0.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:163) ~[jsqlparser-4.0.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:59) ~[jsqlparser-4.0.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:37) ~[jsqlparser-4.0.jar:na]
```

**Expected behavior**
Support `BINARY` keyword.

**System**
 - Database you are using `MySQL 5.7`
- Java Version `1.8`
- JSqlParser version `4.0`

**Comment by manticore-projects** [comment]
BINARY is defined as a keyword and thus not detected as a function.
Maybe we can fix that.
In the meantime, you may want to used the standard compliant
`CAST(value AS BINARY)`.

Best regards
Andreas

**Comment by ImSejin** [comment]
YOU SAVE MY LIFE, THANK YOU!
