### ISSUE TITLE
Cannot parse DB2 create table statement

### ISSUE THREAD

**Issue by andypdale** [JSQLParser/JSqlParser#1230]
**Description**
I am currently running into an issue when parsing some SQL for DB2, related to create table statements.

The following SQL will cause a NullPointerException when trying to parse it:

> create table TABLE_HISTORY (
        ID bigint generated by default as identity,    
        CREATED_AT timestamp not null,
        TEXT varchar(255),        
        primary key (ID)
);

The cause of the NPE seems to the 'as' before the identity

> net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "as" "AS"
    at line 2, column 36.

**To Reproduce**
1. create table TABLE_HISTORY (
        ID bigint generated by default as identity,    
        CREATED_AT timestamp not null,
        TEXT varchar(255),        
        primary key (ID)
);
2. CCJSqlParserUtil.parseStatements(sql);
3. net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "as" "AS"
    at line 2, column 36.
Was expecting one of: 
 "("
    ")"
    "+"
    ","
    "-"
    "::"
    "="
    "ASC"
    "BY"
    "CASCADE"
    "CHECK"
    "COLLATE"
    "COMMENT"
    "COMMIT"
    "CONSTRAINT"
    "DEFAULT"
    "DELETE"
    "DESC"
    "EXCLUDE"
    "FALSE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TRUE"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:188)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:176)
        at com.test.dbconvert.GeneralTests.testCreateTableParsing(GeneralTests.java:344)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Expected behavior**
As the "generated by default as identity" is valid SQL for DB2, I would expect that the parser can handle it.

**System**
 - Database  -> no database is needed to parse sql
- Java Version-> Java 8
- JSqlParser version -> tried with 3.2 and 4.0

**Comment by manticore-projects** [comment]
Confirmed, it does not seem to be supported as per 4.1 Snapshot.
I will see what I can do.

![image](https://user-images.githubusercontent.com/18080123/122202467-49637280-cec7-11eb-8b34-f539ebabf4ac.png)
