### ISSUE TITLE
exception occured when using CCJSqlParserUtil.parse to parse sqlserver sql ,version:3.1

### ISSUE THREAD

**Issue by huangxuzhi** [JSQLParser/JSqlParser#1242]
**Describe the bug**
exception occured when using CCJSqlParserUtil.parse to parse sqlserver sql

**To Reproduce**
1. Example SQL
SELECT
	[id],
	[client_id],
	[client_name],
	[client_secret],
	[redirect_uri],
	[description],
	[status],
	[vertify_type],
	[type],
	[url],
	[token_failure_time],
	[create_id],
	[create_name],
	[create_date],
	[modify_id],
	[modify_name],
	[modify_date],
	[is_delete],
	[data_source_type] 
FROM
	sys_client_details 
WHERE
	is_delete = 0 
	AND ( status = '1' AND type = '2' ) 
ORDER BY
	id DESC

2. Parsing this SQL using JSqlParser with this statements
String sql = "SELECT  [id],[client_id],[client_name],[client_secret],[redirect_uri],[description],[status],[vertify_type],[type],[url],[token_failure_time],[create_id],[create_name],[create_date],[modify_id],[modify_name],[modify_date],[is_delete],[data_source_type]  FROM sys_client_details WHERE  is_delete=0 AND (status = '1' AND type = '2') ORDER BY id DESC";
        try {
            CCJSqlParserUtil.parse(sql);
        } catch (Exception e) {
            e.printStackTrace();
        }

3. Exception
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.dongbao.salary.biz.SalaryAccountingBiz.main(SalaryAccountingBiz.java:1314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:229)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 7 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:229)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)

**Expected behavior**
parse success without exception

**System**
 - sqlserver
 - JDK1.8
 - JSqlParser version 3.1

**Comment by manticore-projects** [comment]
Greetings.

Please use a recent version of JSQLParser, e.g. 4.0 or better 4.1-Snapshot. Also you will need to activate `SquraredBracketQuotation` explicitly because `[` `]` are used for Arrays normally.

```java
boolean useSquareBracketQuotation=true;
Statement statement = CCJSqlParserUtil.parse(statementSql,
              parser -> parser.withSquareBracketQuotation(useSquareBracketQuotation));
```

[You can test it online and interactively here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsG0CWATAugKHt7AaRAxgDZICmAdgC4D6qmOO+CxZV15AhgLan0PxMWFGgGdSBAE6lKffkykokUgjQCuEpLIZMUpEZKQAHSkgD25LY0QjKHSqpGW8iAG6kJJgGYBPapW+GvFj8sEz+gU4CiOpEkaGIlKYA1hTUnhxIROqkfkg8cYJSdjl0wXKERZQ5nPll2hWkxdQoxQWIXKaKPrTodVYIHV2+NUEh8QOdSN0tVW3IIs2kRNKjITp2HNQipuoEOeFBAGIASgDyALKwIt4LQmy6tpkiGADqABIgxyCwSAu6y1VYABeWAABjqAEEAHIAEVgAAorrZ7CJgbAAOQARnRfRC0LhBzR6IATOjYABKDCnY4wz6wABCAE0fihYLTgJAMABuIA+]

Please close this issue after confirmation.

**Comment by huangxuzhi** [comment]
Thanks.I also found that someone posted the same problems before.I should check other issues first.Thanks anyway!
