### ISSUE TITLE
Failed to parse MySQL statement and add common index statement with alter

### ISSUE THREAD

**Issue by t291436520** [JSQLParser/JSqlParser#1295]
Failed to parse MySQL statement and add common index statement with alter

Version：
       <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>4.1</version>
        </dependency>
Parsed statement ：
       ALTER TABLE table_name8 ADD index (column_1) 
This statement can be executed normally in the database。

Error info :
`
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 35.

Was expecting one of:

    "COMMENT"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:215)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:203)
	at com.holder.cdc.database.dynamicSql.utils.MysqlDdl2PgDdlUtils.convert(MysqlDdl2PgDdlUtils.java:24)
	at com.holder.cdc.database.dynamicSql.utils.MysqlDdl2PgDdlUtils.lambda$main$5(MysqlDdl2PgDdlUtils.java:195)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.holder.cdc.database.dynamicSql.utils.MysqlDdl2PgDdlUtils.main(MysqlDdl2PgDdlUtils.java:192)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 35.

Was expecting one of:

    "COMMENT"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26917)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26753)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:15418)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:15646)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:547)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:213)
	... 5 more
`

Excuse me, is this the problem I use？

**Comment by manticore-projects** [comment]
Greetings.

This particular syntax
```sql
ALTER TABLE table_name8 ADD index (column_1)
```
is unsupported.

Standard compliant syntax
```sql
ALTER TABLE table_name8 ADD PRIMARY KEY (column_1)
```
will work.

**Comment by wumpz** [comment]
Unnamed indexes are not allowed but named are:

```sql
ALTER TABLE table_name8 ADD index myidx (column_1)
```

**Comment by fudianchn** [comment]
Verified on 4.2 (the release current at report time), 5.3 and current master `c86cf6a`:

| statement | 4.2 | 5.3 | master |
|---|---|---|---|
| `ALTER TABLE table_name8 ADD INDEX (column_1)` | fails | parses | parses |
| `ALTER TABLE table_name8 ADD KEY (column_1)` | fails | parses | parses |
| `ALTER TABLE table_name8 ADD INDEX myidx (column_1)` | parses | parses | parses |

Unnamed `ADD INDEX / ADD KEY (...)` parses since 5.3. (`ADD UNIQUE INDEX (column_1)` without a name parses on current master only.) Can this be closed?
