### ISSUE TITLE
sql parse error

### ISSUE THREAD

**Issue by wxlfight** [JSQLParser/JSqlParser#1312]
**Describe the bug**
sql parse error at version 4.1, which is correct  at version 2.0

**To Reproduce**
0. use jsqlparser4.1
1. Example SQL
`select date (split(tb_create_time,' ')[1]) as "交易日期",
date_format(tb_create_time,'%H:%i:%s') as "交易时间",
ooc_source as "订单号",
bar_code as "商品条码",
unit_price as "原价",
line_total_display as "实付金额",
requested_qty_display as "商品购买数量",
taobao_id as "淘宝ID",
supplier_sku_code as "货号",
date (split(wms_outbound_time,' ')[1]) as "wms出入库时间",
province as "省",
city as "市",
wh_name as "仓库名字",
direction_display as "出入库类型名称"
from `t01_day_order_detail`
where shop_info_id = 1001121719
and dayid >= '20210813'`
2. Parsing this SQL using JSqlParser with this statements
3. Exception
`net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at com.guandata.core.query.sql.JooqUtil$.extracTableNamesFromSql(JooqUtil.scala:118)
	at services.DataSourceService.getTableNameFromQuery(DataSourceService.scala:307)
	at services.DataSourceService.$anonfun$getColumnCommentMapFromDB$5(DataSourceService.scala:401)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 12.

Was expecting one of:..........`

**Expected behavior**
this sql should be parsed correctly

**System**
 - Database you are using: mysql5.6
- Java Version: 8
- JSqlParser version: 4.1

**Comment by manticore-projects** [comment]
Closed when not reproducible and without further information.
