### ISSUE TITLE
The parse of any SELECT with a column named FULLTEXT throws a JSQLParserException:

### ISSUE THREAD

**Issue by ndepomereu** [JSQLParser/JSqlParser#1359]
**Describe the bug**
The parse of any `SELECT` with a column named `fulltext `throws the `Exception`:
`net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "fulltext" "FULLTEXT"`

**To Reproduce**

Java code:
```
TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
String statement = "SELECT fulltext FROM film";
Statement parsedStatement = CCJSqlParserUtil.parse(statement); // Throws the Exception 
List<String> tables = tablesNamesFinder.getTableList(parsedStatement);
System.out.println(tables);
```
Exception throw:
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "fulltext" "FULLTEXT"
    at line 1, column 8.

Was expecting one of:

    "*"
    "STRAIGHT_JOIN"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
```

**Expected behavior**
A parse of `"SELECT fulltext FROM <table>"` should not throw an `Exception `on databases that don't have `FULLTEXT `as key word or reserved word: PostgreSQL, SQL Server and Oracle Database.
It seems MySQL is the only DB that says FULLTEXT  is a key word.

**System**
- Database you are using: not relevant.
- Java Version: 11
- JSqlParser version : 4.2

**Comment by manticore-projects** [comment]
Thank you for the report, I have enabled that keyword.
Just to get on the same page: JSQLParser is an automatically generated by JavaCC based on a Grammar, which defines tokens. Once a token is defined, it is not part of any other token unless explicitly assigned, like oversimplified:

` TABLE_NAMES = ANYTHING_ELSE | FULLTEXT_TOKEN `

This exercise has to be done for all tokens but at the same time is not allowed for a few tokens:

` TABLE_NAMES = ANYTHING_ELSE | FULLTEXT_TOKEN | TABLE_TOKEN ` would break the grammar and fail.

This is the reason why we enable such tokens mostly request driven.
Cheers.
