### ISSUE TITLE
sqlserver database parsing complex sql error, from 3.2 to the latest version of 4.2, there are problems

### ISSUE THREAD

**Issue by newbirdking** [JSQLParser/JSqlParser#1404]
Execute a complex sql and report an error directly
sql:

select k.* from( 

SELECT a.*,z.F_SCFL ,bd.F_BDZD ,bc.F_BCZD FROM 
(SELECT z.*,'cur' AS 'dqk' FROM V_CX z 
) a LEFT JOIN 
( SELECT z.* FROM T_SC z WHERE z.f_scys='4e6f9f4b-1b3a-459e-b08d-9326a6968232' ) z ON a.F_BLH = z.F_BLH 
left join ( 
select F_BLH,(SELECT '{"bt":"report1'+convert(varchar(20),F_BD_BGXH)+'","bgrq":"'+F_BD_SPARE5+'","bgzt":"'+F_BD_BGZT+'","bgnr":"'+replace(F_BDZD,'"','\\"')+'"},' FROM (
 select F_BLH,F_BD_BGXH,F_BD_SPARE5,F_BD_BGZT,F_BDZD FROM T_BDBG ) b where b.F_BLH=a.F_BLH 
for xml path('')) as F_BDZD from 
(select F_BLH,F_BD_BGXH,F_BD_SPARE5,F_BD_BGZT,F_BDZD FROM T_BDBG  ) a group by F_BLH ) bd 
on a.F_BLH=bd.F_BLH 
left join 
( select F_BLH,(SELECT '{"bt":"report2'+convert(varchar(20),F_Bc_BGXH)+'","bgrq":"'+F_BC_SPARE5+'","bgzt":"'+F_BC_BGZT+'","bgnr":"'+replace(F_BCZD,'"','\\"')+'"},' FROM (select F_BLH,F_BC_BGXH,F_BC_SPARE5,F_BC_BGZT,F_BCZD FROM T_BCBG 
 ) b where b.F_BLH=a.F_BLH 
for xml path('')) as F_BCZD from 
(select F_BLH,F_BC_BGXH,F_BC_SPARE5,F_BC_BGZT,F_BCZD FROM T_BCBG  ) a group by F_BLH ) bc 
on a.F_BLH=bc.F_BLH 

WHERE a.F_BLK in ( 'some' ) AND (a.F_SJKS IS NULL OR a.F_SJKS LIKE '%%' ) AND a.F_SDRQ < DATEADD(d,1,'2021-11-03 00:00:00.0') AND a.F_SDRQ >= '2019-02-07 00:00:00.0' 
UNION ALL

SELECT a.*,z.F_SCFL ,bd.F_BDZD ,bc.F_BCZD FROM (
 SELECT z.*,'history' AS 'dqk' FROM [p-old].dbo.V_CX z 
) a LEFT JOIN 
( SELECT z.* FROM T_SC z WHERE z.f_scys='4e6f9f4b-1b3a-459e-b08d-9326a6968232' ) z ON a.F_BLH = z.F_BLH 
left join ( 
select F_BLH,(SELECT '{"bt":"report1'+convert(varchar(20),F_BD_BGXH)+'","bgrq":"'+F_BD_SPARE5+'","bgzt":"'+F_BD_BGZT+'","bgnr":"'+replace(F_BDZD,'"','\\"')+'"},' FROM (
 select F_BLH,F_BD_BGXH,F_BD_SPARE5,F_BD_BGZT,F_BDZD FROM [p-old].dbo.T_BDBG ) b where b.F_BLH=a.F_BLH 
for xml path('')) as F_BDZD from 
(select F_BLH,F_BD_BGXH,F_BD_SPARE5,F_BD_BGZT,F_BDZD FROM [p-old].dbo.T_BDBG  ) a group by F_BLH ) bd 
on a.F_BLH=bd.F_BLH 
left join 
( select F_BLH,(SELECT '{"bt":"report2'+convert(varchar(20),F_Bc_BGXH)+'","bgrq":"'+F_BC_SPARE5+'","bgzt":"'+F_BC_BGZT+'","bgnr":"'+replace(F_BCZD,'"','\\"')+'"},' FROM (
select F_BLH,F_BC_BGXH,F_BC_SPARE5,F_BC_BGZT,F_BCZD FROM [p-old].dbo.T_BCBG 
 ) b where b.F_BLH=a.F_BLH 
for xml path('')) as F_BCZD from 
(select F_BLH,F_BC_BGXH,F_BC_SPARE5,F_BC_BGZT,F_BCZD FROM [p-old].dbo.T_BCBG  ) a group by F_BLH ) bc 
on a.F_BLH=bc.F_BLH 

WHERE a.F_BLK in ( 'some' ) AND (a.F_SJKS IS NULL OR a.F_SJKS LIKE '%%' ) AND a.F_SDRQ < DATEADD(d,1,'2021-11-03 00:00:00.0') AND a.F_SDRQ >= '2019-02-07 00:00:00.0' 
) k 

2.Use JSqlParser version from 3.2 to 4.2 ; Microsoft SQL Server 2008 R2 (SP3) ;jdk 8

@SneakyThrows
    public static List<String> select(String sql) {
        Statement parse = CCJSqlParserUtil.parse(sql);
        List<String> tableList = new TablesNamesFinder().getTableList(parse);
        return tableList;
    }

3.The errors between version 3.2 and 4.2 are as follows

 jsqlparset 3.2 version error:
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
    at line 25, column 37.

Was expecting one of:

    "("
    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "CYCLE"
    "DESCRIBE"
    "DISABLE"
    "DO"
    "DOUBLE"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "GROUP"
    "IF"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "LATERAL"
    "LEFT"
    "LIMIT"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NULLS"
    "OFFSET"
    "ON"
    "OPEN"
    "OPTIMIZE"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "PROCEDURE"
    "RANGE"
    "READ"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SESSION"
    "SET"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "XML"
    "ZONE"
    "{"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:6195)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4055)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4264)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:12580)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5840)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4055)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4362)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:12580)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5840)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4055)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4264)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3923)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3916)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)

 jsqlparset 4.2 version error:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"
    at line 25, column 28.

Was expecting one of:

    ")"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "INTO"
    "MINUS"
    "START"
    "UNION"
    "WINDOW"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:30694)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:30527)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:7692)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5443)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5736)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5324)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:13775)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:7668)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5443)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5645)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5324)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:5319)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:232)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:153)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	... 4 more

Process finished with exit code 1

The actual query results are as follows
![image](https://user-images.githubusercontent.com/5317586/140454537-66d22e0c-1bac-4cfc-bdb2-61dfe9195d67.png)

**Comment by manticore-projects** [comment]
Greetings.

[Your query parses just fine.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEDWA6AVAKAGICUDyBZWAFLLKBDMQIYqrG133EA0sAXogGYD6AzgMbsAbGgxFNYAIwAmHTlJaThohs3G8Zq+YvpY8hYqShxW1JafrMA5LwCuAJwuwAgsFgXJAR3gWtZ2DvwAbpy8AB6sxACUsBQ+IhDocABS2ACSAHJ6BuRsaL6+-rAALjy8rLF59ADqABIgmCDGXHwAntywALyuACwApgBs7ACc7F3iALQAjOIAzBRjXQCsgz1j4gAMABySY4PTAEx9FH2DfRt7+w5RLOVK2BlUXOICABYdjbIvN3TxSakZRFkjI9PhVQbRmADwIZXABvABE4kKcIAXHDbD0AA4Ae1shQmDgA1LBIFiAHYBHq4ogANQotl4zzpRD2a1gEWYj0ksgA5iFXlEiRY4YwEdzbO4UXDCbBOTwMXSegtYILhaKWEjUdLZeJuerla5VTrSbZJdLMJiBBReD0iJz5JYpZYADpStn6oUAX0Y3jBvtoBSIJCh5BlH2eXz9keUoakPL5EajidgHNkXO48vRCwTScjKdjOvV2Zzvrzkk0xajBWKUh1bvERZzNTqDXE6hebweYbdzhjZYUxYD+mDQLDDYryd7cfD44qpblCqzM7yc4LhTHFdL5aX-pw+GrklrURixYA4jgAKoABVgACEAJox9tRKTru7RNuvTpSD-Zn6wZLpJkw7EMC07bmIkJkHAFjwoikrotiuJ7NKJLkpShQ0nSDJMrALJsnmvBTm6Koijq4qmvqjyEemC7uoauoaq6RJUTyeokaKxoUUS5oYpa1q2rIvD2gaFjOq6AoGl6Prgdou56EGUEgaOMmJgRU7ripdBqTRmYaZpYgsauen6QRW76aIVaCYeEjGb6Tb1BIH4dk5UQ9lRZmJoOCnQo+YHmeCMaETq8b+VpgXzrpoUBYZDG2VGpn9jJlmqNZx45me2BXreD6gXWvCvvcTlfmooE3PZDSdk88CwIBRAWNwWIALY9Jc2aOGkAAieidtwABW8BtCkLhpOeYBgLZ2CYO+TT9W0YApAA0g0FgAKQra1vjtV1PWSOKsAADywB1FCFD0FCSJIRCSMwEyWCyewTJMj1rNMsBrGsyLvZ9ayIGsG1mFt008Lt7iwAAfJ0FgshMgxjGsexwwA7G9H1fe9v3SQw55pCkb6OGNNyApQJigswbBNPwQhgio0h2ols4SCVgkeXQXlE8YuQ5pYzwAJbcIUOLNA4PZuJ4mN5AUADaGJjFiAiSAAuogB5YogQShOEbppaYf4Af83nZCTSaWXwZTFuV7wtG0kO9AMwyjJMMxzIsyyrJs2y7AcRwnGcFxutcYJvpV7adOTylmLrfxAYpvlxWYEIG9BsGMQhOJ4ihZIUlSsC0vSjK2MyrLspOwX8nRpFihKmqUamEWKuXaqMVqterg3RomtX3EWlaNq9sJQqia4LqXHRUlxxUbPAbHUUM9qvJ+TPphzjpirj9uK6xYvvibvTW9SzLcuK8r4iq-u1n1v5FutrlnTB2XbmpizkaTzHpWLxvIUz8vGar+-Jeb1-Puu8lz71lvLJWKtEBn25FrNeGUsr3l8nWYBZgg5FQkLTcOOsQAJH-FHSCPk34yQTkTGCCIU6YjTshfUqEs4YRzlhfOhd8LhVLsRA0FdyKd3CivJU7FVxcVYQxNu3JOLcJ4nxXu7lroiTEiPFUY9-Iv0IVgreog1KlzXkubSP9FxqKUBogB+iRAJS0c-OS0swFH0gdWXg58zGmCvugu+3YXDSLXsokMRCoqGM-j4nhuiHHLiEYWP+7iVKgMPhAk+UCrIwKPHAi815EG5WfPlQOhUb6Mx-KIC2wdqq1VcA1Zq-1TCAyID1WaNVhqjXGlGSaQM+oDVgPNJarg1qlKUIDHae1DrHVOudS6sAZG3VcPdR6ExnqvTRqjH6f02RtU6o0kG4NIbQ1hvDJGKNvrfQxm6eAqAADcQA+)

But you will need to write `AllColumns` for `a` and `z` correctly as `a.*` and `z.*`.
Furthermore you will need to enable `SquaredBracketQuotation`.

Please close the issue after validation.

**Comment by newbirdking** [comment]
Thank you. I tested it and it is normal. The problem is caused by other paging plugins. Therefore, it is a third-party use problem.
