### ISSUE TITLE
“insert ignore into”  net.sf.jsqlparser.parser.ParseException: Encountered " "INTO" "into ""

### ISSUE THREAD

**Issue by yewenhaocn** [JSQLParser/JSqlParser#1418]
**Describe the bug**
when i use "insert ignore into",throw ParseException

Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.vivo.framework.mybatis.parser.SqlParserFactory.createParser(SqlParserFactory.java:50)
	... 103 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "INTO" "into "" at line 1, column 15.
Was expecting one of:
    "WITH" ...
    "SELECT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:12109)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:11965)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:670)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:82)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:54)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 104 more

**To Reproduce**
sql is 
insert IGNORE into xxxx
        <trim prefix="(" suffix=")" suffixOverrides=",">

**Expected behavior**

**System**
 - mysql
- jdk is 1.8
- JSqlParser version is 0.9.3

**Comment by manticore-projects** [comment]
Supported with JSQL Parser 4.3-Snapshot and you can [test it online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBMA4iA8lCCQxXAzgVwCNcBjAJwEtCBTM3ACmoFsBDCgGwEoAoANQEEAMgFUIYegHIAVgHsAFgDsAdABMZ1AAIBzVhyUkZTCZwA0cbnEtXJUlgupLcTCgBc5Gqk32HjAbiA+).
