### ISSUE TITLE
ParseException: Encountered unexpected token: "EXCHANGE" 

### ISSUE THREAD

**Issue by proteen** [JSQLParser/JSqlParser#1454]
### sql
alter table total_issue_info exchange partition P0001 with table total_issue_info_tmp

### Expected Behavior
the sql runs well on Navicat, I expect jsqlparser parses it also well

### Actual Behavior
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.spy.service.situation.SituationHandler.handle(SituationHandler.java:654)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exchange"  <S_IDENTIFIER>
    at line 1, column 34.

Was expecting one of:

    "ADD"
    "ALGORITHM"
    "ALTER"
    "CHANGE"
    "DROP"
    "MODIFY"

at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)

**System**
 - Database :5.7
- Java Version :1.8
- JSqlParser version:4.0

**Comment by manticore-projects** [comment]
Greetings.
This should work with latest JSQParser-4.3 (or 4.4-Snapshot).

Please confirm and close this issue.

**Comment by manticore-projects** [comment]
See `UnsupportedStatements` as explain in #1945 (unless you will sponsor or provide a specific implementation of this feature.)
