### ISSUE TITLE
Throws an exception for empty sql file

### ISSUE THREAD

**Issue by qiujiangkun** [JSQLParser/JSqlParser#1478]
But actually an empty file is a list of statements of size 0.
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token:<EOF>
    at line 4, column 1.

Was expecting one of:

    "("
    ";"
    "ALTER"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "IF"
    "INSERT"
    "MERGE"
    "PURGE"
    "RENAME"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
    <K_SELECT>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:215)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:203)
	at unidef.languages.sql.SqlParser.parse(SqlParser.scala:27)
	at api_tools.Main$.$anonfun$main$6(Main.scala:58)
	at api_tools.Main$.$anonfun$main$6$adapted(Main.scala:54)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
	at api_tools.Main$.main(Main.scala:54)
	at api_tools.Main.main(Main.scala)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 4, column 1.

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
