### ISSUE TITLE
cannot parse [1st_column]

### ISSUE THREAD

**Issue by xsgao-github** [JSQLParser/JSqlParser#1481]
**Describe the bug**
If an identifier starts with a digit but is quoted, JSqlParser fails to parse.

**To Reproduce**
1. Cannot parse: `CCJSqlParserUtil.parse("select [1st_column] FROM [dbo].[table]")`, with exception: 
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "[" "["
    at line 1, column 8.

Was expecting one of:

    "*"
    "STRAIGHT_JOIN"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at test.a.main(a.java:10)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
    at line 1, column 8.

Was expecting one of:

    "*"
    "STRAIGHT_JOIN"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31234)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31067)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:6408)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:6237)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5605)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5827)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5499)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:5494)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:232)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:153)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	... 3 more
```
2. Use double quote, still not working: `CCJSqlParserUtil.parse("select \"1st column\" FROM [dbo].[table]");`
Got this exception:
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "FROM" "FROM"
    at line 1, column 21.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ACTIVE"
    "ALGORITHM"
    "ARCHIVE"
    "ARRAY"
    "AS"
    "AT"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "CHECKPOINT"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "COSTS"
    "CYCLE"
    "DBA_RECYCLEBIN"
    "DESC"
    "DESCRIBE"
    "DISABLE"
    "DISCONNECT"
    "DIV"
    "DO"
    "DUMP"
    "DUPLICATE"
    "EMIT"
    "ENABLE"
    "END"
    "EXCLUDE"
    "EXTRACT"
    "FALSE"
    "FILTER"
    "FIRST"
    "FLUSH"
    "FN"
    "FOLLOWING"
    "FORMAT"
    "FULLTEXT"
    "GROUP"
    "HAVING"
    "HISTORY"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "JSON"
    "KEY"
    "LAST"
    "LEADING"
    "LINK"
    "LOCAL"
    "LOG"
    "MATERIALIZED"
    "NO"
    "NOLOCK"
    "NULLS"
    "OF"
    "OPEN"
    "OVER"
    "PARALLEL"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "QUERY"
    "QUIESCE"
    "RANGE"
    "READ"
    "RECYCLEBIN"
    "REGISTER"
    "REPLACE"
    "RESTRICTED"
    "RESUME"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SEQUENCE"
    "SESSION"
    "SHUTDOWN"
    "SIBLINGS"
    "SIGNED"
    "SIZE"
    "SKIP"
    "START"
    "SUSPEND"
    "SWITCH"
    "SYNONYM"
    "SYSTEM"
    "TABLE"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TIMEOUT"
    "TO"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TRY_CAST"
    "TYPE"
    "UNQIESCE"
    "UNSIGNED"
    "USER"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_NEXTVAL>
    <K_STRING_FUNCTION_NAME>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at test.a.main(a.java:12)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"
    at line 1, column 21.

```

**System**
 - SQL
- Java 1.8
- JSqlParser 4.3

**Comment by wumpz** [comment]
Since some versions, JSqlParsers default for square brackets is array processing. If you want to accept square bracket quotation you have to switch in on:  https://github.com/JSQLParser/JSqlParser/issues/1159. 

```
CCJSqlParserUtil.parse("select [1st_column] FROM [dbo].[table]", parser -> parser.withSquareBracketQuotation(true));
```

This should work.

**Comment by manticore-projects** [comment]
> This should work.

In JSQLParser, **Column Names can't start with a Digit** and even with `SquarredBracketQuotation` enabled the statement will fail to parse.
You can test this (online here0(http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEDaAzAlgJwM4BcD6BjA9gDYCuAtgHYC6AUAGIBKA8gLIIAmARvpQHTyYBDDoQCmNANzVqAWmmxEA5KLaxM+eflSkBmWFgGpM1dCNG5d8AIxY8RMlVgMW7Lr35DRlSbPmLlq9URNbV0RcjYgA+]

**Comment by wumpz** [comment]
@manticore-projects Wow. You are right. I found this `~["0"-"9","]"]` part in the grammar for quoted parts. This seems to be an ancient part of the grammar when JSqlParser just supported simple array addressing like `[5]`. 

I removed it and all tests are still succeeding. 

Please try it out if you find problems.

**Comment by wumpz** [comment]
Since nobody seems to object ..
