### ISSUE TITLE
sqlserver db link error

### ISSUE THREAD

**Issue by kingschan1204** [JSQLParser/JSqlParser#149]
select tid,t_remark,t_status,b.name,t_date 
from LINK_100.htsac.dbo.t_transfer_num  a
left join LINK_100.htsac.dbo.t_user_info b on a.t_creater=b.pid 
where a.t_creater=''

**Comment by kingschan1204** [comment]
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at DefaultSqlParser.init(DefaultSqlParser.java:63)
	at DefaultSqlParser.<init>(DefaultSqlParser.java:48)
	at ParserDemo.main(ParserDemo.java:10)
Caused by: java.lang.IllegalArgumentException: LINK_100 is not a valid database reference
	at net.sf.jsqlparser.schema.Server.<init>(Server.java:37)
	at net.sf.jsqlparser.parser.CCJSqlParser.Table(CCJSqlParser.java:1438)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:2979)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1705)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1589)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1550)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:111)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:66)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 3 more
Caused by:
java.lang.IllegalArgumentException: LINK_100 is not a valid database reference
	at net.sf.jsqlparser.schema.Server.<init>(Server.java:37)
	at net.sf.jsqlparser.parser.CCJSqlParser.Table(CCJSqlParser.java:1438)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:2979)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1705)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1589)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1550)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:111)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:66)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at DefaultSqlParser.init(DefaultSqlParser.java:63)
	at DefaultSqlParser.<init>(DefaultSqlParser.java:48)
	at ParserDemo.main(ParserDemo.java:10)
Exception in thread "main" java.lang.NullPointerException
	at DefaultSqlParser.toString(DefaultSqlParser.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.io.PrintStream.println(PrintStream.java:821)
	at ParserDemo.main(ParserDemo.java:18)
