### ISSUE TITLE
sqlserver database parsing insert sql error using geometry::STGeomFromText

### ISSUE THREAD

**Issue by ReedZheng** [JSQLParser/JSqlParser#1492]
**To Reproduce:**

public static void main(String[] args) throws JSQLParserException {
        String sql = "INSERT INTO test.dbo.china(id, geom, adcode, name, center, centroid, childrenNum, level, parent, subFeatureIndex, acroutes, adchar) VALUES(?, geometry::STGeomFromText(?,4326), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Insert insert = (Insert) sqlParser.parse(new StringReader(sql));
        List columnList = insert.getColumns();
}

**Run result:**
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 162.

Was expecting one of:

    "&"
    ")"
    ","
    "::"
    "<<"
    ">>"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:25)
	at com.example.Test.main(DBPlugin.java:389)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 162.

Was expecting one of:

    "&"
    ")"
    ","
    "::"
    "<<"
    ">>"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:2044)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:143)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:23)
	... 1 more

**System:**
Database you are using=SQLServer
Java Version=1.8
JSqlParser version=4.0

**Comment by ReedZheng** [comment]
? and :: can not exist together
