### ISSUE TITLE
当子sql 的子sql 中存在JSON_OBJECT时sql解析器无法解析

### ISSUE THREAD

**Issue by 532780857** [JSQLParser/JSqlParser#1495]
```
SELECT (SELECT JSON_ARRAYAGG(obj)
        FROM (
#                 当子sql 的子sql 中存在JSON_OBJECT时sql解析器无法解析
                 SELECT JSON_OBJECT('account', t1.account) as obj
                 FROM tb_team t1 LEFT JOIN tb_person t2 on t1.account = t2.account
             ) t
       ) as teamMember
FROM tb_team t1


```

**Comment by 532780857** [comment]
`SELECT (SELECT JSON_ARRAYAGG(obj)
        FROM (
#                 当子sql 的子sql 中存在JSON_OBJECT时sql解析器无法解析
                 SELECT JSON_OBJECT('account', t1.account) as obj
                 FROM tb_team t1 LEFT JOIN tb_person t2 on t1.account = t2.account
             ) t
       ) as teamMember
FROM tb_team t1
`

**Comment by manticore-projects** [comment]
Greetings.

[`JSON_OBJECT`](http://217.160.215.75:8080/jsqlformatter/_static/JSqlParserCC.xhtml#JsonFunction) and [`JSON_ARRAYAGG`](http://217.160.215.75:8080/jsqlformatter/_static/JSqlParserCC.xhtml#JsonAggregateFunction) are supported but your syntax does not seem to be compliant (with the SQL Standard or the [Oracle Reference](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/JSON_OBJECT.html#GUID-1EF347AE-7FDA-4B41-AFE0-DD5A49E8B370))

**Comment by 532780857** [comment]
升级到4.3之后，依然出现异常，使用的是mysql8.0，在Navicat下执行sql正常
<img width="2007" alt="image" src="https://user-images.githubusercontent.com/39074601/160773401-adb04e53-4f2d-48ba-adb3-c85a84cbd4c0.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/39074601/160773480-9ffa1247-bf94-4bf6-9c20-5b0135defa2c.png">


```
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT (SELECT JSON_ARRAYAGG(obj)
                FROM (
                 SELECT JSON_OBJECT('account', tt.account) as obj
                 FROM tb_team tt
                         ) t
               ) as teamMember
        FROM tb_team t1
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:65)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy171.query(Unknown Source)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:132)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy171.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 46 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 9.

Was expecting one of:

    "!"
    "("
    "NOT"
```

**Comment by 532780857** [comment]
success code
```
SELECT
	( SELECT JSON_ARRAYAGG( obj )  FROM ( SELECT JSON_OBJECT( 'account', '11' ) AS obj  ) t  ) AS teamMember 
FROM
	tb_team t1
```
<img width="1933" alt="image" src="https://user-images.githubusercontent.com/39074601/160778847-c91a1651-875e-4a59-8584-70314a8048b6.png">

bad sql code 
```
SELECT
	( SELECT JSON_ARRAYAGG( obj )  FROM ( SELECT JSON_OBJECT( 'account', tb_team.account ) AS obj  FROM tb_team) t  ) AS teamMember 
FROM
	tb_team t1
```
<img width="1953" alt="image" src="https://user-images.githubusercontent.com/39074601/160778967-a6fc65a0-45f9-48d0-8a05-07ecb7262253.png">

JSON_OBJECT使用了tb_team的字段时就会抛出异常
请修复一下

**Comment by 532780857** [comment]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/39074601/160779606-728139ca-3ef7-419a-9c83-5768f17d5fdd.png">
最后查到的问题，JSON_OBJECT中使用到字段时，解析器无法识别

**Comment by wumpz** [comment]
So could you exactly describe your syntax and add the specific documentation to it?

**Comment by manticore-projects** [comment]
Duplicate #1504
