### ISSUE TITLE
cannot parse mysql column in JSON_OBJECT function

### ISSUE THREAD

**Issue by 532780857** [JSQLParser/JSqlParser#1504]
Mysql version: 8.0

JSQLParser verison: 4.3

sql example：

```sql
// this is bad sql
SELECT JSON_OBJECT('account',account) as obj FROM tb_team;

// this is success sql
SELECT JSON_OBJECT('account','some string') as obj FROM tb_team;
```

bad sql exception:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/39074601/161875351-a62869fd-8a6b-4de2-b814-c69aa6ea63c7.png">

## DDL

```sql
CREATE TABLE `tb_team` (
  `id` bigint(20) NOT NULL COMMENT '雪花id',
  `process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程id',
  `relevance_id` bigint(20) DEFAULT NULL COMMENT '发布id',
  `apply_id` bigint(20) DEFAULT NULL COMMENT '报名id',
  `account` varchar(32) DEFAULT NULL COMMENT '学工号',
  `originator` varchar(32) DEFAULT NULL COMMENT '发起人',
  `team_type` tinyint(4) DEFAULT NULL COMMENT '类型',
  `member_type` tinyint(4) DEFAULT NULL COMMENT '成员类型',
  `join_type` tinyint(4) DEFAULT NULL COMMENT '加入类型',
  `open_status` tinyint(4) DEFAULT NULL COMMENT '成员状态',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `updater` varchar(64) DEFAULT NULL COMMENT '修改者',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '删除标志',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '租户id',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='队伍成员表';
```

<img width="666" alt="image" src="https://user-images.githubusercontent.com/39074601/161875390-7e7d893b-0f20-49ba-94e0-4a1b0f9c8781.png">

An exception will occur if the 'account' column comes from the tb_team table

**Comment by manticore-projects** [comment]
Supported  **Standard Compliant** Syntax is shown [here](http://217.160.215.75:8080/jsqlformatter/_static/JSqlParserCC.xhtml#JsonObject).

```sql
// this was the correct syntax
SELECT JSON_OBJECT(key 'account' value account_col) as obj FROM tb_team;

// this was also the correct syntax
SELECT JSON_OBJECT(key account :  account_col) as obj FROM tb_team;

// this was also the correct syntax
SELECT JSON_OBJECT( account : account_col) as obj FROM tb_team;

// this is success sql
SELECT JSON_OBJECT('account','some string') as obj FROM tb_team;
```

You can [test it here online](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20PTAEBcAsEsGdQO4EN5QKagMYHsBOu1NxRYBPAO3CQA8AoAZQFEAZRgYQBVQApegeQByAfT4Ahbuw4AKANZpSoAORJMOAK6VFoAG5IANmowr1lITj0BKUClDYARgCtQAMQBKfALIQ7Q8GiQAtgDctLQgEDDwyPD6sNgRGDj4hMRklDQMLJI8-MJiEpyy8taq2BrEAFygJSbgZtiW1vD2Tm6e3r7+waHhUHCINrHx6Fh4BEQkFFR0TKycOYIi4pJSNWWUoFXG63XmVjYtLu5e4D5+gSFhYH3w-bBqqmiw8LAAjnqZc1y8i-kryqVyooADSKOIBDCwcC4aDkADmin2zUcR3ap06FyAA+)

**Comment by 532780857** [comment]
Thank you on behalf of 阿里渣渣Java r&d team

**Comment by 532780857** [comment]
```
        SELECT JSON_ARRAYAGG(obj) FROM (
           SELECT JSON_OBJECT('account':trr.account,'accountName':tp.person_name) obj
           FROM tb_review_result trr
                    LEFT JOIN tb_person tp ON trr.account = tp.account
           WHERE
               trr.relevance_id = ?
             AND trr.apply_id = ?
             AND trr.task_id = ?
             AND trr.review_type = ?
             AND trr.deleted = 0
           ORDER BY trr.create_time DESC
        )tmp
     ) experts
        FROM tb_contests_apply tca
                 LEFT JOIN tb_contests_team_type tctt on tca.team_type_id = tctt.id AND tca.handle_id = tctt.handle_id
                 LEFT JOIN tb_person tp ON tca.creator = tp.account
        WHERE
            tca.relevance_id = ?
            AND tca.apply_id = ?
            AND tca.deleted = 0
        ORDER BY tca.create_time DESC
 ) tmp_count
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:69)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy167.query(Unknown Source)
	at com.github.pagehelper.util.ExecutorUtil.executeAutoCount(ExecutorUtil.java:169)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:178)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:121)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy167.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 148 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 7, column 9.

Was expecting one of:

    "!"
    "("
    "NOT"
```

<img width="383" alt="image" src="https://user-images.githubusercontent.com/39074601/161950462-566b3998-214a-4895-9466-062b86e5d44e.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/39074601/161950510-743ffc0e-0f9a-4f71-831a-7258e7edcf48.png">

Still abnormal

**Comment by 532780857** [comment]
An error is also reported if there are tables and fields in the middle

**Comment by manticore-projects** [comment]
> JSON_OBJECT('account':trr.account,'accountName':tp.person_name)

I checked the EBNF, only `S_IDENTIFIER` is allowed for the second key which looks odd to me. I will have a look into this.
```sql
SELECT JSON_ARRAYAGG( obj )
FROM (  SELECT JSON_OBJECT( account:account, accountName:person_name ) obj
        FROM tb_review_result trr
            LEFT JOIN tb_person tp
                ON trr.account = tp.account
        WHERE trr.relevance_id = ?
            AND trr.apply_id = ?
            AND trr.task_id = ?
            AND trr.review_type = ?
            AND trr.deleted = 0
        ORDER BY trr.create_time DESC  )
;
```

However, you Example is corrupted and the brackets are not balanced.

**Comment by 532780857** [comment]
```

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserManager;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.select.SelectItem;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        // this is true
        test_select_items("SELECT JSON_OBJECT(key person value account,key personName value account_name) obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
        // this is true
        test_select_items("SELECT JSON_OBJECT(person:account,personName:account) obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
        // this is bad
        test_select_items("SELECT JSON_OBJECT(person:trr.account,personName:tp.account) obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
        // this is bad
        test_select_items("SELECT JSON_OBJECT(person:'1',personName:'1') obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
        // this is bad
        test_select_items("SELECT JSON_OBJECT(key person value '1',key personName value '1') obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
    }


    // *********select body items内容
    public static List<String> test_select_items(String sql) {
        CCJSqlParserManager parserManager = new CCJSqlParserManager();
        Select select = null;
        try {
            select = (Select) parserManager.parse(new StringReader(sql));
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }
        PlainSelect plain = (PlainSelect) select.getSelectBody();
        List<SelectItem> selectitems = plain.getSelectItems();
        List<String> str_items = new ArrayList<String>();
        if (selectitems != null) {
            for (int i = 0; i < selectitems.size(); i++) {
                str_items.add(selectitems.get(i).toString());
            }
        }
        return str_items;
    }
}

```

**Comment by manticore-projects** [comment]
Thank you for reporting, I would look into your examples tomorrow.

**Comment by 532780857** [comment]
What should I do?
Can it be filtered?

**Comment by 532780857** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/39074601/162127259-991bba09-9bce-43a0-93ab-8e8d3849d8c6.png">
The official tutorial！
Can you support an example like this？

**Comment by manticore-projects** [comment]
You can try the attached JAR file, which contains all the goodies from the PR.
I have tested all your variants. Do let me know when anything is left open (plain failing SQL would be sufficient).

Thank you again for reporting, cheers
[jsqlparser-4.3-SNAPSHOT.zip](https://github.com/JSQLParser/JSqlParser/files/8440954/jsqlparser-4.3-SNAPSHOT.zip)
.

**Comment by 532780857** [comment]
An exception occurred when using a function in JSON_OBJECT
```
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select count(0) from ( 
SELECT
         
         
            *
         
        FROM
        (SELECT
            tct.id as relevance_id,
            tct.declare_id,
            '0' as review_type,
            tct.contests_name,
            tct.contests_level,
            tct.contests_type,
            tct.principals,
            tp.person_name,
            tct.deleted,
        (SELECT JSON_ARRAYAGG(obj) FROM (SELECT trt.relevance_id,JSON_OBJECT('id',CAST(trt.id AS CHAR),'taskName',trt.task_name,'openStatus',trt.open_status,'taskSort',trt.task_sort) as obj  FROM tb_review_task trt ORDER BY trt.task_sort ASC)tmp  WHERE tmp.relevance_id = tct.id)  as task_sort_list,
        IFNULL((SELECT COUNT(id) FROM tb_contests_apply tcp WHERE tcp.handle_id = tct.id AND tcp.contests_state = 1 AND tcp.deleted = 0),0) as total,
--         (SELECT COUNT(id) FROM tb_review_task trt WHERE trt.relevance_id = tct.id AND trt.review_type = 0 AND trt.task_sort = 1 AND trt.deleted = 0) as calculated
        IFNULL((SELECT COUNT(id) FROM tb_review_total_score WHERE relevance_id = tct.id AND deleted = 0 GROUP BY apply_id),0) as calculated
        FROM tb_contests_transact tct
        LEFT JOIN tb_person tp ON tp.account = tct.principals) tmp
            WHERE (deleted = ?)
 ) tmp_count
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:72)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy166.query(Unknown Source)
	at com.github.pagehelper.util.ExecutorUtil.executeAutoCount(ExecutorUtil.java:169)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:178)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:121)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy166.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 157 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 18, column 10.

Was expecting one of:

    "!"
    "("
    "NOT"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:32047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31880)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:9818)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:9757)
	at net.sf.jsqlparser.parser.CCJSqlParser.XorExpression(CCJSqlParser.java:9738)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:9811)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:9757)
	at net.sf.jsqlparser.parser.CCJSqlParser.XorExpression(CCJSqlParser.java:9738)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:9709)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:6338)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:6490)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:6328)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5663)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5892)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5540)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:14458)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:8013)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5676)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5892)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5540)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:14458)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:8013)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5676)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5892)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5540)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:5534)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:223)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:144)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)

```

```
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserManager;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.select.SelectItem;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        // this is bad
        test_select_items("SELECT JSON_OBJECT('account', CAST(trr.account AS CHAR)) obj FROM tb_review_result trr LEFT JOIN tb_person tp ON trr.account = tp.account");
    }


    // *********select body items内容
    public static List<String> test_select_items(String sql) {
        CCJSqlParserManager parserManager = new CCJSqlParserManager();
        Select select = null;
        try {
            select = (Select) parserManager.parse(new StringReader(sql));
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }
        PlainSelect plain = (PlainSelect) select.getSelectBody();
        List<SelectItem> selectitems = plain.getSelectItems();
        List<String> str_items = new ArrayList<String>();
        if (selectitems != null) {
            for (int i = 0; i < selectitems.size(); i++) {
                str_items.add(selectitems.get(i).toString());
            }
        }
        return str_items;
    }
}
```

**Comment by manticore-projects** [comment]
Unfortunately your examples are overly complex. I will appreciate when you bisect the relevant failing fragments, e.g.

```sql

SELECT JSON_ARRAYAGG(obj) FROM (SELECT trt.relevance_id,JSON_OBJECT('id',CAST(trt.id AS CHAR),'taskName',trt.task_name,'openStatus',trt.open_status,'taskSort',trt.task_sort) as obj FROM tb_review_task trt ORDER BY trt.task_sort ASC)
```

Also I do not need any Java Code, when analyzing parser errors, just the causing SQL fragment.

That said, I have pushed another change in order to allow Expressions as Values in `JSON_OBJECT`. This parses the statement above correctly. Please give it a try.

**Comment by manticore-projects** [comment]
Your provided example is invalid, again brackets are not balanced.
After correcting your SQL and with the mentioned support of `Expression`, your example parses well and [you can test it here online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYApa1AhnwBcBjEgOgEsATWAQWFgCcBTAGzYDcBDAOzJsA+nUT4JkqfgA0sclVpsyHXu1G1x07bNgByAAx7Gzdt2psA7sJIBPAA5stO6XIWUyAe34k2AZxI-YX5eAFsnF203Cg9vXwCgrm5OZ0iJaKovH39AmwcItMkMynsWakFqe14OP1TCt3sSthY-b2CwgsLddyUuX00u9NwCcCg4AClgdAA5YQZUVAYATQYAcVW8TwAjACtYAEo6wdg0LGGRojh5Fip2JIEhDSPj47lJmeF0ACFxsbw9Oh6OSQJjQHAkG40ehMWCQAAS832cj0JF4fgA1tMOkDrlRURj2uFkZ5HPxgKiSABXPw4iFUElsfjCAK8Kl+ZH49HATw3WmQznMnkkA4mWDbHbPF5SU7YEhbYRmCzWTm4yVSiToVAAERAqFgXyWuMoAtaNxMkHw+3koXsarSAHU4bqQNbGnceA8RHRYABeeQxb1WmEmoXCDjUAJ21ywACSADN+JSOBw8HhCGNYZ5KT48IGo1KZfJ5Vl4rlePZ7BxbP7berIo7nTXKAALAS0LgaX3+qhiOtdBjTLVNks5IIs3xdgCM+b7A6H5EavTY-S7BgOcjXQeYJE8qI4M6G8cTydTFwzkCzOdgeb7OkLcoVPCVNl31WZXnYB8GDdQLvdfEEL16D9dxe1vSI51gJcVz9Awvy6VYMAAVQABX1Q1y0rWxOyRWBN1FMhqjIJNWTYAZtHvYs4lHGwWAEPxeAobt8wgZAJnQGNpiLYRHBabx5FrY4ZgEyhGK8bNhRAmJSnKMhKmqPwRRIG1EB-F08GgsiuwAfgORAAG4gA+)

**Comment by 532780857** [comment]
// bad  streamline sql
```
SELECT JSON_ARRAYAGG(JSON_OBJECT('teamTypeId',CAST(tre.team_type_id AS CHAR))) as team_type_ids FROM tb_review_expert tre LEFT JOIN tb_person tp ON tre.account = tp.account

```

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/39074601/162401843-88b470b4-5c64-494b-adf0-70884a9005f4.png">

**Comment by manticore-projects** [comment]
Unfortunately your concern is not clear.
Although the provided statement [parses correctly](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBSwDyA5A+gQQEpYwTQwHFCAKBZdJAIXimjIHIAXAUwEMBbaATwAcWAkgBMGAGliQMwekwBOLAHStOaJnxZoAlkNhSJACWwBKWCdO7gsZR1XqtQgM4AoAGJYkAWSsAjNPIBumiwA7mgsAB78skxW8k6wCbAQLnDwSAIoPmhRDgD2AHZWvPGJpaiximwAxlW5AK75MQC8RQrVtQ1MTgDcQA+)

**Comment by 532780857** [comment]
Using jSQLParser-4.4-snapshot.jar succeeded

**Comment by hsiong** [comment]
> test it here online

adding the annotation @InterceptorIgnore(tenantLine = "true") to the mapper may solve this problem  .

**Comment by hsiong** [comment]
adding the annotation @InterceptorIgnore(tenantLine = "true") to the mapper may solve this problem .

**Comment by pigping88** [comment]
@Select("SELECT meter_id," +
            "   JSON_OBJECTAGG(datarq, daily_usage) AS data," +
            "   SUM(daily_usage)                    AS total" +
            " FROM (SELECT meter_id," +
            "              datarq," +
            "              zxyg - LAG(zxyg) OVER (PARTITION BY meter_id ORDER BY datarq) AS daily_usage" +
            "       FROM tcmr_data_day" +
            "       WHERE datarq BETWEEN '2024-11-01' AND '2024-11-13') AS daily_usage_data" +
            " GROUP BY meter_id")
    IPage<DataDayRespVO> dailyUsageList(Page<DataDayDO> page, DataDayPageReqVO reqVO);
    jSQLParser-5.0 mysql 8 

    Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "JSON_OBJECTAGG" "JSON_OBJECTAGG"
    at line 1, column 20.

Was expecting one of:

    "!"
    "("
    "*"
    "NOT"
