### ISSUE TITLE
Encountered unexpected token: "WITH" "WITH"

### ISSUE THREAD

**Issue by Style1002** [JSQLParser/JSqlParser#1509]
**Describe the bug**
mysql SQL support: process the summary of states. 

**To Reproduce**
1. SQL: SELECT name, SUM(score) FROM table_name GROUP BY name WITH ROLLUP
2. Method: Parsing this SQL using CCJSqlParserUtil.parse(sql)
3. Exception: Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.wwei.demo.DemoApplication.main(DemoApplication.java:14)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "WITH" "WITH"
    at line 1, column 55.

**Expected behavior**
can parsed
**System**
- JSqlParser version is 4.4

**Comment by manticore-projects** [comment]
Greetings.

`WITH ROLLUP` is not supported.
Since it is not standard compliant, you likely would need to provide a PR or sponsor an implementation to get that implemented.

**Comment by Style1002** [comment]
👌
Thanks for responding!
