### ISSUE TITLE
Load data from a function error

### ISSUE THREAD

**Issue by kingschan1204** [JSQLParser/JSqlParser#151]
select * from tables a left join getdata() b on a.id=b.id

----------------------------------------------------------------------------------------------

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at DefaultSqlParser.init(DefaultSqlParser.java:63)
	at DefaultSqlParser.<init>(DefaultSqlParser.java:48)
	at ParserDemo.main(ParserDemo.java:10)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 41.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ON" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "JOIN" ...
    "LEFT" ...
    "CROSS" ...
    "OPEN" ...
    "FULL" ...
    "WHERE" ...
    "FOR" ...
    "PIVOT" ...
    "XML" ...
    "USING" ...
    "GROUP" ...
    "INNER" ...
    "RIGHT" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "NATURAL" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "PIVOT" ...
    "PIVOT" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "ON" ...
    "USING" ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "INNER" ...
    "NATURAL" ...
    "CROSS" ...
    "JOIN" ...
    "," ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13897)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13767)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 3 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 41.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ON" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "JOIN" ...
    "LEFT" ...
    "CROSS" ...
    "OPEN" ...
    "FULL" ...
    "WHERE" ...
    "FOR" ...
    "PIVOT" ...
    "XML" ...
    "USING" ...
    "GROUP" ...
    "INNER" ...
    "RIGHT" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "NATURAL" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "PIVOT" ...
    "PIVOT" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "ON" ...
    "USING" ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "INNER" ...
    "NATURAL" ...
    "CROSS" ...
    "JOIN" ...
    "," ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13897)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13767)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at DefaultSqlParser.init(DefaultSqlParser.java:63)
	at DefaultSqlParser.<init>(DefaultSqlParser.java:48)
	at ParserDemo.main(ParserDemo.java:10)
Exception in thread "main" java.lang.NullPointerException
	at DefaultSqlParser.toString(DefaultSqlParser.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.io.PrintStream.println(PrintStream.java:821)
	at ParserDemo.main(ParserDemo.java:18)

**Comment by wumpz** [comment]
Was fixed by a pull request some time ago.
