### ISSUE TITLE
MySQL parsing exception - ColumnDefinition - COLLATE BINARY

### ISSUE THREAD

**Issue by agarman** [JSQLParser/JSqlParser#1518]
**Describe the bug**
Parse returns exception
```
Was expecting one of:

    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31468)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31301)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColDataType(CCJSqlParser.java:15610)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnDefinition(CCJSqlParser.java:14312)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:14640)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:281)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:153)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	... 26 more
```

**To Reproduce**
```
    @Test
    public void testParseCollateConstraint()
    {
        String sql = "CREATE TABLE `s` (`a` enum('a','b','c') CHARACTER SET binary COLLATE binary)";
        try
        {
            CCJSqlParserUtil.parse(sql);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
```

**Expected behavior**
Call returns Statement

**System**
 - MySQL
- Java 1.8, 9, 11, 17
- JSqlParser 4.4

**Comment by manticore-projects** [comment]
'BINARY' is a restricted keyword not allowed/supported in this context.

**Comment by agarman** [comment]
MySQL not only accepts it in this context, it also normalizes to this in its binary log.

Relevant MySQL documentation:
https://dev.mysql.com/doc/refman/8.0/en/charset-binary-set.html
https://dev.mysql.com/doc/refman/8.0/en/charset-binary-collations.html

The sample SQL provided will execute successfully on 5.x and later versions of MySql.

```sql
-- qux.binCol definition
CREATE TABLE example (
    e enum('a','b','c') CHARACTER SET binary COLLATE binary DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```
