### ISSUE TITLE
WITH ... AS ( DELETE ... RETURNING )

### ISSUE THREAD

**Issue by dfcatdivvy** [JSQLParser/JSqlParser#1550]
The following is valid in postgresql but gives an error in JSqlParser
```sql
WITH updated_rows AS (
    DELETE FROM documents WHERE something='something'
    RETURNING *
)
SELECT * FROM updated_rows LIMIT 1000;
```

Error:
```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "DELETE" "DELETE"
    at line 2, column 5.

Was expecting one of:

    "("
    "VALUE"
    "VALUES"
    "WITH"
    <K_SELECT>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:327)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:299)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:274)
	...
```

**Comment by manticore-projects** [comment]
Working now on it.

**Comment by manticore-projects** [comment]
Duplicate #1916

**Comment by manticore-projects** [comment]
This has been resolved recently.
