### ISSUE TITLE
Encountered unexpected token: "member"

### ISSUE THREAD

**Issue by lovlyhao** [JSQLParser/JSqlParser#1631]
代码如下
`String sql= "SELECT  \n" +
              " id,cxr_employee_id,cxr_post_id,cxr_site_id,cxr_region_id,in_charge_start_time,in_charge_end_time,charge_status,create_by,create_time,update_by,update_time,revision,create_by_name,create_by_type,update_by_name,update_by_type,delete_by,delete_by_name,delete_by_type,delete_time,delete_status,sort_num,remark,sys_dept_id,spare_id \n" +
              "  FROM cxr_employee_post      \n" +
              " WHERE  (  '106' member of (cxr_post_id->'$.value') )";

        Select stmt = (Select) CCJSqlParserUtil.parse(sql);`

报错如下：

Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "member" <S_IDENTIFIER>
    at line 4, column 18.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.example.demo3.controller.Main.main(Main.java:21)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "member" <S_IDENTIFIER>
    at line 4, column 18.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	... 3 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "member" <S_IDENTIFIER>
    at line 4, column 18.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:33398)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:33231)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:10313)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:10259)
	at net.sf.jsqlparser.parser.CCJSqlParser.XorExpression(CCJSqlParser.java:10241)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:10212)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:9494)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:6205)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:6406)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:6054)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:6049)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:248)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:157)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by manticore-projects** [comment]
Greetings,

MySQL [MEMBER OF Operator](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of) is not supported yet.

Syntax is: [value MEMBER OF(json_array)](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of)

Example:
```sql
SELECT 17 MEMBER OF('[23, "abc", 17, "ab", 10]');
```

**Comment by lovlyhao** [comment]
@manticore-projects  thank you very much.

**Comment by RekaDowney** [comment]
> > @manticore-projects As I have stated, the MySQL specific `MEMBER OF` operator is not supported by JSQLParser.
Is there any plan to support `MEMBER OF` operator
