### ISSUE TITLE
BUG order by  CONVERT(NAME  USING gbk) 

### ISSUE THREAD

**Issue by a4882567** [JSQLParser/JSqlParser#1654]
Unable to resolve order by CONVERT (NAME USING gbk)

**Comment by a4882567** [comment]
error msg net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("   at line 1, column 112. Was expecting one of: 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:33398)at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:33231)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:167)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)

**Comment by a4882567** [comment]
version :
     <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>4.5</version>
        </dependency>

**Comment by a4882567** [comment]
> Unable to resolve order by CONVERT (NAME USING gbk)
