### ISSUE TITLE
Oracle: Field named CACHE in projection leads to error

### ISSUE THREAD

**Issue by andghe** [JSQLParser/JSqlParser#1655]
Hi

Whenever an unquoted field named `CACHE` (among others) is part of the projection, e.g. using the following query

```sql
-- https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/ALL_ALL_TABLES.html
SELECT CACHE FROM SYS.USER_ALL_TABLES
```

the parser (version 4.5) reports

```text
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CACHE" "CACHE"
    at line 1, column 8.

Was expecting one of:

    "*"
    "STRAIGHT_JOIN"
```

When aliasing the table, e.g.

```sql
SELECT t.CACHE FROM SYS.USER_ALL_TABLES t
```

the exception changes to

```text
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 9.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at TestMain.main(TestMain.java:26)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 9.
```

When wrapping the word `CACHE` with double quotes, it works fine.

```sql
SELECT t."CACHE" FROM SYS.USER_ALL_TABLES t
```

The shown behavior does apply to other keywords such as HAVING or INTO.

**Comment by manticore-projects** [comment]
Good Morning, thanks for reporting.

This Keyword problem has been fixed already and you can use latest JSQLParser 4.6 Snapshot from Github Source.

I have tested your statement successfully.
