### ISSUE TITLE
explain col in sqlserver

### ISSUE THREAD

**Issue by dulm** [JSQLParser/JSqlParser#1660]
In sqlserver, then `explain` is valid col name, not reserved keyword

```
SELECT  BillID,BillDate,BillCode,BillType,Comment,ERec,KRec,Posid,SaleEtypeid,totalmoney,totalqty,DiscountMoney,Cash,Change,explain,Flags,HandOverDate,MachineNo,LinkStatus,multiple,BuyerName,CurrIntegral,CurrIntegralTotal,SS_ID,SS_Status,Vipid,ifcheck,draft,DisTinyMoney,printtime,SQERec,SaleChecke,RxChecke,ShopCashID,ShopCashCode,ShopSaleID,ShopSaleCode,ShopPromoID,ShopPromoCode,BillFlags,GroupID,VipChange,UniqueBIllid,billstatus,CZBalance,BillCash,_MD  FROM RetailBillIndex_His 
 
 WHERE (Posid = ?)
```

```
Change[124],[125]explain,Flags,
```

when 3.2, with error
```
by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "explain" "EXPLAIN"
    at line 1, column 125.
```

then i upgrade to 4.4, with error
```
	... 5 more
Caused by: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "," ","
    at line 1, column 124.

Was expecting one of:

    "&"
    "::"
    ";"
   ..........
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190) ~[jsqlparser-4.4.jar:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63) ~[jsqlparser-4.4.jar:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38) ~[jsqlparser-4.4.jar:?]
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:34) ~[mybatis-plus-extension-3.4.1.jar:3.4.1]
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:70) ~[mybatis-plus-extension-3.4.1.jar:3.4.1]

```

**Comment by manticore-projects** [comment]
Please try latest JSQLParser 6.4 Snapshot from GitHub Source. It has a much better Keywords handling and [parses your statement just fine. Try here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsCMCWAbFSAmAoevcBpFUUMBDAFwFMc8Ci0BjAew2truTXIE8AHN9rELMAtiMoA7cjXaFKAJ0oMZtQgGtFywUNi8mAZ0wq8hfaRSVKPfke2FyTcuZFMJlbsboOnKAI49PeEIMJH1mAFcpFzcPO1gGUn0AC0CdBiTSCQBzAVlYSgAPXhRSJAlUwgAzEqz9CtgMiQwmADcFMip6kVJ0sskmevQJNX0ncnC6uJFwlHIkYtzVRHDuBQlScXqGcPl5Mqos+XMtnb2pSkPzb2O4-X0AfVtBUwfRign6lvmnvKRK9KUanqGCOlWkcRCozK3Gi7nqvDO5Dmm1uvgUSnqZgsAIYakWJlg8gKOLxmKSTF4CWSPyWyQpVKSzFYZIpWMoNIJdN4bKZ+LoXIRTBcHP55N4gpcvPqnBQ1VItXqhyY4V4IqCsC+lMaOXqkSQvnClBlap0Mre40mz3iAC8EOZMgw+eqZQz6vcRNgAGIAJQA8gBZQlWUooY1NQr3JKhLAAdQAEiBvSBYAAKXQGTCwAC8sAA-LAAJRYADcQA)
