### ISSUE TITLE
Oracle database, "delete from xxx like '%||'aaa'||'%'" parsing exception

### ISSUE THREAD

**Issue by xiaostart977** [JSQLParser/JSqlParser#1667]
use Oracle Database，"delete from xxx like '%||'aaa'||'%'" parsing exception

example
```sql
delete from XXX
where DEPT like '%'||'aaa'||'%'
```

cause info
```java
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "like" "LIKE"
    at line 2, column 26.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "LIMIT"
    "ORDER"
    "["
    "^"
    "|"
    <EOF>

 at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31468)
 at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31301)
 at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:903)
 at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:213)
 at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:203)
 at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserMulti(JsqlParserSupport.java:63)
 ... 102 common frames omitted
```

**Comment by manticore-projects** [comment]
Greetings.

Please use a recent version of JSQLParser since 4.6-Snapshot parses your statement without any problems. [You can try it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20CIUQMiAqIAQGICUDyBZGAPTAoA6gCRAVgBMBTABwBcYwBJAaVgHIBSJmAHw5iYEN-2XHmywBuIA)

**Comment by manticore-projects** [comment]
Closed when no further question has been asked.
