### ISSUE TITLE
Parsing DROP MATERIALIZED VIEW is not supported

### ISSUE THREAD

**Issue by zaza** [JSQLParser/JSqlParser#1685]
Parsing statement for dropping a materialized view e.g. "DROP MATERIALIZED VIEW foo" results in an error:

```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MATERIALIZED" "MATERIALIZED"
    at line 1, column 6.

Was expecting one of:

    "INDEX"
    "SCHEMA"
    "SEQUENCE"
    "TABLE"
    "VIEW"
    <S_IDENTIFIER>

	at app//net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31468)
	at app//net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31301)
	at app//net.sf.jsqlparser.parser.CCJSqlParser.Drop(CCJSqlParser.java:16562)
	at app//net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:291)
	at app//net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:153)
	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	... 88 more
```

Parsing "DROP VIEW foo" with "MATERIALIZED" removed, works fine.

**Comment by wumpz** [comment]
This feature is not supported. Do you want to provide a PR?

**Comment by zaza** [comment]
Yes, a PR is up and ready for review.

**Comment by zaza** [comment]
Fixed in https://github.com/JSQLParser/JSqlParser/pull/1711
