### ISSUE TITLE
MySQL "#..." comments style not recognized 

### ISSUE THREAD

**Issue by TearsOfJupiter** [JSQLParser/JSqlParser#1695]
The following MySQL query will produce the following exception:
`#Here's a MySQL comment\nselect 1`

`Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at Scratch.main(scratch_3.java:11)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "#Here" <S_IDENTIFIER>
    at line 1, column 1.`

It would be nice if JSqlParser was able to parse MySQL `#`-style comments.

**Comment by manticore-projects** [comment]
Greetings.

As far as I understand it. the `#` is used as an Operator in other supported SQL Dialects.

Since Comments would be discarded by the parser in any, the best approach will be to mangle your SQL before handing it to the parser and to suppress any of those comments. (e. g. using a `String.replaceAll()`  and a proper Regex).

**Comment by TearsOfJupiter** [comment]
Ah, ok. Thank you!
