### ISSUE TITLE
Redshift notation for SET is not supported

### ISSUE THREAD

**Issue by zaza** [JSQLParser/JSqlParser#1708]
In Redshift the syntax for SET statements is `SET x TO y`,  for [example](https://docs.aws.amazon.com/redshift/latest/dg/super-configurations.html#upper-mixed-case): `SET enable_case_sensitive_identifier to true`

This format is not supported and fails with 
```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "true" "TRUE"
    at line 1, column 41.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:94)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:81)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:67)
	at net.sf.jsqlparser.statement.SetStatementTest.setTo(SetStatementTest.java:76)
...
```

**Comment by wumpz** [comment]
This is not supported. PRs are welcome.

**Comment by manticore-projects** [comment]
Duplicate #1945

**Comment by manticore-projects** [comment]
See solution at #1945
