### ISSUE TITLE
[BUG] JSQLParser 4.5 : RDBMS : failing to parse postgresql query "on conflict"

### ISSUE THREAD

**Issue by ashishkrgupta** [JSQLParser/JSqlParser#1729]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### SQL Example:
insert into table ( col1, col2, updationtime, username, lastname ) values ( ?, ?, ?, ?, ? )  ON CONFLICT (  col1, col2 ) DO UPDATE SET username=EXCLUDED.username RETURNING id

It throws below error:
`could not parse query 'insert into userinfo ( col1, col2, updationtime, username, lastname ) values ( ?, ?, ?, ?, ? ) ON CONFLICT ( col1, col2 ) DO UPDATE SET username=EXCLUDED.username RETURNING id'
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
at line 1, column 116.

Was expecting:

")"

at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
at com.securonix.soar.database.cache.JDBCCache.getTableSet(JDBCCache.java:155)
at com.securonix.soar.database.cache.JDBCCache.main(JDBCCache.java:198)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
at line 1, column 116.

Was expecting:

")"

at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
... 4 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
at line 1, column 116.

Was expecting:

")"

at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:33398)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:33231)
at net.sf.jsqlparser.parser.CCJSqlParser.InsertConflictTarget(CCJSqlParser.java:3017)
at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:2967)
at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:252)
at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:157)
at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
[]

### Software Information:
- JSqlParser version
- Database (e. g. Oracle, MS SQL Server, H2, PostgreSQL, IBM DB2 )

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Duplicate #1633

**Comment by manticore-projects** [comment]
Please retry with latest SNAPSHOT from GIT, it should be fixed.
