### ISSUE TITLE
Support for ALTER TABLE ADD FOREIGN KEY syntax

### ISSUE THREAD

**Issue by apalat** [JSQLParser/JSqlParser#174]
Hi,

I'd like to have support for parsing ALTER TABLE ADD FOREIGN KEY constraints.  An example is provided below.

```java
public class IssueExample {
	/**
	 * 
	 * @param args
	 * @throws JSQLParserException
	 */
	public static void main(String[] args) throws JSQLParserException {
		// @formatter:off
		String sql = "ALTER TABLE test " + 
				"ADD FOREIGN KEY (user_id) " + 
				"REFERENCES ra_user (id) " +
				"ON DELETE CASCADE";
		// @formatter:on
		System.out.println(sql);

		Statement statement = CCJSqlParserUtil.parse(sql);
		if (statement instanceof Alter) {
			Alter alter = (Alter) statement;
			System.out.printf("Table %s column %s references table %s column %s.\n", 
					alter.getTable(),
					"alter.getFkColumns()", 
					"alter.sourceTable()", 
					"alter.sourceColumns()");
		}
	}
}
```

Thanks and great project!

**Comment by wumpz** [comment]
Any Exception available? Is this something you could implement? Pull requests are welcome.  Cheers Tobias

**Comment by apalat** [comment]
Hi Tobias,

Here is the exception, I should have added it initially.

```
ALTER TABLE test ADD FOREIGN KEY (user_id) REFERENCES ra_user (id) ON DELETE CASCADE
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.antm.gbd.dm.sql.IssueExample.main(IssueExample.java:30)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "FOREIGN" "FOREIGN "" at line 1, column 22.
Was expecting one of:
    "PRIMARY" ...
    "COLUMN" ...
    "UNIQUE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7303)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "FOREIGN" "FOREIGN "" at line 1, column 22.
Was expecting one of:
    "PRIMARY" ...
    "COLUMN" ...
    "UNIQUE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7303)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at com.antm.gbd.dm.sql.IssueExample.main(IssueExample.java:30)
```

I don't feel that I have the experience with parser generators to implement this myself.  I have basic experience with BNF, I'm working through some tutorials to see if I could.  Its technology on my list to learn but don't have the time to dedicate to it right now.  
Thanks!
Anil

**Comment by bgaborg** [comment]
I've run in to this issue too. Now trying to fix it, however the javacc parser generator feels alien to me.
