### ISSUE TITLE
[BUG] JSQLParser 4.6 : dummy sql : Failed parsing sql containing Korean.

### ISSUE THREAD

**Issue by KyongSik-Yoon** [JSQLParser/JSqlParser#1747]
### Failing SQL Feature:
- SQL can't be parsed. It was no problem until 4.5

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    SELECT 가 FROM 나
    from dual
    ```

### Software Information:
- JSqlParser 4.6
- Just SQL

**Comment by KyongSik-Yoon** [comment]
Please refer following stacktrace.
```
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 8.  Encountered: '44032' (44032),
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	... 71 more
Caused by: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 8.  Encountered: '44032' (44032),
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:6898)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:38711)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_82(CCJSqlParser.java:31391)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_PlainSelect_2016_5_642(CCJSqlParser.java:31400)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_SetOperationList_2111_25_817(CCJSqlParser.java:30776)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_SetOperationList_2111_23_752(CCJSqlParser.java:30784)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_SetOperationList_2110_5_627(CCJSqlParser.java:30921)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_SelectBody_1981_5_348(CCJSqlParser.java:31511)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Select_1972_5_305(CCJSqlParser.java:31517)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_SingleStatement_638_21_122(CCJSqlParser.java:36648)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_3(CCJSqlParser.java:36692)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_3(CCJSqlParser.java:24171)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:362)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:285)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
```

**Comment by manticore-projects** [comment]
Greating,

please try JSQLParser 4.7-Snapshot which has a fix for CJK support.

**Comment by manticore-projects** [comment]
I have added `"\uAC00"-"\uD7A3"` to the CJK block, although I do not understand why this range is not included in the CJK already. It fixes your sample (except that there is a redundant `FROM`).
