### ISSUE TITLE
Alter table add constraint syntax support

### ISSUE THREAD

**Issue by bgaborg** [JSQLParser/JSqlParser#178]
Hello,

I'd like to have support for parsing ALTER TABLE ADD CONSTRAINT support.

The example expression: 
`ALTER TABLE RESOURCELINKTYPE ADD CONSTRAINT FK_RESOURCELINKTYPE_PARENTTYPE_PRIMARYKEY FOREIGN KEY (PARENTTYPE_PRIMARYKEY) REFERENCES RESOURCETYPE (PRIMARYKEY)`

The exception thrown: 

>net.sf.jsqlparser.JSQLParserException
>	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:42)
>	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:51)
>	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:39)
>	at net.sf.jsqlparser.test.alter.AlterTest.testAlterTableForgeignKey(AlterTest.java:36)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
>	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
>	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
>	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
>	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
>Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "CONSTRAINT" "CONSTRAINT "" at line 1, column 35.
>Was expecting one of:
>    "PRIMARY" ...
>    "FOREIGN" ...
>    "COLUMN" ...
>    "UNIQUE" ...
    
>	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
>	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
>	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7643)
>	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
>	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
>	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
>	... 25 more
> Caused by:
> net.sf.jsqlparser.parser.ParseException: Encountered " "CONSTRAINT" "CONSTRAINT "" at line 1, column 35.
> Was expecting one of:
>    "PRIMARY" ...
>    "FOREIGN" ...
>    "COLUMN" ...
>    "UNIQUE" ...
>    
>	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
>	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
>	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7643)
>	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
>	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
>	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
>	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:51)
>	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:39)
>	at net.sf.jsqlparser.test.alter.AlterTest.testAlterTableForgeignKey(AlterTest.java:36)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
>	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
>	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
>	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
>	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

I'd love to fix this issue, but JavaCC syntax is currrently a little alien to me, however I try to learn it from your commits :)

**Comment by apalat** [comment]
There are two additional key words for the ALTER TABLE command in regards to actions.

ON DELETE <b>RESTRICT</b> and
ON DELETE <b>SET NULL</b>.

Gabor, would you be willing to add these to your pull request along with the named constraint fix you've done?

**Comment by apalat** [comment]
One last thought about the alter table for foreign key syntax, its not required to provide the parent table key names in the references section of the statement.  So ALTER table could also read

ALTER TABLE RESOURCELINKTYPE ADD CONSTRAINT FK_RESOURCELINKTYPE_PARENTTYPE_PRIMARYKEY FOREIGN KEY (PARENTTYPE_PRIMARYKEY) REFERENCES RESOURCETYPE ~~(PRIMARYKEY)~~

basically without the parent tables keys explicitly named, the assumption is that the keys in the parent table are named the same as the keys in the child table.

**Comment by bgaborg** [comment]
Ok, I'll add the two addational keywords tomarrow. 
The expression was generated by Eclipselink, without any modification. However, if you think that it is necessary I can modify the expression in the test.

**Comment by wumpz** [comment]
added restrict and set null

**Comment by bgaborg** [comment]
Thanks. Would you merge the pull request too?

**Comment by wumpz** [comment]
I thought you wanted to extend your patch. That's why I waited to look into it.

**Comment by bgaborg** [comment]
I'm not sure how should I extend the patch. When I committed it fixed the issue.

**Comment by wumpz** [comment]
Sorry. Misinterpreted your intention to add some other key words. Nevertheless I merged your patch. Thx for providing. There is room for cleaning up our two solutions. Maybe a merge of both of out patches, to clean up sources? But for now, it works.

**Comment by bgaborg** [comment]
Thanks for merging. I was in a hurry and I thought that you added the solution for @apalat. That was quite a misunderstanding :)

**Comment by apalat** [comment]
I think there may still be an issue with this ticket.  Here are the samples it looks like RESTRICT AND SET NULL are not being recognized correctly.

```java
public class IssueExampleAlterTableForeignKey {
	/**
	 * 
	 * @param args
	 * @throws JSQLParserException
	 */
	public static void main(String[] args) throws JSQLParserException {
		// @formatter:off
		String sql = "ALTER TABLE test " + 
				"ADD FOREIGN KEY (user_id) " + 
				"REFERENCES ra_user (id) " +
				"ON DELETE RESTRICT";
		// @formatter:on
		System.out.println(sql);

		Statement statement = CCJSqlParserUtil.parse(sql);
		if (statement instanceof Alter) {
			Alter alter = (Alter) statement;
			System.out.printf("Table %s column %s references table %s column %s.\n", 
					alter.getTable(),
					alter.getFkColumns(), 
					alter.getFkSourceTable(), 
					alter.getFkSourceColumns());
		}
	}
}
```
Exception was
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "RESTRICT "" at line 1, column 78.
Was expecting:
    "CASCADE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7631)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "RESTRICT "" at line 1, column 78.
Was expecting:
    "CASCADE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7631)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
```
and
```java
public class IssueExampleAlterTableForeignKey1 {
	/**
	 * 
	 * @param args
	 * @throws JSQLParserException
	 */
	public static void main(String[] args) throws JSQLParserException {
		// @formatter:off
		String sql = "ALTER TABLE test " + 
				"ADD FOREIGN KEY (user_id) " + 
				"REFERENCES ra_user (id) " +
				"ON DELETE SET NULL";
		// @formatter:on
		System.out.println(sql);

		Statement statement = CCJSqlParserUtil.parse(sql);
		if (statement instanceof Alter) {
			Alter alter = (Alter) statement;
			System.out.printf("Table %s column %s references table %s column %s.\n", 
					alter.getTable(),
					alter.getFkColumns(), 
					alter.getFkSourceTable(), 
					alter.getFkSourceColumns());
		}
	}
}
```
Exception was
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "SET" "SET "" at line 1, column 78.
Was expecting:
    "CASCADE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7631)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "SET" "SET "" at line 1, column 78.
Was expecting:
    "CASCADE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7631)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
```
As for the previous statement where there was some confusion, there isn't a mandate to explicitly state the foreign keys in the parent table so the following fails:
```java
public class IssueExampleAlterTableForeignKey2 {
	/**
	 * 
	 * @param args
	 * @throws JSQLParserException
	 */
	public static void main(String[] args) throws JSQLParserException {
		// @formatter:off
		String sql = "ALTER TABLE test " + 
				"ADD FOREIGN KEY (user_id) " + 
				"REFERENCES ra_user " +
				"ON DELETE CASCADE";
		// @formatter:on
		System.out.println(sql);

		Statement statement = CCJSqlParserUtil.parse(sql);
		if (statement instanceof Alter) {
			Alter alter = (Alter) statement;
			System.out.printf("Table %s column %s references table %s column %s.\n", 
					alter.getTable(),
					alter.getFkColumns(), 
					alter.getFkSourceTable(), 
					alter.getFkSourceColumns());
		}
	}
}
```
Exception was
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "ON" "ON "" at line 1, column 63.
Was expecting:
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnsNamesList(CCJSqlParser.java:7439)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7625)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "ON" "ON "" at line 1, column 63.
Was expecting:
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13507)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13363)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnsNamesList(CCJSqlParser.java:7439)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alter(CCJSqlParser.java:7625)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:131)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at com.antm.gbd.dm.sql.IssueExampleAlterTableForeignKey.main(IssueExampleAlterTableForeignKey.java:30)
```
Sorry for the long post!

**Comment by bgaborg** [comment]
@apalat This issue was about ALTER TABLE ADD CONSTRAINT support. 
Please explain the relation to ALTER TABLE ADD FOREIGN KEY.

**Comment by wumpz** [comment]
I was not able to deploy JSqlParser in time. The deployed version contains not all of the issue. So maybe cloning and compiling would solve some of it.

**Comment by apalat** [comment]
I think I may have messed us up here, I apologize for that.  Gabor you're right that neither ON DELETE nor the non-explicitly referenced keys apply to your ticket for ADD CONSTRAINT.  I'll re-post to my original ticket.
Tobias, I'm set to the 0.9.5-SNAPSHOT release and tried again today and am getting the same exceptions.  I'll re-post and we can continue this there, would you consider reopening issue 174 or would you prefer I just create a new issue?
