### ISSUE TITLE
[Performance] jsqlparser 4.6 parse process is eminently slow than 4.0 version

### ISSUE THREAD

**Issue by liujin163** [JSQLParser/JSqlParser#1806]
### Grammar or Syntax Description
Statement statement = CCJSqlParserUtil.parse(sql);

```sql
### SQL Example
SELECT  e.id
        , e.code
        , e.review_type
        , e.review_object
        , e.review_first_datetime AS reviewfirsttime
        , e.review_latest_datetime AS reviewnewtime
        , e.risk_event
        , e.risk_detail
        , e.risk_grade
        , e.risk_status
        , If( e.deal_type IS NULL
            OR e.deal_type = '', '--', e.deal_type ) AS dealtype
        , e.deal_result
        , If( e.deal_remark IS NULL
            OR e.deal_remark = '', '--', e.deal_remark ) AS dealremark
        , e.is_deleted
        , e.review_object_id
        , e.archive_id
        , e.feature AS featurename
        , Ifnull( ( SELECT real_name
                    FROM bladex.blade_user
                    WHERE id = e.review_first_user ), ( SELECT DISTINCT
                                                            real_name
                                                        FROM app_sys.asys_uniapp_rn_auth
                                                        WHERE uniapp_user_id = e.review_first_user
                                                            AND is_disable = 0 ) ) AS reviewfirstuser
        , Ifnull( ( SELECT real_name
                    FROM bladex.blade_user
                    WHERE id = e.review_latest_user ), (    SELECT DISTINCT
                                                                real_name
                                                            FROM app_sys.asys_uniapp_rn_auth
                                                            WHERE uniapp_user_id = e.review_latest_user
                                                                AND is_disable = 0 ) ) AS reviewnewuser
        , If( ( SELECT real_name
                FROM bladex.blade_user
                WHERE id = e.deal_user ) IS NOT NULL
            AND e.deal_user != - 9999, (    SELECT real_name
                                            FROM bladex.blade_user
                                            WHERE id = e.deal_user ), '--' ) AS dealuser
        , CASE
                WHEN 'COMPANY'
                    THEN Concat( (  SELECT ar.customer_name
                                    FROM mtp_cs.mtp_rsk_cust_archive ar
                                    WHERE ar.is_deleted = 0
                                        AND ar.id = e.archive_id ), If( (   SELECT alias
                                                                            FROM web_crm.wcrm_customer
                                                                            WHERE id = e.customer_id ) = ''
                OR (    SELECT alias
                        FROM web_crm.wcrm_customer
                        WHERE id = e.customer_id ) IS NULL, ' ', Concat( '（', ( SELECT alias
                                                                                FROM web_crm.wcrm_customer
                                                                                WHERE id = e.customer_id ), '）' ) ) )
                WHEN 'EMPLOYEE'
                    THEN (  SELECT Concat( auth.real_name, ' ', auth.phone )
                            FROM app_sys.asys_uniapp_rn_auth auth
                            WHERE auth.is_disable = 0
                                AND auth.uniapp_user_id = e.uniapp_user_id )
                WHEN 'DEAL'
                    THEN (  SELECT DISTINCT
                                Concat( batch.code, '-', detail.line_seq
                                        , ' ', Ifnull( (    SELECT DISTINCT
                                                                auth.real_name
                                                            FROM app_sys.asys_uniapp_rn_auth auth
                                                            WHERE auth.uniapp_user_id = e.uniapp_user_id
                                                                AND auth.is_disable = 0 ), ' ' ) )
                            FROM web_pym.wpym_payment_batch_detail detail
                                LEFT JOIN web_pym.wpym_payment_batch batch
                                    ON detail.payment_batch_id = batch.id
                            WHERE detail.id = e.review_object_id )
                WHEN 'TASK'
                    THEN (  SELECT code
                            FROM web_tm.wtm_task task
                            WHERE e.review_object_id = task.id )
                ELSE NULL
            END AS reviewobjectname
        , CASE
                WHEN 4
                    THEN 'HIGH_LEVEL'
                WHEN 3
                    THEN 'MEDIUM_LEVEL'
                WHEN 2
                    THEN 'LOW_LEVEL'
                ELSE 'HEALTHY'
            END AS risklevel
FROM mtp_cs.mtp_rsk_event e
WHERE e.is_deleted = 0
ORDER BY e.review_latest_datetime DESC
LIMIT 30
;
```

### Additional context
JSQLParser 4.6 need 5 seconds , JSQLParser 4.6 need 200ms
mysql 8.0

**Comment by manticore-projects** [comment]
Greetings.

You can set the TIMEOUT to less than 6 seconds (default) in order to let the first parse attempt fail faster.
I also would like to suggest to switch to JSQLParser 4.7 Snapshot which has seen improvements in this regards.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsFMB0BLAJgKHt7AaRSAxgPZoJY54EBOCAbiggO4D6ALgJ4AO5lVytBsxbEARgCsEhNhT74B9RqwBmKagGc2LNAEM2CNigC2CWAEFgsQUtUa2hk7Mryk14QBs9CTdq8PTFlaKzAB2zP5OOC7UKOoA1iz0CCEyfPDRsQlkbDoo7pH8rpksAObUOmQF6TTFmnoArupVsPgAksoAFARkOu7s3KatlgByAKpgYM04APIASt0Ivf08sAC8sADkG-gbALS72wtLnCsAlOaWPe4nvGkuVyy06vXXzW2dR320RjrUcbBDWBjCZTbBzT6PBA-P5rTaHPYHe6LL5Q37-c6BK7fNFvAixbQIdwGBCYNItGjBVhiSTSFjoXHIX6EAAWKDoCDppLuBGUizY9VoF1gvIatBCOkcZPeIRe7i6XVAEBgQSW4slZI18AAYrNpgBZWCiTxkAAeSCNFQ5jQQ1FBmoA6gAJECzECwdCwhRCFRqHzW6iwU74BXgKBwAAiQ2grWGMDtmoTiaT2Foqolt2TmazGp1+tgOi4XBY6g46iQOhL6hY9RCKALReoIRYOnqbGZ8eznY1TpdbprdcL1fUNs5ntclJYtj9w9tXbn87Mw3D7qraFiOiNpnWAAZA3vAm4mFP+TPce0Ze45bAQ0q4Km+mqM9ncwaLabzcarae5z3Xe60GOh4sJ4+jTjagbBjgiphrAkbANGsbQB284oWS94sI+yGoahL75oOlblpW1a1vWjxNi2bZYdh86-n2JGDv6o7rF6SjAV4YGztRXGJouy74mu6gbkSsK7ucGKWIeYRMP6Z4fDeMHoZhWa4W+CBmqpQ42lRtH-mODz+nugLDNMcDApMPFLhCBkAITrLssAAJxOQ5kHYNByqKemVHcbAKmfupn6aZxPnJjpHrMUg+kzhBmz7Bs+6XMiMlSrAkAWCA2nOsMmyQPqAAKi4AJobN52DQFlqXECEhB6PK8DuXAvxEI0bDECY1AYV5IVpLhRhsEWhBln1DbxCwhAtc21Asmypi-KVnY6U1-GEsSAE7vNC6WUta0EEyrLsqOQYAnJbmhsqvR1k03XXZmuFMAgohjdQRhIEwhDPWNLVtVpN2-QmYU7cg42aN9HUeuc6xbFR4JdKdt75u4l0bTgd0PU9L1vR9wOte1yPYADY7Y6Dh0AiM4xgDsmz4JAVU1WwXQbIAEP+HPJ52IxWeN-dhqOPe9GN859IO41zIvds6f7hQQRPtYdOyAJD-8ViYGmUgNlGwgHqeVgNMhUgCAJVzuVqvXvVZ1wDT1W1fmrbMuOaYmJThwUbbXDMlVpinJzlC4aRBEVqWxEDg25E29blE+YtNuoKu66biJXtkrxYe2-2pGMZLyCpwxM6HSravhiAZhgAbXZG9lsMNbBUYxnGN0W3TXSiHoLJEKQCA7IisDZLk7hIIjYTFggACOCeZo70qynVcMwXBCG16LXHO3bD5dQv84+-hpaEQHWfB82ofO6Pf2R22SC70FTEEOf6dcmvqFJ0v-Gx8JO4xfFivKz5PMsFwHAY7-Rgf46D-skLQTc2AsgJDkPIXcDA9yPpQCAWo4AAClpgxlgPdR6ADXoAKASAlILBwEskNM3dsItpjZW7nkJAXBgEmEIcQ5kl8mGoFvtRHS1De4Z3HN6EQEgpBaHBnnTY0ALAAGkS6djLibWAlcSCVC-rqA0WD2AYzYIAnI8RYBaLiAgnSLFhDUkEZfXRbDP6ZnAKAIE5N4yq2XAeSkxjpBKW5GlUAIiAAsG0ZEbEdK0AA4o6FgEAABq4ApFJh7NlAAzD4iqGw9QgEjKMPUISQDhOLiIgATPE42Gxtb2nSZkyJiYrFuj8YXMA5Vip2MsgeTIRJ2T5F6v1MaQ02kaASEkFIiAMAGOjgSIk+gdrbgwHMAu8wABChUKR8JAt4LQuh9D+FgiAYAkAMBgFaHqVocAYljIANxAA)

**Comment by manticore-projects** [comment]
Greetings.

[please reduce the timeout](https://manticore-projects.com/JSQLParser/usage.html#define-the-parser-features):

```
// Allow Complex Parsing (which allows nested Expressions, but is much slower)
Statement stmt2 = CCJSqlParserUtil.parse(
        sqlStr
        , parser -> parser
            .withAllowComplexParsing(true)
            .withTimeOut(1000)
);
```

**Comment by liujin163** [comment]
we use the code to set time out 
Statement statement = CCJSqlParserUtil.parse(sql,parser->parser.withAllowComplexParsing(true).withTimeOut(1000));

but the code return exception:
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Time out occurred.
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:275)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:80)
	at com.ysc.JsqlparserTest.main(JsqlparserTest.java:189)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:271)
	... 2 more

**Comment by manticore-projects** [comment]
When this happens, increase Timeout until you it succeeds (but less than 6 seconds).

**Comment by liujin163** [comment]
We know the sql is parsed by "complex parsing" , but we don't understand why 4.0 version is only need 200ms and 4.1 - 4.7 version need 2s ~ 4s . 

We have try the link you send earlier , but java code is really slow than format fuction in the  link you provide   when we used CCJSqlParserUtil.parse java code to parse complex sql

**Comment by manticore-projects** [comment]
Greetings.

With JSQLParser 4.7-Snapshot, the statement takes roughly 2 seconds to parse. You can try the demo code shown below.
Why is it slower than JSQLParser 4.0? Simple answer:

1) your statement uses nested expressions and so can't be parsed in `Simple Mode` (which is fast, but relies on simple parameters for clauses and functions)

2) `Complex Mode` has gotten much more powerful since 4.0 and parses a lot of very complex statements, which 4.0 could not parse. Of course, those additional features come at a cost and the parser has to test many more expressions and branches now, but so gets it right much more often.

A more correct and complete parser is more valuable than a fast parser, since the fastest possible parser would parse nothing and return the failure instantly.

```java
    @Test
    void testComplexParsingOnly() throws Exception {
        String sqlStr = "SELECT  e.id\n" +
                "        , e.code\n" +
                "        , e.review_type\n" +
                "        , e.review_object\n" +
                "        , e.review_first_datetime AS reviewfirsttime\n" +
                "        , e.review_latest_datetime AS reviewnewtime\n" +
                "        , e.risk_event\n" +
                "        , e.risk_detail\n" +
                "        , e.risk_grade\n" +
                "        , e.risk_status\n" +
                "        , If( e.deal_type IS NULL\n" +
                "            OR e.deal_type = '', '--', e.deal_type ) AS dealtype\n" +
                "        , e.deal_result\n" +
                "        , If( e.deal_remark IS NULL\n" +
                "            OR e.deal_remark = '', '--', e.deal_remark ) AS dealremark\n" +
                "        , e.is_deleted\n" +
                "        , e.review_object_id\n" +
                "        , e.archive_id\n" +
                "        , e.feature AS featurename\n" +
                "        , Ifnull( ( SELECT real_name\n" +
                "                    FROM bladex.blade_user\n" +
                "                    WHERE id = e.review_first_user ), ( SELECT DISTINCT\n" +
                "                                                            real_name\n" +
                "                                                        FROM app_sys.asys_uniapp_rn_auth\n" +
                "                                                        WHERE uniapp_user_id = e.review_first_user\n" +
                "                                                            AND is_disable = 0 ) ) AS reviewfirstuser\n" +
                "        , Ifnull( ( SELECT real_name\n" +
                "                    FROM bladex.blade_user\n" +
                "                    WHERE id = e.review_latest_user ), (    SELECT DISTINCT\n" +
                "                                                                real_name\n" +
                "                                                            FROM app_sys.asys_uniapp_rn_auth\n" +
                "                                                            WHERE uniapp_user_id = e.review_latest_user\n" +
                "                                                                AND is_disable = 0 ) ) AS reviewnewuser\n" +
                "        , If( ( SELECT real_name\n" +
                "                FROM bladex.blade_user\n" +
                "                WHERE id = e.deal_user ) IS NOT NULL\n" +
                "            AND e.deal_user != - 9999, (    SELECT real_name\n" +
                "                                            FROM bladex.blade_user\n" +
                "                                            WHERE id = e.deal_user ), '--' ) AS dealuser\n" +
                "        , CASE\n" +
                "                WHEN 'COMPANY'\n" +
                "                    THEN Concat( (  SELECT ar.customer_name\n" +
                "                                    FROM mtp_cs.mtp_rsk_cust_archive ar\n" +
                "                                    WHERE ar.is_deleted = 0\n" +
                "                                        AND ar.id = e.archive_id ), If( (   SELECT alias\n" +
                "                                                                            FROM web_crm.wcrm_customer\n" +
                "                                                                            WHERE id = e.customer_id ) = ''\n" +
                "                OR (    SELECT alias\n" +
                "                        FROM web_crm.wcrm_customer\n" +
                "                        WHERE id = e.customer_id ) IS NULL, ' ', Concat( '（', ( SELECT alias\n" +
                "                                                                                FROM web_crm.wcrm_customer\n" +
                "                                                                                WHERE id = e.customer_id ), '）' ) ) )\n" +
                "                WHEN 'EMPLOYEE'\n" +
                "                    THEN (  SELECT Concat( auth.real_name, ' ', auth.phone )\n" +
                "                            FROM app_sys.asys_uniapp_rn_auth auth\n" +
                "                            WHERE auth.is_disable = 0\n" +
                "                                AND auth.uniapp_user_id = e.uniapp_user_id )\n" +
                "                WHEN 'DEAL'\n" +
                "                    THEN (  SELECT DISTINCT\n" +
                "                                Concat( batch.code, '-', detail.line_seq\n" +
                "                                        , ' ', Ifnull( (    SELECT DISTINCT\n" +
                "                                                                auth.real_name\n" +
                "                                                            FROM app_sys.asys_uniapp_rn_auth auth\n" +
                "                                                            WHERE auth.uniapp_user_id = e.uniapp_user_id\n" +
                "                                                                AND auth.is_disable = 0 ), ' ' ) )\n" +
                "                            FROM web_pym.wpym_payment_batch_detail detail\n" +
                "                                LEFT JOIN web_pym.wpym_payment_batch batch\n" +
                "                                    ON detail.payment_batch_id = batch.id\n" +
                "                            WHERE detail.id = e.review_object_id )\n" +
                "                WHEN 'TASK'\n" +
                "                    THEN (  SELECT code\n" +
                "                            FROM web_tm.wtm_task task\n" +
                "                            WHERE e.review_object_id = task.id )\n" +
                "                ELSE NULL\n" +
                "            END AS reviewobjectname\n" +
                "        , CASE\n" +
                "                WHEN 4\n" +
                "                    THEN 'HIGH_LEVEL'\n" +
                "                WHEN 3\n" +
                "                    THEN 'MEDIUM_LEVEL'\n" +
                "                WHEN 2\n" +
                "                    THEN 'LOW_LEVEL'\n" +
                "                ELSE 'HEALTHY'\n" +
                "            END AS risklevel\n" +
                "FROM mtp_cs.mtp_rsk_event e\n" +
                "WHERE e.is_deleted = 0\n" +
                "ORDER BY e.review_latest_datetime DESC\n" +
                "LIMIT 30\n" +
                ";";

        long startMillis = System.currentTimeMillis();
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        final CCJSqlParser parser = new CCJSqlParser(sqlStr)
                .withSquareBracketQuotation(false)
                .withAllowComplexParsing(true)
                .withBackslashEscapeCharacter(false);
        Future<Statements> future = executorService.submit(new Callable<Statements>() {
            @Override
            public Statements call() throws ParseException {
                return parser.Statements();
            }
        });
        try {
            future.get(6000, TimeUnit.MILLISECONDS);
            long endMillis = System.currentTimeMillis();

            System.out.println("Time to parse [ms]: " + (endMillis-startMillis));
        } catch (TimeoutException | InterruptedException ex2) {
            parser.interrupted = true;
            future.cancel(true);
            throw new JSQLParserException("Failed to within reasonable time " , ex2);
        } catch (ExecutionException e) {
            if (e.getCause() instanceof ParseException) {
                ParseException parseException = (ParseException) e.getCause();
                net.sf.jsqlparser.parser.Token token = parseException.currentToken.next;
                throw new JSQLParserException("Failed to parse statement at Token " + token.image);
            }
        } finally {
            executorService.shutdown();
        }
    }
```

**Comment by liujin163** [comment]
thank you very much . the java code you provide is work for us .

The performance of the parser become slow when we add  some brackets around the CASE WHEN sql , and the speed is very fast when we remove the brackets around the CASE WHEN sql  . (Tested using version 4.6)

Is this specially designed for the Parse Engine?

**Comment by manticore-projects** [comment]
Greetings and thank you for the feedback.

Brackets are expensive because any Expression could be inside. Although I will have a look if there was a way to make it faster.

**Comment by liujin163** [comment]
Emm , Thanks for you help .
