### ISSUE TITLE
[BUG] Encountered unexpected token: "ORDER" "ORDER"

### ISSUE THREAD

**Issue by baklpc** [JSQLParser/JSqlParser#1830]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: `WITH ROLLUP` can't be parsed

### SQL Example:
    ```sql
 SELECT  
 xxxx,xxx,xxx,xxx,xxx,version 
  FROM   menu   

 WHERE  del_flag='0'


  ORDER BY sort_order ASC
    ```

### Software Information:
- JSqlParser version 4.6
- Database Mysql

### Tips:
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ORDER" "ORDER"
    at line 8, column 3.

Was expecting:

    <EOF>

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:49)
	... 133 common frames omitted

**Comment by manticore-projects** [comment]
Works fine with JSQLParser 4.7 Snapshot and [you can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsA8kIFD3egNIpaNZ1XwOT2O1OPmwDcBTAJwGcBLAewDsUAxAJQHkAsrAC2dDgFcUAdQASIXiFgATOgBsA+gDM1AQwDmsALywA5AAZTKfrwAiC2ACEAmrCZsGAFw0fVDWACCwJAoANxAA)

I am very sure your statement is also supported with JSQLParser 4.6 but I do assume that it contains 2 empty lines `\n\n` which terminate your statement (not shown in your example).

**Comment by baklpc** [comment]
Thanks
