### ISSUE TITLE
[BUG] JSQLParser 4.6 : mysql : net.sf.jsqlparser.parser.TokenMgrException

### ISSUE THREAD

**Issue by afish177** [JSQLParser/JSqlParser#1851]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 2, column 30.  Encountered: '22996' (22996),
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserGlobal.parse(JsqlParserGlobal.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:48)
	... 159 more
Caused by: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 2, column 30.  Encountered: '22996' (22996),
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:6898)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:38711)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_79(CCJSqlParser.java:32713)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameList_1831_5_331(CCJSqlParser.java:32737)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Table_1933_5_195(CCJSqlParser.java:31643)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_AllTableColumns_2298_6_192(CCJSqlParser.java:30138)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_116(CCJSqlParser.java:30189)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_116(CCJSqlParser.java:25075)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:8594)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:8551)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:7838)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:8107)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:7718)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:7713)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:377)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:285)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

### SQL Example:
SELECTCUSTOS_DECEAD.ID,
CUSTOS_DECEAD.principal_id 某某ID,
CUSTOS_DECEAD.principal_name 某某I名称,
CUSTOS_DECEAD.ENTRY_ID 某某I编号
FROM 
CUSTOS_DECEAD

### Software Information:
- JSqlParser 4.6
- database mysql

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

Works with JSQLParser 4.7 Snapshot, [you can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsGMCuBnALgewLYoPoBMBTBAC0IEN8A6AS3wCh4mmAaRVTHA4syqgBwBONAHYIa-cgBtcdWIBXNQBpGgTtM6jZq3bpseIqQrUho8ZJkjyWQgpWBYFUAPnuo2w2ybVz29qhEWkEBPWXxYQHdbQGdFQDR-QHflegAxACUAeQBZLU5dHgN6AG4gA)

**Comment by manticore-projects** [comment]
New version including the needed improvement just has been released. I am closing this.
