### ISSUE TITLE
CCJSqlParserUtil.parse Encountered " "IF" "if "" at line 1, column 8. net.sf.jsqlparser.parser.ParseException

### ISSUE THREAD

**Issue by skill7899** [JSQLParser/JSqlParser#186]
this is mysqlStr "select if(1>0,'closed','' ) as abc "
net.sf.jsqlparser.JSQLParserException
    at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
    at com.hgsoft.eap.hgcms.util.test.main(test.java:29)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "IF" "if "" at line 1, column 8.
Was expecting one of:
    "ALL" ...
    "TOP" ...
    "DISTINCT" ...
    "SKIP" ...
    "_" ...
    "SKIP" ...
    "ALL" ...
    "DISTINCT" ...
    "TOP" ...
    "_" ...

```
at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:1917)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:1837)
at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1510)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1408)
at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1395)
at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:110)
at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
... 1 more
```

Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "IF" "if "" at line 1, column 8.
Was expecting one of:
    "ALL" ...
    "TOP" ...
    "DISTINCT" ...
    "SKIP" ...
    "_" ...
    "SKIP" ...
    "ALL" ...
    "DISTINCT" ...
    "TOP" ...
    "_" ...

```
at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:1917)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:1837)
at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1510)
at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1408)
at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1395)
at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:110)
at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
at com.hgsoft.eap.hgcms.util.test.main(test.java:29)
```

**Comment by skill7899** [comment]
I  use mysql db

**Comment by wumpz** [comment]
Look at  #100. This is not a simple problem.

**Comment by skill7899** [comment]
thank you very much。I hope that will fix this problem when you have time ^ ^ ! now i also use case ..when  replace if
