### ISSUE TITLE
[BUG] JSQLParser Version : 4.7  RDBMS : PostgreSQL Encountered unexpected token: "select" <K_SELECT>

### ISSUE THREAD

**Issue by qiqingli** [JSQLParser/JSqlParser#1867]
### Failing SQL Feature:
- Brief description of the failing SQL feature
```
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "select" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "WITH"

	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:308) ~[jsqlparser-4.7.jar!/:?]
	... 74 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "select" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:37141) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:36968) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:7501) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:397) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:283) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:304) ~[jsqlparser-4.7.jar!/:?]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:301) ~[jsqlparser-4.7.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
```

### SQL Example:
- Simplified Query Example, focusing on the failing feature
```
select nextval(:seqName) as pkId;
```

### Software Information:
- JSqlParser version: 4.7
- Database :PostgreSQL

**Comment by manticore-projects** [comment]
Greetings.

This works with JSQLParser 4.8 Snapshot (since I have fixed that a few days ago).
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEByBTAHgFwG4EMA2AKWAXAM6ICO8mAtorAJSwCCwsADgNYCWAJgFADcQA)
