### ISSUE TITLE
[BUG] 4.7 : any : create table parsing fails

### ISSUE THREAD

**Issue by rjahn** [JSQLParser/JSqlParser#1870]
Following statement:

```
CREATE TABLE orders 
(
  order_id SERIAL PRIMARY KEY, 
  table_id INTEGER REFERENCES tables(table_id), 
  dish_id INTEGER REFERENCES dishes(dish_id)
);
```

fails with:

```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "tables" "TABLES"
    at line 1, column 79.

    Was expecting one of:

    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:116)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:85)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:62)
	at com.sibvisions.test.TestSqlParser.testParseCreateTable(TestSqlParser.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

Simple test code:

`CCJSqlParserUtil.parse("CREATE TABLE orders (order_id SERIAL PRIMARY KEY, table_id INTEGER REFERENCES tables(table_id), dish_id INTEGER REFERENCES dishes(dish_id));");`

**Comment by manticore-projects** [comment]
Greetings!

Please have a look at the (Syntax diagram](https://manticore-projects.com/JSQLParser/syntax_snapshot.html#createtable).
`CONSTRAINT ... FOREIGN KEY (...)` is missing.

**Comment by rjahn** [comment]
Following statement is working without problems (same syntax):

```
CREATE TABLE table_name_USER_FAVORITES 
(
  column_name_ID DECIMAL(16,0) PRIMARY, 
  column_name_USER_ID DECIMAL(16,0) 
  NULL REFERENCES USERS(ID), 
  column_name_FOOD_ID DECIMAL(16,0) NULL REFERENCES FOOD_TRUCKS(ID)
);
```

The syntax is valid for Postgresql (https://www.postgresql.org/docs/current/sql-createtable.html).

You're right, it's a different syntax than in your documentation, but if it works with above statement, it should also work with all statements?

**Comment by manticore-projects** [comment]
On a second read, I guess its not about the `REFERENCES` which seems to be swallowed as `CreateParameter` (without understanding the constraint).
It rather looks like `INTEGER` is not parsed as [ColDataType](https://manticore-projects.com/JSQLParser/syntax_snapshot.html#coldatatype).

**Comment by rjahn** [comment]
It looks like a problem with the table name: tables

If I use `DECIMAL` instead of `INTEGER`, no difference:

```
CREATE TABLE orders 
(
  order_id DECIMAL(16,0) PRIMARY KEY, 
  table_id DECIMAL(16,0) REFERENCES tables(table_id), 
  dish_id DECIMAL(16,0) REFERENCES dishes(dish_id)
);
```

Same exception message:

`Encountered unexpected token: "tables" "TABLES"`

**Comment by manticore-projects** [comment]
TABLES indeed is a restricted keyword. https://www.manticore-projects.com/JSQLParser/keywords.htmlOn 26 Sept 2023 07:49, rjahn ***@***.***> wrote:
It looks like a problem with the table name: tables
If I use DECIMAL instead of INTEGER, no difference:
CREATE TABLE orders 
(
  order_id DECIMAL(16,0) PRIMARY KEY, 
  table_id DECIMAL(16,0) REFERENCES tables(table_id), 
  dish_id DECIMAL(16,0) REFERENCES dishes(dish_id)
);

Same exception message:
Encountered unexpected token: "tables" "TABLES"

**Comment by rjahn** [comment]
Yes, you're right.

Do you have an option to ignore "some" keywords?

**Comment by manticore-projects** [comment]
> Do you have an option to ignore "some" keywords?

No, but quoting works:
```sql
CREATE TABLE orders
(
  order_id DECIMAL(16,0) PRIMARY KEY,
  table_id DECIMAL(16,0) REFERENCES "TABLES"(table_id),
  dish_id DECIMAL(16,0) REFERENCES dishes(dish_id)
);
```

Also, you can use the Online Formatter to get a prompt understanding what/where its failing:
http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4HsBOATAphgzgFAAUhssmuGA+gJZawAiYwAkgLITLECMAbABoADAEpYABRAcIIAJqwA0mFkCysAC4BDAEYAbHHQbM2nbv2FjwAMTDgAcsDABlDTv35iWvQfojV5LFp8AAtDJhZpM0FRWGtbMAdnWECQnA8U0N9CEQBuIA

**Comment by rjahn** [comment]
Thanks, this could solve my problem.

Useful swing app in browser :)
