### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by rac021** [JSQLParser/JSqlParser#1872]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: (Select) CCJSqlParserUtil.parse( sqlQuery )

### SQL Example:

```sql
SELECT variable, plot, year::INTEGER AS year_filter, valeur, min_depth, max_depth, (regexp_match($$:CatalyticActivity$$,
                 '(.+\\W|\\.)(\\w+)'))[2] AS characteristic FROM efele_data WHERE variable = 'phos' AND year::INTEGER =
                 ANY(ARRAY(SELECT DISTINCT year::INTEGER AS year_filter FROM efele_data WHERE variable = 'phos')) AND plot =
                ANY(ARRAY(SELECT DISTINCT plot AS plot FROM efele_data WHERE variable = 'phos')) AND max_depth = ANY(ARRAY(SELECT DISTINCT 
                max_depth AS max_depth FROM efele_data WHERE variable = 'phos')) AND variable = ANY(ARRAY(SELECT DISTINCT variable 
                AS variable FROM efele_data WHERE variable = 'phos')) 
                AND (regexp_match($$:CatalyticActivity$$, '(.+\\W|\\.)(\\w+)'))[2] = ANY 
                ( ARRAY (  SELECT DISTINCT ( regexp_match($$:CatalyticActivity$$, '(.+\\W|\\.)(\\w+)'))[2] AS characteristic FROM efele_data WHERE variable = 'phos' ) )

```

### Software Information:
- JSqlParser version : 4.6
- Database : PostgreSQL

### Tips:

The query works well in postgres but parsing it in java : 
```java
(Select) CCJSqlParserUtil.parse( sqlQuery )
```
gives me the following error : 

```
Exception occurred in target VM: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 838.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>
    <ST_SEMICOLON>
 
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 838.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at net.sf.jsqlparser.JSQLParserException.<init>(JSQLParserException.java:29)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:74)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at fr.inra.yedgen.splitter.QueryBuilder.addWhereClause(QueryBuilder.java:160)
	at fr.inra.yedgen.splitter.QueryBuilder.buildMagicSqlQuery(QueryBuilder.java:61)
	at fr.inra.yedgen.splitter.MagicNodeManager.applyRootFilters(MagicNodeManager.java:74)
	at fr.inra.yedgen.splitter.ObdaSplitter.cartesianProduct(ObdaSplitter.java:141)
	at fr.inra.yedgen.splitter.ObdaSplitter.split(ObdaSplitter.java:96)
	at fr.inra.yedgen.processor.Processor$1.accept(Processor.java:659)
	at fr.inra.yedgen.processor.Processor$1.accept(Processor.java:528)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
	at java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:133)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at fr.inra.yedgen.processor.Processor.processOnlyCSV(Processor.java:528)
	at fr.inra.yedgen.processor.Processor.process(Processor.java:904)
	at entypoint.Main.main(Main.java:224)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 838.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>
    <ST_SEMICOLON>

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	... 25 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 838.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:38866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:38696)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:306)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)

```

**Comment by manticore-projects** [comment]
Greetings.

It looks like JSQLParser 4.7 [parses your statement without problems.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsDcCGAnAlkgRgGwKYCh4iiAaWAB2wHsAXQ402AT11QC42BJAOWhAHEQAJVgBBYM1YoA+gDM02GrhT0GsMsjwBXFWvhkAtmgB20gCa5yNABaqGhpAA9zlm3eJkAFClwBzXI7k0gZINADG1p4AJFFskKFI2Ew0aGGiYSkIaDRMMWQA5J4AdADUADplAOoAPhVFAJSeFQDuJfX59fUA2gBMALpiEhGoSBnKaADOKWH4AGJCAPIAsrC4srh45gn4lQASwiCIqBg4uLAAvLD55NZUE-l2otwAIpLsXLwCwhdixkyeYhQKCQ-1goAgMFgz04wGgPBg7j0LHePD4ghE4jeMnkimUiPg82Wq3WmzM2z0sD2ByO6CweB+11u91g9RZjxeFGoNB+oj+ANEQJBAPBUDg0Nh8Og+IYlFog05tGlhJWaw2uC2NCQ0qpQkOyFppwZNzu+RZbOIT1eIWcFis1h5fMBwNBIsh4rh3ARFOI1pcdvlvttbgpyuJao1WopOr1xzpZ0ujJNZvq7Ne+pO9MuvNBAudwvAoqhMI9Xu98HTcflFdOSsWKpJ6rJmu1+11NIz8auxuZrJTFo53j8ASCIXCkRicQSSWm6Uy2VyUQKxXKVVqZQaTTKrXanV6AyzjtzQrBBbdxcl0uIg-8gWCoQi0Vi8U109Ss7QWRyeSuy4qNTqjQtG0HTdP08rDMCYzoFMqS1kSqqkuSejRu2lYJt2pq9vgADcQA)

Please try it out and feedback (or close the issue).

**Comment by rac021** [comment]
World fine with 4.7. 

Thanks
