### ISSUE TITLE
[FEATURE] support for clickhouse's key words global

### ISSUE THREAD

**Issue by Hanchers** [JSQLParser/JSqlParser#1883]
### Grammar or Syntax Description
now i use JSqlParser 4.7 on a clickhouse db. and find a problem : global key word not support. 
sql like : 
```
select a.* from  a global join  b on a.name = b.name 
```

and it throws exception : 
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "global" "GLOBAL"
    at line 1, column 40.

Was expecting one of:

    ";"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "PIVOT"
    "START"
    "WINDOW"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:33398)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:33231)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:167)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 common frames omitted
```

can support the global key words ?

**Comment by manticore-projects** [comment]
Greetings,

according to the Grammar of JSQLParser Snapshot 4.8 [it should work](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html#joinerexpression).

[You can try it online here and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECGA6AVAKAGICUDyBZBsA5gDYD2ARvMarLbAFLYCSAcrOTXV9m0gHbwAtgFNYAXnaIBI1AG4gA)

**Comment by Hanchers** [comment]
![image](https://github.com/JSQLParser/JSqlParser/assets/26269682/fb5e05ea-a050-4de3-8bb6-6c6f9dbc8507)
i try but failed.

it should recognize 'global' as a 'grammar word' , but now recognize as a table name.

**Comment by manticore-projects** [comment]
Fair Point!
I will look into this, we will need to exclude `GLOBAL` from the allowed aliases.

Thanks for testing!

**Comment by manticore-projects** [comment]
```sql
SELECT a.*
FROM a test GLOBAL
    JOIN b
        ON a.name = b.name
;
```

This works, so `GLOBAL` is supported but needs to be reserved as a keyword. I will fix this asap.
Also, the formatter needs a correction regarding `GLOBAL`.

**Comment by Hanchers** [comment]
thanks.
and which version plan to support this feature ?
thanks again.

**Comment by manticore-projects** [comment]
The feature `GLOBAL JOIN` is supported already in JSQLParser 4.7 although version 4.8 will receive a correction regarding `GLOBAL` keyword reservation (so it would not be interpreted as an Alias).

**Comment by Hanchers** [comment]
ok

**Comment by manticore-projects** [comment]
Sorry for taking so long.
