### ISSUE TITLE
[FEATURE] add support for MySQL json path operator

### ISSUE THREAD

**Issue by quaff** [JSQLParser/JSqlParser#1912]
```java
    @Test
    void testMySQLPathOperator() throws JSQLParserException {
        // https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-column-path
        String sqlStr =
                "SELECT sentence->\"$.mascot\" FROM facts";
        assertSqlCanBeParsedAndDeparsed(sqlStr, true);

        // https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-inline-path
        sqlStr =
                "SELECT sentence->>\"$.mascot\" FROM facts";
        assertSqlCanBeParsedAndDeparsed(sqlStr, true);
    }
```
Currently error is reported:
```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "->" "->"
    at line 1, column 17.

Was expecting one of:

    "."
    "::"
    "["
    "^"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:116)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:85)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:98)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:85)
```

**Comment by manticore-projects** [comment]
Greetings!

As far as I can see, your quotes are wrong and we expect a String and not a quoted Identifier:
```sql
SELECT sentence->'$.mascot'
FROM facts
;

SELECT sentence->>'$.mascot'
FROM facts
;
```

[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEDOBTAdgFxQY0QWgHwHIASAOgFsBDeDAe1XwCgAxAJQHkBZWAM3I1XnoBuevVAQYCFOmRY8BEhSq0GLDt178hQA)

**Comment by quaff** [comment]
Thanks, It works with single quotes.
