### ISSUE TITLE
UPDATE with LIMIT clause won't parse

### ISSUE THREAD

**Issue by chiastic-security** [JSQLParser/JSqlParser#195]
JSqlParser (0.9.4) won't parse an `UPDATE` with a `LIMIT` clause.

Parsing `UPDATE tab SET blah='val'` works fine; but `UPDATE tab SET blah='val' LIMIT 1` gives:

    net.sf.jsqlparser.parser.ParseException: Encountered " "LIMIT" "limit "" at line 1, column 27.
    Was expecting one of:
        <EOF> 
        "FROM" ...
        "WHERE" ...
        ";" ...
        "," ...
        "||" ...
        "^" ...
        "::" ...
        "::" ...
        "^" ...
        "||" ...
        "::" ...
        "^" ...
        
    at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
    at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:77)
    at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
    at com.mendeley.platform.tablefinder.TableFinder.lambda$0(TableFinder.java:25)

**Comment by chiastic-security** [comment]
Done! I've added a pull request for this.
