### ISSUE TITLE
[BUG] JSQLParser Version : 4.9: not support cilckhouse sql 

### ISSUE THREAD

**Issue by zljaaa** [JSQLParser/JSqlParser#1992]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 59.

Was expecting one of:

    "FROM"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:350)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:123)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:89)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:62)
	at com.lj.sql111.main(sql111.java:15)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 59.

Was expecting one of:

    "FROM"

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:343)
	... 4 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 59.

Was expecting one of:

    "FROM"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:39603)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:39427)
	at net.sf.jsqlparser.parser.CCJSqlParser.ExtractExpression(CCJSqlParser.java:16399)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:13986)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:13799)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:13752)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:13715)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:13668)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:13644)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:13630)
	at net.sf.jsqlparser.parser.CCJSqlParser.SQLCondition(CCJSqlParser.java:12847)
	at net.sf.jsqlparser.parser.CCJSqlParser.Condition(CCJSqlParser.java:12587)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:9491)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:9468)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:8887)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:8205)
	at net.sf.jsqlparser.parser.CCJSqlParser.ParenthesedSelect(CCJSqlParser.java:8314)
	at net.sf.jsqlparser.parser.CCJSqlParser.WithItem(CCJSqlParser.java:9427)
	at net.sf.jsqlparser.parser.CCJSqlParser.WithList(CCJSqlParser.java:9373)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:369)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:296)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:339)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:336)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### SQL Example:
WITH dis_tab AS
(
    SELECT
        database, 
        table, 
        extract(engine_full, '\'(.*?)\'') cluster 
    FROM system.tables WHERE engine = 'Distributed'
)
SELECT 
    database,
    table,
    cluster,
    host_address,
    port
FROM dis_tab, system.clusters WHERE dis_tab.cluster = system.clusters.cluster

### Software Information:
- JSqlParser version 4.9
- Database  clickhouse

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

There are 2 issues with your statement:
- `EXTRACT` is not standard compliant
- the quoting of the regular expression is not ok because you need to quote/escape the 2nd single quote `'`

[This is a corrected version](http://localhost:8080?args=-c%20OoSQKgEgBAJglgZwPoBcCGAjKBBAylACgCgpSzTcBRAGUoGExSY10M0EBTE8n3gGiisANl15iyAygA8UAJzQBjFAEYCUDgDsA5nA0ckAMwCuQoQIDklggDoAVAH4AlJfNRHUBUKMIUHWd14AMQAlAHkAWSgEAE8fDgBba2EOBACeYAhKYMp1bV0OKABeKHMAEUQ5OAwjXxhXRyIqWgYmFkx2UTEBZLTyAU9vX39xAQALAHsfJDQYGFkU1JGoAAdx2RQiEIjYRFRMNIEYuMSBuNlUjKyc+GRWa1OhoqjY3xOvM4R796GiAG4gA)
