### ISSUE TITLE
[BUG] JSQLParser 4.9: pgvector cosine similarity <=> Failing

### ISSUE THREAD

**Issue by lqh19870820** [JSQLParser/JSqlParser#2005]
### Failing SQL Feature:
- Crash in Postgres Vector when evaluating cosine similarity like (embedding <=> '[3,1,2]') due to enclosing parentheses. `<=>` can't be parsed

### SQL Example:
- Using
    ```sql
    Statement statement = CCJSqlParserUtil.parse(vectorSql)
    ```
however, the following crashes:

String vectorSql= "SELECT (embedding <=> '[3,1,2]') AS cosine_similarity FROM items;";

with error message:

Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "<=" <OP_MINORTHANEQUALS>
    at line 1, column 19.

Was expecting one of:

    ")"
    "."
    "::"
    "["
    "^"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:350)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:123)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:89)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:62)
	at cn.xlink.codeless.data.worker.restful.test.SqlTest.parseInsert(SqlTest.java:293)
	at cn.xlink.codeless.data.worker.restful.test.SqlTest.main(SqlTest.java:71)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "<=" <OP_MINORTHANEQUALS>
    at line 1, column 19.

**Comment by caixiaomao** [comment]
Same issue
