### ISSUE TITLE
NullPointerException in Query: "Select 1"

### ISSUE THREAD

**Issue by devender-yadav** [JSQLParser/JSqlParser#204]
I tried:

    Statement statement = CCJSqlParserUtil.parse("SELECT 1");
    Select selectStatement = (Select) statement;
    TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
    List<String> tableList = tablesNamesFinder.getTableList(selectStatement);

It throws NullPointer :

    Exception in thread "main" java.lang.NullPointerException
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:159)
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:132)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:118)
	at net.sf.jsqlparser.statement.select.Select.accept(Select.java:37)
	at net.sf.jsqlparser.util.TablesNamesFinder.getTableList(TablesNamesFinder.java:107)
	at com.dev.App.getTableNamesFromQuery(App.java:31)
	at com.dev.App.main(App.java:49)

There should be a **null check**  in `getFromItem()` method in`TablesNamesFinder` class.

**Note:** I need to parse queries sent be Tableau & I am using JSqlParser for this. I came across this `SELECT 1` query & got NullPointerException. 

-Dev

**Comment by wumpz** [comment]
This was already solved within the actual snapshot. Look at issue #194.

**Comment by devender-yadav** [comment]
@wumpz 

Thanks a lot for quick response.


-Dev

**Comment by devender-yadav** [comment]
@wumpz 

What is the expected date for 0.9.5 version release?

-Dev
