### ISSUE TITLE
[FEATURE] Dropping multiple tables IF EXISTS is not supported

### ISSUE THREAD

**Issue by awei2024** [JSQLParser/JSqlParser#2065]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
-Unable to resolve, sign in DROP statement
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 25.

Was expecting one of:

    "CASCADE"
    "ON"
    "RESTRICT"
    <EOF>
    <ST_SEMICOLON>
    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:352)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:125)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:64)
	at Test.main(Test.java:40)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 25.

Was expecting one of:

    "CASCADE"
    "ON"
    "RESTRICT"
    <EOF>
    <ST_SEMICOLON>
    <S_IDENTIFIER>

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:345)
	... 4 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 25.

Was expecting one of:

    "CASCADE"
    "ON"
    "RESTRICT"
    <EOF>
    <ST_SEMICOLON>
    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:42285)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:42106)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:341)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:341)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:338)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### SQL Example:
- DROP TABLE IF EXISTS `a`,`b`; 

### Software Information:
- 4.9
- MYSQL

### Tips:
Unable to resolve, sign in DROP statement

**Comment by minleejae** [comment]
@manticore-projects The exact reproducer now works on [master `329ee6b6`](https://github.com/JSQLParser/JSqlParser/commit/329ee6b6465aa7e0d6d01e7555422616fb1f4e93):

```sql
DROP TABLE IF EXISTS `a`,`b`;
```

I verified `Drop.isIfExists() == true` and both table names in `Drop.getNames()`. Default parsing and `Dialect.MYSQL` both pass with unsupported-statement fallback disabled. The fields are preserved after reparsing both `toString()` and `StatementDeParser` output. There is also existing regression coverage in `DropTest.testMySqlDropMultipleTables`.

Could you close this issue if there is no remaining failing example on master?

**Comment by manticore-projects** [comment]
Thank you much!
