### ISSUE TITLE
[BUG] JSQLParser 4.9 & 5.0 : SQL parser report unexpected token

### ISSUE THREAD

**Issue by manbaum** [JSQLParser/JSqlParser#2067]
### Failing SQL Feature:
- JSqlParser report unexpected token.

### SQL Example:
```sql
INSERT INTO TASK_DET ( TASK_ID, INNER_ID, JSON_OBJECT ) VALUES ( ?, ?, ? )
```

### Detailed Exception:
```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 41.

Was expecting one of:

    ")"
    "."

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:352)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:125)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:64)
	at util.gathersync.play.PlaySqlParser.playWeirdSql(PlaySqlParser.java:91)
	at util.gathersync.play.PlaySqlParser.main(PlaySqlParser.java:104)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 41.

Was expecting one of:

    ")"
    "."
```
### Software Information:
- JSqlParser 4.9 and 5.0

**Comment by manticore-projects** [comment]
Greetings!

I can't reproduce your challenge, the [query parses fine and you can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OAXAhgZwNYH0AmApqnABQBQcVaWeAlvpdQDRx0B27hATrg01VYArTAHt2uUQCMhhAMYkAlOQBqAQQAyAVQhgycAPysjhuMoDcQA)

**Comment by manticore-projects** [comment]
Closing this as not reproducible and stale. Feel welcome to re-open when you can produce this error with the online version.
