### ISSUE TITLE
[BUG] JSQLParser 4.9 & 5.0 : Oracle : update statement encountered unexpected token

### ISSUE THREAD

**Issue by manbaum** [JSQLParser/JSqlParser#2068]
### Failing SQL Feature:
- update statement encountered unexpected token

### SQL Example:
```sql
UPDATE TASK_BAT B SET B.RESULT0=? B.RESULT1=? WHERE TASK_ID=?
```

### Exception Detail:
```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "B" <S_IDENTIFIER>
    at line 1, column 35.

Was expecting one of:

    "("
    ","
    "::"
    "FROM"
    "LIMIT"
    "ORDER"
    "OUTPUT"
    "RETURN"
    "RETURNING"
    "WHERE"
    "^"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:352)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:125)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:64)
	at util.gathersync.play.PlaySqlParser.playWeirdSql2(PlaySqlParser.java:100)
	at util.gathersync.play.PlaySqlParser.main(PlaySqlParser.java:114)
```

### Software Information:
- JSqlParser 4.9 & 5.0
- Database Oracle

**Comment by manbaum** [comment]
My fault. the UPDATE statement lacks ',' between multiple assignments. This is not a bug.
