### ISSUE TITLE
[BUG] 5.0 4.9 4.2 mysql fulltext and concat error

### ISSUE THREAD

**Issue by nmf2019** [JSQLParser/JSqlParser#2077]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- mysql fulltext and concat error
- match (name) against (concat('*',?,'*') in boolean mode) can't be parsed

### SQL Example:
select match (name) against (concat('*',?,'*') in boolean mode) as full_text from commodity

### Software Information:
- JSqlParser 5.0 4.9 4.3 4.2
- mysql 5.7 

###  code 
Statement parsed = CCJSqlParserUtil.parse("select match (name) against (concat('*',?,'*') in boolean mode) as full_text from commodity", null);
---------
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "concat" <S_IDENTIFIER>
    at line 1, column 30.

Was expecting one of:

    "&"
    ":"
    "?"
    <S_CHAR_LITERAL>
    <S_PARAMETER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:352)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:125)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:91)

**Comment by manticore-projects** [comment]
Greetings!

Nothing of this exotic syntax is supported (or in scope).
You will need to provide or sponsor an implementation to make this happen.
