### ISSUE TITLE
[BUG] JSQLParser Version : BIGQUERY : fails when using BigQuery GAP_FILL function in FROM clause

### ISSUE THREAD

**Issue by hayssams** [JSQLParser/JSqlParser#2120]
The use of the BigQuery GAP_FILL function in SQL code gives a JSqlParser error when running starlake transform command.

### Failing SQL Feature:

```sql
with raw_data as (
    select timestamp('2024-12-01') zetime
    union all 
    select timestamp('2024-12-04')
  )
select zetime from GAP_FILL(
  TABLE raw_data,
  ts_column => 'zetime',
  bucket_width => INTERVAL 4 HOUR
)
```

```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 6, column 28.

Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:45749)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:45570)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:345)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:341)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:338)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Software Information:
- JSqlParser SNAPSHOT version
- BigQuery

**Comment by manticore-projects** [comment]
Thanks for reporting, it is really about the exotic syntax of this function only, relying on a `TABLE` keyword for the first parameter.

I will have to write an extension of JSQLParser for you.

**Comment by hayssams** [comment]
Great thank you 🙏
