### ISSUE TITLE
Can't parse NOT w/o Parenthesis

### ISSUE THREAD

**Issue by pavelber** [JSQLParser/JSqlParser#234]
JSQLParser expects always NOT before parenthesis (), but really it can be used w/o:
`select count(*) from "Persons" where NOT "F_NAME" = 'John';`
 This is tested on my Postgres

**Comment by wumpz** [comment]
Could you provide an exception? I was able to parse your statement without any modification to JSqlParser. Maybe the problem lies somewhere else.

**Comment by pavelber** [comment]
I see that with = it is working, but assuming I have boolean functions or columns - this is not working


```
public class Test1 {
    public static void main(String[] args) throws JSQLParserException {
        String expressions[] = {
                "not a "
        };


        for(String e:expressions){
            Expression expr = CCJSqlParserUtil.parseCondExpression(e);
            System.out.println("expr = " + expr);

            expr.accept(new MyExpressionVisitor(1));
        }
    }
}
```

leads to
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseCondExpression(CCJSqlParserUtil.java:112)
	at Test1.main(Test1.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "NOT" "not "" at line 1, column 1.
Was expecting one of:
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4014)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseCondExpression(CCJSqlParserUtil.java:110)
	... 6 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "NOT" "not "" at line 1, column 1.
Was expecting one of:
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4014)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseCondExpression(CCJSqlParserUtil.java:110)
	at Test1.main(Test1.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

**Comment by wumpz** [comment]
Somehow forgot to close this one. It was solved by another issue.
