### ISSUE TITLE
Null Pointer Exception while extracting named parameters with Update/delete with subselect

### ISSUE THREAD

**Issue by MathivananSekar** [JSQLParser/JSqlParser#252]
UPDATE USER_GRP SET USER_CMNT ='TEST TXT' WHERE USER_ID NOT IN (SELECT USER_ID FROM AUTHOR_GRP WHERE AUTHOR_AGE<30)
I get null pointer exception when trying to get NamedParameters.
I am using the following code
UpdateDeParser deparser = new UpdateDeParser(sqlExpressionVisitor, buffer);
deparser.deParse(update);
sqlExpressionVisitor.getNamedparameters();
sqlExpressionVisitor is a Deparser extending ExpressionDeparser

Logs
Caused by: java.lang.NullPointerException
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:117)
	at net.sf.jsqlparser.util.deparser.ExpressionDeParser.visit(ExpressionDeParser.java:281)
	at net.sf.jsqlparser.statement.select.SubSelect.accept(SubSelect.java:80)
	at net.sf.jsqlparser.util.deparser.ExpressionDeParser.visit(ExpressionDeParser.java:158)
	at net.sf.jsqlparser.expression.operators.relational.InExpression.accept(InExpression.java:91)
	at net.sf.jsqlparser.util.deparser.UpdateDeParser.deParse(UpdateDeParser.java:86)

**Comment by wumpz** [comment]
So where the NPE is thrown?

**Comment by MathivananSekar** [comment]
I have updated the Logs.

**Comment by wumpz** [comment]
I am not sure about your Exception. The source code line numbers do not match. Do you use an older version. 
Nevertheless my guess is, you forgot to initialize the select visitor within you ExpressionDeParser. For this you could use the `contructor `or `setSelectVisitor`. This one is needed / used for parsing subselects within expressions.

**Comment by MathivananSekar** [comment]
Thanks @wumpz It worked.

**Comment by wumpz** [comment]
Glad I could help and thx for using JSqlParser :).
