### ISSUE TITLE
Cannot parse nested function call

### ISSUE THREAD

**Issue by homerhsing** [JSQLParser/JSqlParser#253]
This query cannot be parsed:

```
SELECT (
      replace_regex(replace_regex(replace_regex(get_json_string(a_column, 'value'), '\n', ' '), '\r', ' '), '\\', '\\\\')
      )   
  FROM a_table
  WHERE b_column = 'value'
```

Error message:

```
Exception in thread "main" net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 116.  Encountered: "\\" (92), after : ""
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:2267)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:13862)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_469(CCJSqlParser.java:12275)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_69(CCJSqlParser.java:12757)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_109(CCJSqlParser.java:12793)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_381(CCJSqlParser.java:12825)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_305(CCJSqlParser.java:12866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_242(CCJSqlParser.java:12921)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_130(CCJSqlParser.java:12897)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:12938)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_376(CCJSqlParser.java:11687)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_296(CCJSqlParser.java:11868)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_235(CCJSqlParser.java:11856)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_117(CCJSqlParser.java:11945)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_147(CCJSqlParser.java:12599)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_69(CCJSqlParser.java:12698)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_109(CCJSqlParser.java:12793)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_381(CCJSqlParser.java:12825)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_305(CCJSqlParser.java:12866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_242(CCJSqlParser.java:12921)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_130(CCJSqlParser.java:12897)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_158(CCJSqlParser.java:12369)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_69(CCJSqlParser.java:12720)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_109(CCJSqlParser.java:12793)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_381(CCJSqlParser.java:12825)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_305(CCJSqlParser.java:12866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_242(CCJSqlParser.java:12921)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_130(CCJSqlParser.java:12897)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:12938)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_178(CCJSqlParser.java:10788)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_441(CCJSqlParser.java:10734)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_390(CCJSqlParser.java:10758)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_391(CCJSqlParser.java:10629)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_330(CCJSqlParser.java:10822)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_261(CCJSqlParser.java:11383)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_166(CCJSqlParser.java:11092)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_78(CCJSqlParser.java:11102)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_17(CCJSqlParser.java:11445)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_17(CCJSqlParser.java:8441)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1884)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1876)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:111)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
```

**Comment by wumpz** [comment]
Hmm. The problem seems to be '\\' within the expression. Using other parameters works.

**Comment by wumpz** [comment]
I did not yet provide a compiled jar. So please check it out and test it. It was a problem within the escape character literal parser.
