### ISSUE TITLE
cannot parse SQL on Oracle

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#260]
the following two work fine:
select A from TEST  where (A like ? escape '\')
select A from TEST  where (A like ? escape '\') or (A like ?)

but the following fails to compile:
select A from TEST  where (A like ? escape '\') or (A like ? escape '\')

with exception:
Exception in thread "main" net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 70.  Encountered: "\" (92), after : ""
    at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:2271)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:14134)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_287(CCJSqlParser.java:13833)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_187(CCJSqlParser.java:13888)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_92(CCJSqlParser.java:13914)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_286(CCJSqlParser.java:13867)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_187(CCJSqlParser.java:13884)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_92(CCJSqlParser.java:13914)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_41(CCJSqlParser.java:13933)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_186(CCJSqlParser.java:13941)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_399(CCJSqlParser.java:9712)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_337(CCJSqlParser.java:11440)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_264(CCJSqlParser.java:11590)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_168(CCJSqlParser.java:11216)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_79(CCJSqlParser.java:11226)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_17(CCJSqlParser.java:11633)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_17(CCJSqlParser.java:8596)
    at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1924)

note that for testing I am using a string (escaping the single '\' with an additional '\' )

String test = "select A from TEST  where (A like ? escape '\\') OR (A like ? escape '\\')";

for oracle documentation on Escape with  LIKE https://docs.oracle.com/cd/B12037_01/server.101/b10759/conditions016.htm

**Comment by wumpz** [comment]
This is a problem with character literal scanning. I am not sure how to tackle this. Since JsqlParser should provide \\ escaping and '' escaping there ist a problem. If two such escapes occure. Your character literal here is `'\\') OR (A like ? escape '` and therefore a syntax error arrises. For the first examples that got parsed, the tokenmanager switches back to the other variant of parsing and so the parse process runes fine.

**Comment by donshop11** [comment]
I am not sure I understand why this one fails

select A from TEST where (A like ? escape '\') or (A like ? escape '\')

while this one work fine:

select A from TEST where (A like ? escape '\') or (A like ?)

**Comment by wumpz** [comment]
This is quite a nasty thing. The token parser of JavaCC will try to accept the max length token at a time. The problem for the first sql is, that this one token is `'\') or (A like ? escape '`. This results in a invalid SQL: select A from TEST where (A like ? escape OUR_WRONG_CHARACTER_LITERAL \').

I tried to support both escaping of single quotes using '' or \' but seeing this, it was a step back I think. 

I have no solution at hand for both ways.

**Comment by wumpz** [comment]
I don't know which sql dialect you are using. But maybe a double backslash works for you. Escaping.

**Comment by manticore-projects** [comment]
[Works with 4.1](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECGAoAYgJQPIFlYBcCmAzjogOoASIqIsAFArGAJIDS1A-LAJSKy+zqpa9Jq1gduAbiA+)
