### ISSUE TITLE
NullPointerException in TablesNamesFinder

### ISSUE THREAD

**Issue by mnadeem** [JSQLParser/JSqlParser#295]
import java.util.List;
    import net.sf.jsqlparser.JSQLParserException;
    import net.sf.jsqlparser.parser.CCJSqlParserUtil;
    import net.sf.jsqlparser.statement.Statement;
    import net.sf.jsqlparser.statement.update.Update;
    import net.sf.jsqlparser.util.TablesNamesFinder;

    public class ExtractTables {

	public static void main(String[] args) throws JSQLParserException {
		Statement statement = CCJSqlParserUtil.parse("UPDATE component SET col = 0 WHERE (component_id,ver_num) IN (SELECT component_id,ver_num FROM component_temp)");
		
		Update selectStatement = (Update) statement;
		TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
		List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
		for (String table : tableList) {
			System.out.println(table);
		}
	}
	
    }

Here is the exception

> Exception in thread "main" java.lang.NullPointerException
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:322)
	at net.sf.jsqlparser.expression.operators.relational.InExpression.accept(InExpression.java:91)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:626)
	at net.sf.jsqlparser.statement.update.Update.accept(Update.java:57)
	at net.sf.jsqlparser.util.TablesNamesFinder.getTableList(TablesNamesFinder.java:185)
	at ExtractTables.main(ExtractTables.java:19)

I think we have to Null check for left and right expressions in 

    @Override
    public void visit(InExpression inExpression) {
        inExpression.getLeftExpression().accept(this);
        inExpression.getRightItemsList().accept(this);
    }

**Comment by wumpz** [comment]
snapshot is not yet deployed
