### ISSUE TITLE
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : ""

### ISSUE THREAD

**Issue by hangum** [JSQLParser/JSqlParser#31]
Hi, community.
I ran.
insert into example (num, name, address, tel) 
       values (1, ‘name‘, ’test ‘, ’1234-1234‘) 
## The following error appears.

!MESSAGE Unhandled event loop exception
!STACK 0
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : ""
    at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1771)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:7951)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_110(CCJSqlParser.java:7234)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_57(CCJSqlParser.java:7258)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_90(CCJSqlParser.java:7375)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_181(CCJSqlParser.java:7477)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_89(CCJSqlParser.java:7484)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_180(CCJSqlParser.java:7551)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_86(CCJSqlParser.java:7684)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_83(CCJSqlParser.java:7603)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_36(CCJSqlParser.java:7673)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_36(CCJSqlParser.java:4762)
    at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:2790)
    at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:468)
    at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:146)
    at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
    at com.hangum.tadpole.sql.util.SQLUtil.isStatement(SQLUtil.java:122)
    at com.hangum.tadpole.rdb.core.editors.main.MainEditor.execute(MainEditor.java:1157)
    at com.hangum.tadpole.rdb.core.editors.main.MainEditor.executeCommand(MainEditor.java:975)
    at com.hangum.tadpole.rdb.core.editors.main.function.MainEditorBrowserFunctionService.doExecuteQuery(MainEditorBrowserFunctionService.java:89)
    at com.hangum.tadpole.editor.core.rdb.texteditor.function.EditorBrowserFunctionService.function(EditorBrowserFunctionService.java:53)
    at org.eclipse.swt.internal.browser.browserkit.BrowserOperationHandler$1.run(BrowserOperationHandler.java:83)
    at org.eclipse.rap.rwt.lifecycle.ProcessActionRunner.executeNext(ProcessActionRunner.java:53)
    at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1187)
    at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1172)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1164)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
    at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
    at com.hangum.tadpole.application.Application.createUI(Application.java:40)
    at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:186)
    at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:298)
    at java.lang.Thread.run(Thread.java:724)
    at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:104)
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : "" 
ERROR - LogListener : logging Unhandled event loop exceptionnet.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 19.  Encountered: "\u2018" (8216), after : ""

**Comment by preetbawa** [comment]
i had question about this exception, even though i am calling CCJParserUtils to parse query within try and catch (generic exception) block, my program still exits when this error happens, can we somehow make the parser move on to next query when this is encountered for specific query ?

**Comment by wumpz** [comment]
Look at StatementsTest. There is an example to turn on error recovery. Hope that helps.

**Comment by preetbawa** [comment]
Thanks Tobias

**Comment by preetbawa** [comment]
hi, so i tried setting parser recovery using example in statementtest.java, interestingly sql query that was parsed correctly throws parser exception now - is the parser returned by constructing new CCJSQLParser different from CCJSqlParserUtil .?

**Comment by wumpz** [comment]
I restate my guess: after googling around I found: Unicode Character 'LEFT SINGLE QUOTATION MARK' (U+2018). The used quotation marks are not supported by JSqlParser. This one is parsed successfully: 
`insert into example (num, name, address, tel) values (1, 'name', 'test ', '1234-1234')`
Look at the quotation marks difference.

Maybe you could provide a file containing your sqls, so that all copy paste problems due to githubs markup processing are avoided.

**Comment by preetbawa** [comment]
Hi Tobias two things here
1) somehow ccjsqlparserutil doesn’t choke on create. table query but
creating new CcjSqlpraser with error recovery set to true still exits out,

Isn’t both ways using same parsing technique ?

**Comment by preetbawa** [comment]
Hi Tobias I wa able to catch throwable for lexical error to keep going; one
thing that’s puzzling if you have very complex select with lot of case when
upto maybe 30-40 it seems parser gets stuck ; is there way to timeout Jsql
parser in case it’s tsking too long on query.

**Comment by wumpz** [comment]
A known performance problem is is there for parentheses parsing due to many possible productions. Nevertheless regarding performance there are already a lot of improvements. Give example SQLs in a different issue to start tackling it. Within jsqlparser organisation is already a performance problem detection project.
