### ISSUE TITLE
error has occurred as bellow when i tried to parsing above query .....

### ISSUE THREAD

**Issue by ytechinfo** [JSQLParser/JSqlParser#324]
query  : 
create table  ccc{
 aaa 	varchar(10)
}

error has occured as bellow when i tried to analyze above query , 
so i want you to throw the error "CCJSqlParserTokenManager.getNextToken"

thank you.

net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 19.  Encountered: "\n" (10), after : "{"
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:2267)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:13862)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_14(CCJSqlParser.java:11611)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_14(CCJSqlParser.java:8417)
	at net.sf.jsqlparser.parser.CCJSqlParser.Table(CCJSqlParser.java:1610)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:7210)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:143)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)

**Comment by wumpz** [comment]
Right. JSqlParser does not support curly braces. Use (  )  instead.

**Comment by ytechinfo** [comment]
I know
And try to take my log.
By the way a successful query and error query
Out error in the lower part, trap the log without
Thing was your inquiry.


I wrong English.
Please understand even if there is wrong wrote sentence.

**Comment by wumpz** [comment]
Sorry, I couldnt catch you. I did not understand you.
