### ISSUE TITLE
How to parser select statement contained '@'?

### ISSUE THREAD

**Issue by jisonami** [JSQLParser/JSqlParser#352]
when I try to parser a select statement contained '@', like this "SELECT @rowNO := @rowNo + 1 from (SELECT (@rowNO := 0) from dual) r;", I get a TokenMgrError.

net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 2, column 10.  Encountered: "r" (114), after : "@"
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1750)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:9139)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_294(CCJSqlParser.java:6500)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_235(CCJSqlParser.java:6546)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_150(CCJSqlParser.java:6089)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:6304)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_16(CCJSqlParser.java:6577)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_16(CCJSqlParser.java:5292)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:845)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:837)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:74)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:54)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)

But, I need to parser these select statement, in order to optimize some "select count" statement in my paging component.Help, please!

**Comment by wumpz** [comment]
The problem is not the @. I was able to successfully parse:
`SELECT @rowNO from (SELECT @rowNO from dual) r`

The problem seems to be the expressions:
`@rowNO := @rowNo + 1`

**Comment by jisonami** [comment]
think you! can I parse ":=" as "+" ? when I repalce ":=" as "+", all thing is OK!

**Comment by jisonami** [comment]
Is not support function “if”？
And is not support table alias ”of”？
