### ISSUE TITLE
parse a insert sql failed with a word 'precision'

### ISSUE THREAD

**Issue by kiterunner-t** [JSQLParser/JSqlParser#363]
when i used jsqlparser-0.9.6 to parse the following sql, and I got a exception:

`insert into test(user_id, precision) values (1, '111')`

the exception:
`net.sf.jsqlparser.parser.ParseException: Encountered " "PRECISION" "precision "" at line 1, column 41.
Was expecting one of:
    "DO" ...
    ...
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
	at net.sf.jsqlparser.parser.CCJSqlParser.Column(CCJSqlParser.java:1630)`

and i followed the call stack, and the kind of "precision" is not matched in method "jj_consume_token".

**Comment by wumpz** [comment]
Precision is a keyword. Therefore it has to be added to the allowed keyword list. I will look into it.
