### ISSUE TITLE
"set deferred_name_resolution on" -> Encountered " "ON" "on "" at line 1, column 30.

### ISSUE THREAD

**Issue by pietergent** [JSQLParser/JSqlParser#373]
Hi,

I'm trying to parse a DDL-script from Sybase, which starts with "set deferred_name_resolution on". This gives me the underneath exception.

As I'm new to JSqlParser, the reason of this is unclear:
- does JSqlPArser does not support Sybase?
- does it not support options to be set in the SQL to be parsed?
- ...?

Thanks a lot in advance!

Pedro

```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "ON" "on "" at line 1, column 30.
Was expecting:
    "=" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
	at net.sf.jsqlparser.parser.CCJSqlParser.Set(CCJSqlParser.java:320)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:186)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 5 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "ON" "on "" at line 1, column 30.
Was expecting:
    "=" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
	at net.sf.jsqlparser.parser.CCJSqlParser.Set(CCJSqlParser.java:320)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:186)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
```

**Comment by wumpz** [comment]
At the moment JSqlParser only supports this syntax
set varname = varvalue
JSqlParser isnt limited to one DBMS. In fact it is able to parse many speciaities from different DBMS (Oracle, Postgresql)..

**Comment by pietergent** [comment]
ok thanks for the input!
Is there some kind of hook that can be used to filter this (and potential other) of these statements out and have them ignored?

**Comment by wumpz** [comment]
Unfortunately not. But it should be no problem to extend JSQLPARSER to support it.

**Comment by pietergent** [comment]
I continued testing ,and I noticed that it has similar errors on syntax like 
- "use MyDataBase"
- "IF EXISTS ..."
- "go"
- "BEGIN"
...

**Comment by wumpz** [comment]
At least JSqlParser 4.0 parses this set statement.
