### ISSUE TITLE
subqueries alias

### ISSUE THREAD

**Issue by luc-leonard** [JSQLParser/JSqlParser#395]
Hi,

It seems to be impossible to give a subquery an alias.
eg.

`SELECT * FROM (SELECT 1 AS COL) AS foobar
`
this query gives an error in Jsql 0.9.6:

> net.sf.jsqlparser.parser.ParseException: Encountered " "AS" "AS "" at line 1, column 19.
> Was expecting one of:
>     <EOF> 
>     ";" ...
>     
> 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:90)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
>

**Comment by luc-leonard** [comment]
(it actually works, my bad for not checking enough before opening an issue)
