### ISSUE TITLE
postgresql to_timestamp is failure

### ISSUE THREAD

**Issue by siaron** [JSQLParser/JSqlParser#421]
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "to_timestamp "" at line 1, column 64.
Was expecting one of:
    "NOT" ...
    "(" ...
    "(" ...
    "NOT" ...
    "NOT" ...
    "NOT" ...
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    "NOT" ...
    "NOT" ...
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    "NOT" ...
    "NOT" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:3506) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:3425) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:3381) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:2855) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1534) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1408) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1395) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:110) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67) ~[jsqlparser-0.9.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38) ~[jsqlparser-0.9.4.jar:na]
	... 89 common frames omitted
.

**Comment by wumpz** [comment]
Could you give a complete sql.

**Comment by wumpz** [comment]
no communication
