### ISSUE TITLE
Failed to parse Insert Query

### ISSUE THREAD

**Issue by goti921** [JSQLParser/JSqlParser#424]
Query:
INSERT into merchant_param SET merchantid=?, `key`=?, value=?, isactive=1, addedon=NOW()

Exception Stack Trace:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "SET" "SET "" at line 1, column 28.
Was expecting one of:
    "WITH" ...
    "SELECT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...

       	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16222)
       	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16075)
       	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:996)
       	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:137)
       	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
       	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
       	... 30 common frames omitted
```

Maven Dependency:
```
        <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>1.0</version>
        </dependency>
```

**Comment by wumpz** [comment]
There is another issue regarding **inserts** using the **set** syntax. At the moment **JSqlParser** does not support this.

**Comment by goti921** [comment]
@wumpz 
When can this be expected?

**Comment by AnEmortalKid** [comment]
@goti921 usually when people need something, they fork the code and submit a PR.

**Comment by wumpz** [comment]
unintentionally left open
