### ISSUE TITLE
support for not expression using "!"

### ISSUE THREAD

**Issue by blue4209211** [JSQLParser/JSqlParser#43]
unable to parse following query --

select s1.a,s1.d as d from Sheet1 s1 where !(s1.b != 60)

version - 0.8,0.9 

following is the stacktrace--
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 45.  Encountered: "(" (40), after : "!"
    at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1750)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:8568)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_187(CCJSqlParser.java:5969)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_83(CCJSqlParser.java:5993)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_165(CCJSqlParser.java:6085)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_81(CCJSqlParser.java:6097)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_162(CCJSqlParser.java:6374)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_80(CCJSqlParser.java:6381)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_256(CCJSqlParser.java:6539)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_160(CCJSqlParser.java:6551)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_79(CCJSqlParser.java:6605)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_383(CCJSqlParser.java:6663)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_355(CCJSqlParser.java:6670)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_341(CCJSqlParser.java:7321)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_295(CCJSqlParser.java:5906)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_231(CCJSqlParser.java:6038)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_147(CCJSqlParser.java:5581)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:5787)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_16(CCJSqlParser.java:6060)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_16(CCJSqlParser.java:4818)
    at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:695)
    at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:687)
    at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:74)
    at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:54)
    at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)

**Comment by wumpz** [comment]
Was already solved on commit d4f744c.
