### ISSUE TITLE
Unable to parse valid Snowflake query 

### ISSUE THREAD

**Issue by ghost** [JSQLParser/JSqlParser#465]
Query : select count(*) from temp.abc where length(substring(cost, (position('.' in cost) +1))) > 2;

Above query results in exception while parsing whereas it is a valid query in Snowflake.

Exception trace below : 

net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56) ~[jsqlparser-1.1-SNAPSHOT.jar:na]
[classes/:na]
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 49.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "ORDER" ...
    "ORDER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869) ~[jsqlparser-1.1-SNAPSHOT.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722) ~[jsqlparser-1.1-SNAPSHOT.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91) ~[jsqlparser-1.1-SNAPSHOT.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54) ~[jsqlparser-1.1-SNAPSHOT.jar:na]
	... 3 common frames omitted

**Comment by wumpz** [comment]
My first guess would be the `position('.' in cost) ` construct. JSqlParser does not yet supports this.

**Comment by wumpz** [comment]
Was I right? Do you want to provide a PR?

**Comment by Shivasish** [comment]
Well, I can try if proper guidance if provided :)

**Comment by natzcam** [comment]
If this is MySQL, you can use LOCATION():
https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_position

**Comment by manticore-projects** [comment]
[Works with 4.1](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgKlgSgCgAxAJQHkBZWNAUwFsAHAOgEMAjAYwIHUAJEEiFhgaKAOZoAFlmBI2AZzQAnAJbisHBIoA0sLAAUtKtCoQoMAciYXYa2JsV5YAalgBGfJ6cA+WACYCAG4gA+)
