### ISSUE TITLE
Can not parse query that have "case when" in where clause

### ISSUE THREAD

**Issue by AnLuming160** [JSQLParser/JSqlParser#466]
eg: String statement2 = "select * from user " +"where case when 1=1 then 2=2 end";
parse this sql statement throws parserException:
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.calm.b.common.SqlParserTest.testGetSelect(SqlParserTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "CASE" "case "" at line 1, column 26.
Was expecting one of:
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16395)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16248)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:4695)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:4651)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4622)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:4021)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2455)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2579)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2336)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2328)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:129)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 28 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "CASE" "case "" at line 1, column 26.
Was expecting one of:
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "NOT" ...
    "(" ...
    "(" ...
    "(" ...
    "NOT" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16395)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16248)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:4695)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:4651)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4622)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:4021)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2455)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2579)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2336)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2328)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:129)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at com.calm.b.common.SqlParserTest.testGetSelect(SqlParserTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by wumpz** [comment]
I guess the condition return is not supported.

**Comment by AnLuming160** [comment]
For MySql DB,the original sql statement like this:
SELECT
	i.id tradeItemId,
	i.type type,
	i.sku_uuid setmealId,
	i.unit_name unitName,
	i.property_amount workmanshipAmount,
	s.brand_dish_uuid brandDishUuid,
	s.brand_dish_id brandDishId,
i.quantity goodsSaleCount,
	CASE
WHEN s.dish_code = 'unknown_dish_code' THEN
	'虚拟商品'
ELSE
	s.`name`
END goodsName,
 CASE
WHEN i.type = 2 THEN
	'-'
WHEN s.dish_code = 'unknown_dish_code' THEN
	'虚拟商品'
ELSE
	s.dish_code
END goodsCode,
 
 CASE
WHEN i.type = 1 THEN
	i.actual_amount
ELSE
	i.amount + i.property_amount
END goodsAmount,
 dt.`name` childTypeName,
 dt.id childTypeId,
 CASE
WHEN i.type = 2 THEN
	'配料'
WHEN s.dish_code = 'unknown_dish_code' THEN
	'虚拟类别'
ELSE
	dt.type_code
END childTypeCode,
 dbt.`name` parentTypeName,
 dbt.id parentTypeId,
 CASE
WHEN i.type = 2 THEN
	'配料'
WHEN s.dish_code = 'unknown_dish_code' THEN
	'虚拟类别'
ELSE
	dbt.type_code
END parentTypeCode,

IFNULL((CASE WHEN tp.privilege_type = 1 or tp.privilege_type = 2 THEN tp.privilege_amount END),0) singleGoodsDiscountAmount,
IFNULL((CASE WHEN tp.privilege_type = 18 THEN tp.privilege_amount END),0) giftAmount,
IFNULL((CASE WHEN tp.privilege_type = 11 THEN tp.privilege_amount END),0) memberPrivilegeAmount,
IFNULL((CASE WHEN tp.privilege_type = 4 or tp.privilege_type = 13 THEN tp.privilege_amount END),0) marketingActivitiesAmount,
CASE WHEN t.trade_type in (1,3,4,6) THEN 1 WHEN t.trade_type in (2,5,7) THEN -1 END goodsSaleTimes

FROM
	trade t
JOIN trade_item i ON t.id = i.trade_id
AND t.status_flag = i.status_flag
JOIN dish_shop s ON i.brand_identy = s.brand_identy
AND i.shop_identy = s.shop_identy
AND i.sku_uuid = s.uuid
LEFT JOIN trade_privilege tp ON tp.trade_item_id = i.id
AND tp.trade_id = t.id
AND i.status_flag = tp.status_flag
LEFT JOIN dish_brand_type dt ON s.dish_type_id = dt.id
AND dt.brand_identy = t.brand_identy
LEFT JOIN dish_brand_type dbt ON dbt.id = dt.parent_id
AND dbt.brand_identy = dt.brand_identy
LEFT JOIN trade_item ti ON i.brand_identy = ti.brand_identy
AND ti.shop_identy = i.shop_identy
AND i.parent_uuid = ti.uuid
WHERE
	t.brand_identy = 11476
AND t.shop_identy IN (
810015597,810015598,850015837
)
AND t.biz_date >= '2017-06-15'
AND t.biz_date <= '2017-06-15'
AND t.trade_status IN (4, 5, 11, 12, 10)
AND t.status_flag = 1
AND t.business_type IN (1, 2, 3, 6, 8)
AND i.quantity != 0
AND t.trade_pay_status IN (1, 2, 3, 4, 5, 6, 8)
AND t.trade_type IN (1, 2, 3, 4, 6, 5, 7)
AND t.delivery_type IN (0, 1, 2, 3, 4)
AND (
	i.type IN (1, 3)
	OR (
		i.type = 0
		AND i.parent_uuid IS NULL
	)
	OR (
		i.type = 2
		AND ti.parent_uuid IS NULL
		AND ti.type = 0
	)
)
AND t.recycle_status = 1
AND (
	CASE
	WHEN t.source_child = 32
	AND t.trade_pay_form = 2
	AND t.trade_status IN (1, 2) THEN
		t.trade_pay_status != 1
	ELSE
		1 = 1
	END
)

This statement can be executed and get right results by the mysql5.5 DB.
if delete sub clause "AND (
	CASE
	WHEN t.source_child = 32
	AND t.trade_pay_form = 2
	AND t.trade_status IN (1, 2) THEN
		t.trade_pay_status != 1
	ELSE
		1 = 1
	END
)" at the end of this statement , it can be parsed .
but ,if add the sub clause ,will throws exception .

**Comment by wumpz** [comment]
Same problem here. Then then - part accepts at the moment only simple expressions.

**Comment by CodingFabian** [comment]
I can chip in with another example I encountered today:

```
select count(*) from `orders` where `email` = ? and `created_at` >= ? and `created_at` <= ? and `status` in (?, ?, ?, ?, ?) and CASE `status` WHEN 1 THEN `created_at` >= '2017-01-01 00:00:00' ELSE true END
```

**Comment by AnEmortalKid** [comment]
@wumpz i believe this can be closed now:

![image](https://user-images.githubusercontent.com/3474369/85235444-83945400-b3da-11ea-96e4-c27a493d529b.png)
