### ISSUE TITLE
no support lateral view  grammar

### ISSUE THREAD

**Issue by chenshaoxing** [JSQLParser/JSqlParser#470]
select  lat,lng from gas_station lateral view amap2basegps(-76.1419264,-136.0134856)  p as lat,lng;

Exception：
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.huoyunren.bigdata.platform.service.SqlParseService.main(SqlParseService.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "LATERAL" "lateral "" at line 1, column 34.
Was expecting one of:
    <EOF>

**Comment by AnEmortalKid** [comment]
@chenshaoxing would you have the time to try to support LATERAL? What DB is this for?

**Comment by hk-lrzy** [comment]
i think it's hive with function explode()

**Comment by manticore-projects** [comment]
Duplicate #239
