### ISSUE TITLE
MySql `use` ParseException

### ISSUE THREAD

**Issue by Xcorpio** [JSQLParser/JSqlParser#480]
sql like `use sqlparser; create table test;` will cause a `ParseException`:

```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "USE" "USE "" at line 1, column 1.
Was expecting one of:
    "SET" ...
    "DROP" ...
    "WITH" ...
    "DELETE" ...
    "SELECT" ...
    "INSERT" ...
    "UPDATE" ...
    "UPSERT" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "ALTER" ...
    "EXEC" ...
    "EXECUTE" ...
    "COMMIT" ...
    "MERGE" ...
    "(" ...
    "ALTER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:200)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 47 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "USE" "USE "" at line 1, column 1.
Was expecting one of:
    "SET" ...
    "DROP" ...
    "WITH" ...
    "DELETE" ...
    "SELECT" ...
    "INSERT" ...
    "UPDATE" ...
    "UPSERT" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "ALTER" ...
    "EXEC" ...
    "EXECUTE" ...
    "COMMIT" ...
    "MERGE" ...
    "(" ...
    "ALTER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:200)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
```

**Comment by wumpz** [comment]
**Use** is not supported. It would be nice to add. PRs are wellcome.

**Comment by wumpz** [comment]
integrated
