### ISSUE TITLE
INNER JOIN doesnt seem to like grouping parantheses

### ISSUE THREAD

**Issue by CodingFabian** [JSQLParser/JSqlParser#483]
The following query parses fine:

```
SELECT * FROM table1 INNER JOIN table ON table1.column_name = table2.column_name WHERE table1.column_name=1
```

But this one doesn't:
```
SELECT * FROM table1 INNER JOIN (table) ON (table1.column_name = table2.column_name) WHERE table1.column_name=1
```
Which is however accepted by mysql.

**Comment by CodingFabian** [comment]
Looks like this is the general FROM expression which doesn't seem to like parentheses:

```
SELECT * FROM (tab)
```

fails with the same problem.

**Comment by CodingFabian** [comment]
```
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:3752)
	at net.sf.jsqlparser.parser.CCJSqlParser.JoinerExpression(CCJSqlParser.java:4298)
	at net.sf.jsqlparser.parser.CCJSqlParser.JoinsList(CCJSqlParser.java:4177)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2682)
```

**Comment by CodingFabian** [comment]
this is also valid:
```
select * from ((TABLE_A), (TABLE_b as b));
```
lets see if i manage to teach javacc that nesting ;)

**Comment by wumpz** [comment]
Looked not yet into it. Keep an eye on performance. Regarding this parenthesis processing is very problematic.

**Comment by AnEmortalKid** [comment]
@wumpz i think you fixed this!

![image](https://user-images.githubusercontent.com/3474369/85235468-bc342d80-b3da-11ea-95f2-b6b188cb9b6c.png)
