### ISSUE TITLE
Cannot parse empty string with double quotes

### ISSUE THREAD

**Issue by ianformanek** [JSQLParser/JSqlParser#488]
Parsing query containing empty string quoted in double quotes, e.g.

```SELECT ""```

which is valid for some SQL databases (e.g. MySQL) results in TokenMgrError:

```
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "\"\""
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:3124) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.getToken(CCJSqlParser.java:16764) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.getOracleHint(CCJSqlParser.java:4878) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2597) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54) ~[jsqlparser-1.1.jar:na]
```

Reproducible in 1.0 and 1.1

**Comment by wumpz** [comment]
I think empty string is not allowed there.

**Comment by ianformanek** [comment]
Allowed (provably) in MySql, not allowed in JsqlParser, hence the issue

**Comment by AnEmortalKid** [comment]
What does that do in MySQL?

**Comment by ianformanek** [comment]
https://dev.mysql.com/doc/refman/5.7/en/string-literals.html

**Comment by wumpz** [comment]
Jsqlparser does not support value quotation with double quotes. Like in my sqls doc described, in ansi sql mode only single quotes are allowed. Double quotes are used for identifiers, db object names, but no values.

**Comment by ianformanek** [comment]
Indeed. Supporting all edge cases of all SQL dialects is a challenging undertaking. 

The JSqlparser README states

```
JSqlParser is not limited to one database but provides support for a lot of specials of Oracle, 
SqlServer, MySQL, PostgreSQL ... To name some, it has support for Oracles join syntax using (+), 
PostgreSQLs cast syntax using ::, relational operators like != and so on.
```

which made me think that Jsqlparser is not limited to ANSI SQL standard and thus it might be useful to report issues.

We implemented a workaround for this, so I am happy to leave this as not worth addressing.
