### ISSUE TITLE
Encountered " "RESTRICT" "RESTRICT "" at line 17, column 72

### ISSUE THREAD

**Issue by david919** [JSQLParser/JSqlParser#493]
**Hi, I'm trying to parse a DDL statement from MySQL and that gives me this exception:**

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:155)
	at Parser.main(Parser.java:29)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "RESTRICT" "RESTRICT "" at line 17, column 72.
Was expecting one of:
    "CASCADE" ...
    "NO" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:17026)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16879)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:9030)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:168)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:273)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:153)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "RESTRICT" "RESTRICT "" at line 17, column 72.
Was expecting one of:
    "CASCADE" ...
    "NO" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:17026)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16879)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:9030)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:168)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:273)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:153)
	at Parser.main(Parser.java:29)

**and the statement is:**

CREATE TABLE UniIS.PREDMET
(
IdPredmeta INT NOT NULL,
NazivPredmeta VARCHAR COLLATE utf8_unicode_ci,
ECTS TINYINT UNSIGNED NOT NULL,
NazivFakulteta VARCHAR COLLATE utf8_unicode_ci NOT NULL,
PRIMARY KEY (IdPredmeta,NazivPredmeta),
CONSTRAINT FK_predmet_maticni_fakultet
FOREIGN KEY (NazivFakulteta)
REFERENCES UniIS.FAKULTET (NazivFakulteta) ON DELETE CASCADE ON UPDATE RESTRICT,
CONSTRAINT UNIQUE_NazivP_NazivF
UNIQUE (NazivPredmeta, NazivFakulteta)
);

**Comment by AnEmortalKid** [comment]
Doesn't look like restrict was handled for Update:
https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L3347
https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L2971
https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L2978

Would you have the time/ability to add support for that?

**Comment by dprutean** [comment]
Also statements with ON DELETE <CASCADE,UPDATE,RESTRICT> are failing. An fix would be nice.

ALTER TABLE dbo.StockTaskPartSku ADD CONSTRAINT FK_StockTaskPartSku_PartSku FOREIGN KEY ( PartSkuID ) REFERENCES dbo.PartSku( ID ) ON DELETE restrict ON UPDATE restrict;

**Comment by eolivelli** [comment]
it looks like this issue has been fixed on current master

Looking forward a release soon ! 
We need this stuff for HerdDB 0.22.0 ! We are implementing foreign keys

**Comment by wumpz** [comment]
So you need only a release, right?

**Comment by eolivelli** [comment]
Yes @wumpz 

Thanks in advance

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
