### ISSUE TITLE
parse error when table name include #

### ISSUE THREAD

**Issue by fogboxggc** [JSQLParser/JSqlParser#512]
e.g.   CCJSqlParserUtil.parse("SELECT * FROM #tab1");

Exception in thread "main" net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 15.  Encountered: "#" (35), after : ""
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1750)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:9139)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_74(CCJSqlParser.java:8548)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_250(CCJSqlParser.java:8761)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_159(CCJSqlParser.java:8779)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_298(CCJSqlParser.java:6452)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_235(CCJSqlParser.java:6553)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_150(CCJSqlParser.java:6089)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:6304)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_16(CCJSqlParser.java:6577)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_16(CCJSqlParser.java:5292)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:845)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:837)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:74)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:54)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at Pansoft.JavaTest.App.main(App.java:15)

How I can do for this?

**Comment by wumpz** [comment]
That is right. Identifier names are not yet allowed to include #.

**Comment by fogboxggc** [comment]
thanks.
