### ISSUE TITLE
sqlParser.Statements() falied

### ISSUE THREAD

**Issue by SuperFireFoxy** [JSQLParser/JSqlParser#513]
CREATE TABLE public.pro_process (
	id int4 NOT NULL DEFAULT nextval('pro_process_id_seq'::regclass),
	county_code varchar(6) NOT NULL,
	county_name varchar(50) NOT NULL,
	creator varchar(100) NOT NULL,
	create_time date NOT NULL,
	CONSTRAINT pro_process_pkey PRIMARY KEY (id)
)
WITH (
	OIDS=FALSE
) ;

net.sf.jsqlparser.parser.ParseException: Encountered " "::" ":: "" at line 69, column 55.
Was expecting one of:
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    "=" ...
    "," ...
    ")" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.AList(CCJSqlParser.java:9719)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateParameter(CCJSqlParser.java:9609)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:8713)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:168)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:273)

**Comment by AnEmortalKid** [comment]
What database has this syntax? `::regclass` ? certain things aren't supported. It looks from the parser that this isn't supported.

**Comment by SuperFireFoxy** [comment]
that's postgresql

**Comment by AnEmortalKid** [comment]
Doesn't look like that's supported. What does that do for postgres?

**Comment by manticore-projects** [comment]
Solved via commit https://github.com/JSQLParser/JSqlParser/pull/1778/commits/32ec56114c1fbc4601d563c83071e7fc81963d2f with PR #1778

**Comment by manticore-projects** [comment]
You are most welcome!
Please give PR #1778 a test ride and let me know any obstacles or concerns. I do look forward hearing your feedback.
