### ISSUE TITLE
 Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]

### ISSUE THREAD

**Issue by yidasanqian** [JSQLParser/JSqlParser#525]
```
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
String currentDate = dateFormat.format(new Date());
```

```
expressionList.getExpressions()
                        .add(new TimestampValue(currentDate ));
```

Exception:
```
Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql.Timestamp.valueOf(Timestamp.java:237)
	at net.sf.jsqlparser.expression.TimestampValue.<init>(TimestampValue.java:34)
```

**Comment by wumpz** [comment]
TimestampValue expects the value in simple quotation. 

`new TimestampValue("'" + currentDate + "'");`

Maybe you could provide a PR to correct this and process both (with / without) possibilities.

**Comment by yidasanqian** [comment]
OK, thanks

**Comment by wumpz** [comment]
SimpleNode is one of the classes generated by jjtree. You need to build it using maven. Then the missing classes will be under genereated-sources.
