### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered " "IS" "IS "" at line 1, column 454.

### ISSUE THREAD

**Issue by qianzhiheilv** [JSQLParser/JSqlParser#528]
```
SELECT D.OTC_PLAN_NAME,D.OTC_PLAN_ID,D.OTC_PLAN_CODE,D.COMMENTS,D.EFF_DATE,D.EXP_DATE,D.STATE,D.STATE_DATE 
FROM BIZ_CUST A, PROD B, PROD_PLAN C, OTC_PLAN D
WHERE A.PROD_ID = B.PROD_ID 
AND B.PROD_ID = C.PROD_ID 		  
AND C.PLAN_TYPE = 2 		   
AND C.PLAN_ID = D.OTC_PLAN_ID 		   
AND D.STATE = 1 		   
AND D. EFF_DATE < SYSDATE() 		   
AND (D.EXP_DATE > SYSDATE() || D.EXP_DATE IS NULL)
```

DataBase is mysql
error is 
```
net.sf.jsqlparser.parser.ParseException: Encountered " "IS" "IS "" at line 1, column 454.
Was expecting one of:
    "AND" ...
    "(" ...
    ")" ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "(" ...
    "(" ...
    "::" ...
    "^" ...
    "|" ...
    "&" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "::" ...
    "^" ...
    "|" ...
    "&" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:5055)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:4976)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4947)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:4346)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2691)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)

```

**Comment by wumpz** [comment]
Shouldn't be the double pipe an or?

**Comment by qianzhiheilv** [comment]
it works well in sqlyog for mysql

**Comment by wumpz** [comment]
But what does this mean:

`D.EXP_DATE > SYSDATE() || D.EXP_DATE IS NULL`

**Comment by qianzhiheilv** [comment]
D.EXP_DATE > SYSDATE() || D.EXP_DATE IS NULL means D.EXP_DATE > SYSDATE() OR D.EXP_DATE IS NULL
New version of mysql support ||

**Comment by wumpz** [comment]
JSqlParser will not be able to process this because it collides with string concatenation in oracle or postgresql. Or at least, I dont see, how to implement this without and bigger problems.

**Comment by qianzhiheilv** [comment]
ok,thanks,I have solved this problem by using druid to parse this sql,I use JSqlParser to parse most part of sqls,if it throws expcetion,I will use druid to parse again.

**Comment by wumpz** [comment]
so I close this issue
