### ISSUE TITLE
CCJSqlParserUtil.parse(sql) fail

### ISSUE THREAD

**Issue by darkleave** [JSQLParser/JSqlParser#549]
-----------------------------test: select * from test where 1=1 and case when 1=1 then 1=1 else 1=1 end 
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at com.zxy.product.report.common.util.SqlUtil.removeOrderBy(SqlUtil.java:128)
	at com.zxy.product.report.common.util.SqlUtil.main(SqlUtil.java:111)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "CASE" "case "" at line 1, column 35.

when i add the 'case when' after the where condition,it throw this error..

**Comment by AnEmortalKid** [comment]
@wumpz also resolved:

![image](https://user-images.githubusercontent.com/3474369/85235411-3fa14f00-b3da-11ea-9578-b2d9eab2bf9c.png)
