### ISSUE TITLE
Exception thrown while parsing insert containing \'

### ISSUE THREAD

**Issue by billy1380** [JSQLParser/JSqlParser#558]
``` java
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.willshex.codegen.fromsql.Insert.handle(Insert.java:52)
	at com.willshex.codegen.fromsql.Program.main(Program.java:54)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "Side "" at line 1, column 741132.
Was expecting one of:
    "," ...
    ")" ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:975)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:138)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 2 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "Side "" at line 1, column 741132.
Was expecting one of:
    "," ...
    ")" ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:975)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:138)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at com.willshex.codegen.fromsql.Insert.handle(Insert.java:52)
	at com.willshex.codegen.fromsql.Program.main(Program.java:54)
```

**Comment by wumpz** [comment]
What was the SQL?

**Comment by billy1380** [comment]
Hi,
Thanks for the quick response.
I can get this code to consistently throw the exception.

``` java
JSqlParser parser = new CCJSqlParserManager();
try {
    Statement parsed = parser.parse(new StringReader(
        "INSERT INTO `test` VALUES (20124,10,112,'46','Test S\'',' ',NULL)"));
    parsed.accept(new StatementVisitorAdapter() {
            @Override
            public void visit (net.sf.jsqlparser.statement.insert.Insert insert) {
	         System.out.println(insert.getTable().getName());
            }
        });
} catch (JSQLParserException e) {
	e.printStackTrace();
}
```

**Comment by wumpz** [comment]
That is a poblem, I am not yet able to solve. JSqlParser supports \' and '' for quotation output. The grammar rule for s_char_literal is implemented like : 

< S_CHAR_LITERAL: ("'" ( <ESC> | ~["'", "\\", "\n", "\r"] )* "'") | ("'" ("''" | ~["'"])* "'") >

If you remove the last part ` | ("'" ("''" | ~["'"])* "'") `, you are able to parse your statement.

This problem occures, when multiple quoted literals are included in your statement.

**Comment by mxdan** [comment]
Hi, wumpz! Is it the same problem for parsing expression like:
`replace('123123\\', '\', '\\')`?

I caught this exception:
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 25.  Encountered: "\\" (92), after : ""

                at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:3124)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:16732)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_481(CCJSqlParser.java:13929)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_85(CCJSqlParser.java:14416)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_134(CCJSqlParser.java:14448)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_130(CCJSqlParser.java:14514)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_127(CCJSqlParser.java:14543)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_271(CCJSqlParser.java:14620)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_156(CCJSqlParser.java:14578)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_83(CCJSqlParser.java:14648)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_258(CCJSqlParser.java:14675)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_122(CCJSqlParser.java:14763)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_302(CCJSqlParser.java:12105)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_246(CCJSqlParser.java:12425)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_116(CCJSqlParser.java:12527)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_85(CCJSqlParser.java:14110)
                at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_85(CCJSqlParser.java:10990)
                at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6446)
                at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257)
                at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214)
                at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176)
                at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109)
                at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133)
                at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101)
                at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseExpression(CCJSqlParserUtil.java:98)
                at com.sbt.mgr.codegenerator.SqlParserTest.testParseExpression(SqlParserTest.java:236)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
                at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
                at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
                at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

**Comment by wumpz** [comment]
Unfortunately yes. As  mentioned I don't know how to solve it in a clean way.

**Comment by manticore-projects** [comment]
Please retry with JSQLParser 4.6 and set the `Backslash Escape` feature:

```java
// Allow Back-slash escaping
sqlStr="SELECT ('\\'Clark\\'', 'Kent')";
Statement stmt2 = CCJSqlParserUtil.parse(
        sqlStr
        , parser -> parser
            .withBackslashEscapeCharacter(true)
);
```
