### ISSUE TITLE
Fail parsing Oracle View

### ISSUE THREAD

**Issue by SebTardif** [JSQLParser/JSqlParser#566]
The following view is accepted by Oracle 12g and Eclipse SQL validation.

Fail this View:

```
SELECT "CAMPAIGNID","TARGET_SOURCE","NON_INDV_TYPE","GROUP_SPONSOR","SEGMNTS","COUNTRY_CD","TARGET_STATE","TARGET_CITY","TARGET_ZIP","SIC_CLASS","NAICS_CLASS","GENDER_CD","OCCUPATION","CREDIT_SCORE","MARITAL_STATUS","IMPORT_ID","BIRTH_DT","STATUS"
             FROM (
               SELECT
                 X.CAMPAIGNID,
                 X.FIELDNAME,
                 CASE WHEN Y.VALUE IS NULL THEN 'ALL'
                 ELSE Y.VALUE END AS VALUE
               FROM
            --CREATES A CARTESIAN JOIN TO COMBINE ALL CHARACTERISTICS WITH CAMPAIGN
                 (SELECT
                    CAMPAIGNID,
                    FIELDNAME
                  FROM CAMPAIGN
                    CROSS JOIN (SELECT DISTINCT FIELDNAME
                                FROM FIELDCRITERIA)) X
                 LEFT JOIN
            --RETURNS ALL AVAILABLE CAMPAIGN CHARACTERISTS
                 (
                   SELECT
                     CAMPAIGNID,
                     FIELDNAME,
                     (CASE FIELDNAME
                      WHEN U'BUSINESSTYPE' THEN D.DISPLAYVALUE
                      WHEN U'LEADTARGETSOURCE' THEN E.DISPLAYVALUE
                      ELSE VALUE END) AS VALUE
                   FROM FIELDCRITERIA A, STRINGFIELDCRITERIA_VALUE B
                     LEFT JOIN (SELECT
                                  B.CODE,
                                  B.DISPLAYVALUE,
                                  LOOKUPNAME
                                FROM LOOKUPLIST A, LOOKUPVALUE B
                                WHERE A.ID = B.LOOKUPLIST_ID AND LOOKUPNAME = 'NONINDIVIDUALTYPE') D ON B.VALUE = D.CODE
                     LEFT JOIN (SELECT
                                  B.CODE,
                                  B.DISPLAYVALUE,
                                  LOOKUPNAME
                                FROM LOOKUPLIST A, LOOKUPVALUE B
                                WHERE A.ID = B.LOOKUPLIST_ID AND LOOKUPNAME = 'LEADTARGETSOURCE') E ON B.VALUE = E.CODE
                     ,
                     CAMPAIGN C
                   WHERE A.ID = B.FIELD_CRITERIA_ID
                         AND A.CRITERIA_ID = C.ID
                 ) Y ON X.CAMPAIGNID = Y.CAMPAIGNID AND X.FIELDNAME = Y.FIELDNAME
             )
               PIVOT (MAX(VALUE)
                 FOR FIELDNAME
                 IN
                   ('LEADTARGETSOURCE' AS TARGET_SOURCE, 'BUSINESSTYPE' AS NON_INDV_TYPE, 'GROUPSPONSOR' AS GROUP_SPONSOR, 'SEGMENTS' AS SEGMNTS, 'COUNTRYCD' AS COUNTRY_CD, 'STATEPROVCD' AS TARGET_STATE,
                   'CITY' AS TARGET_CITY, 'POSTALCODE' AS TARGET_ZIP, 'SICCLASSIFICATION' AS SIC_CLASS, 'NAICSCLASSIFICATION' AS NAICS_CLASS, 'GENDERCD' AS GENDER_CD, 'OCCUPATION' AS OCCUPATION, 'CREDITSCORE' AS CREDIT_SCORE,
                   'MARITALSTATUSCD' AS MARITAL_STATUS, 'IMPORTID' AS IMPORT_ID, 'BIRTHDATE' AS BIRTH_DT, 'STATUS' AS STATUS))
```

Error is:

```
net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at com.lmig.hibernate.Helper.extractTableFromQuery(Helper.java:83)
	at com.lmig.hibernate.Helper.getTables(Helper.java:46)
	at com.lmig.ci.lmb.hibernate.NativeSQLParserTest.test(NativeSQLParserTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 22, column 22.
Was expecting one of:
    "NULL" ...
    "CASE" ...
    "INTERVAL" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "*" ...
    "{d" ...
    "{t" ...
    "{ts" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6699)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:3064)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:3192)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:3054)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2667)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:8219)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:3743)
	at net.sf.jsqlparser.parser.CCJSqlParser.JoinerExpression(CCJSqlParser.java:4298)
	at net.sf.jsqlparser.parser.CCJSqlParser.JoinsList(CCJSqlParser.java:4177)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2682)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:8219)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:3743)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2681)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 26 common frames omitted
```

**Comment by wumpz** [comment]
I assume it is something like an UTF-8 prefix for oracle. After removing leading 'U' from this lines

```
WHEN U'BUSINESSTYPE' THEN D.DISPLAYVALUE
WHEN U'LEADTARGETSOURCE' THEN E.DISPLAYVALUE
```

the statement was parsed.
I would consider this a nearly duplicate to #438.
