### ISSUE TITLE
Error on table rename, column rename, add constraints with cascade

### ISSUE THREAD

**Issue by Golg013** [JSQLParser/JSqlParser#571]
Hello, Wumpz!

**I understand that you are busy, so you can just ignore this message.**

I have some issues:

`CREATE TABLE table_qwert
(
    column_1 INT,
    column_2 INT,
    column_3 INT,
    CONSTRAINT table_qwert_db_object_id_fk FOREIGN KEY (column_1) REFERENCES db_object (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ON" "ON"
    at line 8, column 3.

Was expecting one of:

    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16995) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16848) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:9451) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:171) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:250) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	... 97 common frames omitted

##################################################################################

ALTER TABLE attachment CHANGE content test LONGBLOB;

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CHANGE" <S_IDENTIFIER>
    at line 1, column 24.

Was expecting one of:

    "ADD"
    "DROP"
    "MODIFY"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16995) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16848) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:10673) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:10686) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:159) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:250) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	... 97 common frames omitted

##############################################################################

RENAME TABLE `group` TO `member`;

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "RENAME" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

    "("
    ";"
    "ALTER"
    "CALL"
    "COMMIT"
    "DELETE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SELECT"
    "SET"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16995) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16848) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:208) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:250) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152) ~[jsqlparser-1.2-20180105.233414-16.jar:na]
	... 97 common frames omitted`

**Comment by wumpz** [comment]
No message will be ignored!!! :) (only prioritized)

But you are right, other things are more important at this time, you know, coding for food ;).

Nevertheless, are you willing to provide a pull request? I will happily review and integrate it.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
