### ISSUE TITLE
IN clause without parentheses is not working but work in Oracle DB 

### ISSUE THREAD

**Issue by SebTardif** [JSQLParser/JSqlParser#574]
The following works on Oracle 11g:
`update AsyncTaskManager set lastActive = SYS_EXTRACT_UTC(SYSTIMESTAMP) where sessionId in sessionId`

**Comment by SebTardif** [comment]
Error:

`net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at com.lmig.ci.lmb.hibernate.NativeSQLParserTest.testThirdPartyLibrary(NativeSQLParserTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "IN" "in "" at line 1, column 88.
Was expecting one of:
    <EOF> 
    "AND" ...
    "LIMIT" ...
    "ORDER" ...
    "RETURNING" ...
    ";" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 24 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "IN" "in "" at line 1, column 88.
Was expecting one of:
    <EOF> 
    "AND" ...
    "LIMIT" ...
    "ORDER" ...
    "RETURNING" ...
    ";" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at com.lmig.ci.lmb.hibernate.NativeSQLParserTest.testThirdPartyLibrary(NativeSQLParserTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

`

**Comment by anderruiz** [comment]
Not sure if it is the same case but this example also fails

SELECT * FROM TABLE WHERE ID IN 381

**Comment by AnEmortalKid** [comment]
Is that even legal? If im reading the grammar right, the in_clause requires `()`: https://docs.oracle.com/cd/B19306_01/server.102/b14200/conditions013.htm

So the correct syntax would be:

```
update AsyncTaskManager set lastActive = SYS_EXTRACT_UTC(SYSTIMESTAMP) where sessionId in (sessionId)
```

**Comment by SebTardif** [comment]
> Is that even legal? If im reading the grammar right, the in_clause requires `()`: https://docs.oracle.com/cd/B19306_01/server.102/b14200/conditions013.htm

Some or all version of Oracle accept it.

Like other things in software, the caller should follow the interface strictly but the callee should be flexible as possible. JSqlParser should definitely have a mode that can understand the most as possible the SQLs. I can imagine a use case where it's used for strict validation but it not my use case.

**Comment by AnEmortalKid** [comment]
@SebTardif I mostly ask since I usually go off of the grammar when making a contribution. 

> JSqlParser should definitely have a mode that can understand the most as possible the SQLs. 

Yeah definitely we should be as flexible as possible. 

> Some or all version of Oracle accept it.

if you can find the version of oracle that accepts it, that would be nice , cause then I can base things off of their grammar. Im mostly new at all this stuff and I found that just implementing things according to the grammar made it easier (since it has stuff like `(expr)* [foo]` and those translate easily to javacc)

**Comment by SebTardif** [comment]
> if you can find the version of oracle that accepts it, that would be nice 
Using free Online Oracle at: https://livesql.oracle.com/apex/f?p=590:1000

SELECT * FROM v$version;
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.5.0.0.0

SELECT * FROM all_tables where TABLE_NAME in 'DUAL'
// return the row without error;

SELECT * FROM all_tables where TABLE_NAME in 'DUAL', 'xyz'
// fail
