### ISSUE TITLE
Mysql Parser error 

### ISSUE THREAD

**Issue by rmahnovetsky** [JSQLParser/JSqlParser#584]
I get this parser error in mysql
select chequeoute0_.cheque_book_id as cheque_b1_11_, chequeoute0_.cheque_number as cheque_n2_11_, chequeoute0_.created_utc as created_3_11_ from vw_cheque_out chequeoute0_ where (chequeoute0_.cheque_book_id, chequeoute0_.cheque_number)=(76, 1)

`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 179.
Was expecting one of:
    "ALL" ...
    "NOT" ...
    "NULL" ...
    "CASE" ...
    "INTERVAL" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "ALL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NOT" ...
    "ALL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <K_TIME_KEY_EXPR> ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6699)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101)
	at net.sf.jsqlparser.parser.CCJSqlParser.ComparisonItem(CCJSqlParser.java:6043)
	at net.sf.jsqlparser.parser.CCJSqlParser.RegularCondition(CCJSqlParser.java:5166)
	at net.sf.jsqlparser.parser.CCJSqlParser.Condition(CCJSqlParser.java:5077)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:4997)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:4976)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:4947)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:4346)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2691)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 144 more`

**Comment by wumpz** [comment]
(a,b) = (c,d) is not supported. Only a subquery type is recognized.

**Comment by wumpz** [comment]
Do you want to provide a pull request? Or do you want to contribute in any way for this feature?

**Comment by adriil** [comment]
Hi,
I'm interested in providing a pull request for this feature.
Would you know if a name is given to this notation, in order to give new interfaces/classes a decent name ?
Best regards

**Comment by wumpz** [comment]
The main elements are there. Named  I think ValueList.

**Comment by adriil** [comment]
I may be missing something, but ValuesList implements FromItem, I'm not sure this is suitable.

**Comment by adriil** [comment]
I've managed to have a working solution using an ExpressionList as ComparisonItem().
But the issue is that something like this will work : (a,b) = (c, d, e)  or even  a = (b, c).
So I think it should be a new (I guess) kind of BinaryExpression (with ExpressionList as members) in order to check leftExpression and rightExpression sizes.
Does it sound OK to you ?

**Comment by wumpz** [comment]
@adriil Sorry for introducing some kind of confusion. You are right in using ExpressionList. My memory was somehow corrupted ;).

To your question: JSqlParser is a parser and not a sql validator. You are able to construct invalid SQLs due to JSqlParser multi database approach. 

Now:
`(a,b) = (select a,b,c ...) `
is possible.

But I consider that not a problem. 

Nevertheless are you right, that this kind of obvious problem could be processed. But wouldn't be a better place some kind of validation visitor with more than this check? But I would not be surprised if some database verndor would come up with something like (a,b) = (c,d,e) with some kind of special meaning. You know SQL is a jungle :).

**Comment by adriil** [comment]
@wumpz Don't worry :)

I totally agree about keeping apart validation, for all the above reasons.
Then I will keep it simple and provide a PR later this day.
