### ISSUE TITLE
createTable error  Encountered " "CHARACTER" "CHARACTER "" at line 19, column 41.

### ISSUE THREAD

**Issue by wanjinji** [JSQLParser/JSqlParser#587]
### Steps to Reproduce the Problem
sql:
CREATE TABLE `basic`  (
  `basic_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增长id',
  `basic_title` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '标题',
  `basic_description` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '描述',
  `basic_thumbnails` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '缩略图',
  `basic_hit` bigint(22) DEFAULT NULL COMMENT '点击次数',
  `basic_sort` int(11) DEFAULT NULL COMMENT '排序',
  `basic_datetime` datetime DEFAULT NULL COMMENT ' 发布时间',
  `basic_updatetime` datetime DEFAULT NULL COMMENT '更新时间',
  `basic_peopleid` int(22) DEFAULT NULL COMMENT '用户编号',
  `basic_categoryid` int(22) DEFAULT NULL COMMENT '所属分类编号',
  `basic_appid` int(11) NOT NULL COMMENT '应用编号',
  `basic_modelid` int(11) DEFAULT NULL COMMENT '模块编号',
  `basic_comment` int(11) DEFAULT NULL COMMENT '评论次数',
  `basic_collect` int(11) DEFAULT NULL COMMENT '收藏次数',
  `basic_share` int(11) DEFAULT NULL COMMENT '分享次数',
  `basic_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '属性',
  PRIMARY KEY (`basic_id`) 
) ENGINE = InnoDB AUTO_INCREMENT = 220 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '基础表' ROW_FORMAT = Dynamic
 

aused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "CHARACTER" "CHARACTER "" at line 19, column 41.
Was expecting one of:
    <EOF> 
    "ON" ...
    "KEY" ...
    "NOT" ...
    "NULL" ...
    "WITH" ...
    "WHERE" ...
    "USING" ...
    "DELETE" ...
    "UPDATE" ...
    "PRIMARY" ...
    "FOREIGN" ...
    "CONSTRAINT" ...
    "REFERENCES" ...
    "CHECK" ...
    "ROWS" ...
    "COMMIT" ...
    "UNIQUE" ...
    "CASCADE" ...
    <K_TIME_KEY_EXPR> ...
    "TABLESPACE" ...
    "EXCLUDE" ...
    ";" ...
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    "=" ...
    "(" ...
    "+" ...
    "-" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at net.mingsoft.mcode.biz.impl.ProjectModelObjectBizImpl.upload(ProjectModelObjectBizImpl.java:124)
	at net.mingsoft.mcode.action.people.ProjectModelObjectAction.upload(ProjectModelObjectAction.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2463)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2452)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by manticore-projects** [comment]
[Works with JSQL-4.10 Snapshot](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4CMCGBnAlgY1gAoAoWM2TXPAfRwBNzGmmBJAOSiIEYuBKZgYIFsA8pzYBVZMlgQJUEdXagwAWTAdYwEavWaA5ICvAwHkagf1SWAEX2lyAGgrZ81AC45nAGwCmQ8gDUIIMAAEgFEAMwADBH8wQEQwDAgsADKYJzyAGIAHIza0tBwmVnUAOIaYCAQyNTALLAWYBlyyOJSMtq6Gpz6gOAWgBkZ1oz2lE50nlh4AE44AA6uAPYAdswwABqcsZUJFSlpsEU+5HnIBftQ2aXlldW1Wjp63YDzxoAP8YN2DlQuABYArgC2aEWGBw7iwAn8gRCSUIXCi0S0UPiiV26XOOTIx1ORUubAqVRqdQaTSkrWkd06BkAlP6AU1dAH9qbzIw0cNC+bkO5EQLBK7E4hAATHz+Oz2UTmqT2vcurB9IBOh0A34qAQmtAA6mDNgTM+WHmk2cwp53D4wsN9UaYtgkjJHQe0sAScaAeL1VerRhhnJ5XH9vIILAUoCx1EbhaKSWa2uSrfpYIBF5UAwHqAN9NAC+pDo+Th+MzoztdOHdAi9MB9fv9h0DLWDFslBkAL2aABtN44mRjQZp55jMvPQhHr+YKC4WTUHzRKKd1ABSugHYjQBo-oB35VrzOoeHTAHMtQBPVvMdsCoVdz094t90NS-SAASNAHo6gDAlQDePhOp58MDMZiufO2eBvN8xROK9wZACl6g8vNkZSZoP55jGdx7wER8DRfbNt3fS190AQitAHV1X8hgAmd5j+d1Fh1NtNBhSCoKYItYLLbpABHowAu6OVK8nDweZ3C8PAcMECDn0IshiJLfsw0ANlNAHnQ6i-zVNCsC+DBJg9B88KfdiiJgriP26E9AGq5QTULrFxFwbYUIU2Ig+QAVgMmJEW2JJUlRbJchEfIYDOC4ylxa4CWNYkdxDOCDCPQByA0TAAFEBfQCABNWAAGkwFCwg0NbXhiH4DRuVxWAAF5YHYUQLEQWR5EUZRwCtNKBQiBE4jMlFUvsnJMTstLsUcvEbjqTzODS-RAC-1QABD0ACwjwxAEQAHVqAyEQQFUaBKosYK2AgVQWGAYgAG4gA)
