### ISSUE TITLE
parser the postgresql sql:  occur error

### ISSUE THREAD

**Issue by shilang** [JSQLParser/JSqlParser#588]
select
sme_org.id,
sme_org.name,
sme_org.short_name,
case
when sme_ac_user_org.defaulted isnull then 0
else sme_ac_user_org.defaulted
end as defaulted,
sme_org.code
from
org

i use the
private static CCJSqlParserManager parserManager = new CCJSqlParserManager();
statement = parserManager.parse(new StringReader(sql));
then occur error:

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "isnull "" at line 5, column 49.
Was expecting one of:
"AND" ...
"THEN" ...
"AND" ...

at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.WhenThenSearchCondition(CCJSqlParser.java:7729) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.CaseWhenExpression(CCJSqlParser.java:7434) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6295) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:3064) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:3192) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:3054) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2667) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81) ~[jsqlparser-1.1.jar:na]
at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38) ~[jsqlparser-1.1.jar:na]
my JSqlParser version is :

com.github.jsqlparser
jsqlparser
1.1
how to resolve it
thank you

**Comment by shilang** [comment]
select
	sme_org.id,
	sme_org.name,
	sme_org.short_name,
	case
		when sme_ac_user_org.defaulted isnull then 0
		else sme_ac_user_org.defaulted
	end as defaulted,
	sme_org.code
from 
     org

i use the 
private static CCJSqlParserManager parserManager = new CCJSqlParserManager();
statement = parserManager.parse(new StringReader(sql));
then occur error:

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "isnull "" at line 5, column 49.
Was expecting one of:
    "AND" ...
    "THEN" ...
    "AND" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.WhenThenSearchCondition(CCJSqlParser.java:7729) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.CaseWhenExpression(CCJSqlParser.java:7434) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6295) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:3064) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:3192) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:3054) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2667) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2564) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81) ~[jsqlparser-1.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38) ~[jsqlparser-1.1.jar:na]


my JSqlParser version is : 
		<dependency>
			<groupId>com.github.jsqlparser</groupId>
			<artifactId>jsqlparser</artifactId>
			<version>1.1</version>
		</dependency>

how to resolve it 
thank you

**Comment by wumpz** [comment]
Do you think your sql is correct?
Shouldn't you write something like `sme_ac_user_org.defaulted is null`, instead of `isnull` using `is null`?

**Comment by shilang** [comment]
I can sure the sql is correct. this is postgresql support format,
and the sql is anthor person writed

**Comment by wumpz** [comment]
You are right. Never saw this kind of null check. So "isnull" has to be another keyword. This change would affect the *IsNullExpression*. Do you want to provide a pull request?

**Comment by shilang** [comment]
thanks for you help me solved the issue
