### ISSUE TITLE
Key Words within SQL INSERT parse error

### ISSUE THREAD

**Issue by Icecream0211** [JSQLParser/JSqlParser#592]
INSERT INTO T_USER 
  (ID,
   EMAIL_VALIDATE,
   ENABLE,
   PASSWORD
 )
VALUES
  (?,
   ?,
   ?,
   ?);

ERROR:

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at com.houbank.encode.util.EncodeFieldReplaceUtil.searchAndReplace(EncodeFieldReplaceUtil.java:150)
	at com.houbank.encode.ssss.main(ssss.java:74)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "ENABLE" "ENABLE "" at line 1, column 46.
Was expecting one of:
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "OPEN" ...
    "TABLE" ...
    "XML" ...
    "VALUE" ...
    "INSERT" ...

### Specifications

  - Version:1.0++
  - Platform:jdk 1.7
  - Subsystem:

**Comment by Icecream0211** [comment]
Is there any switch to turn it off? I mean that within  Version 0.9.7 it is just working fine,but within Version 1.0+，get an error

**Comment by wumpz** [comment]
That is because enable us a new keyword. We should only need to adapt RegObjName.
