### ISSUE TITLE
Error parsing an Oracle CreateView statement

### ISSUE THREAD

**Issue by marcgise** [JSQLParser/JSqlParser#597]
### Actual Behavior
The structure of a CreateView in Oracle, may contains a "FORCE | NO FORCE" words after the CREATE OR REPLACE words:
CREATE OR REPLACE FORCE VIEW XXX AS...

### Expected Behavior
Take into account this words. They are not mandatory: https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_8004.htm#SQLRF01504

### Steps to Reproduce the Problem
  1. Create a view with this modifier
  2. Try to parse it
  3. An error is thrown:
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "FORCE" "FORCE "" at line 2, column 21.
Was expecting one of:
    "VIEW" ...
    "MATERIALIZED" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateView(CCJSqlParser.java:9395)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:170)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at zzz.snippets.Testing.main(Testing.java:53)

### Specifications

  - Version: 1.1
  - Platform: Linux
  - Subsystem: Unbuntu 16.04

**Comment by marcgise** [comment]
I have no time to provide it, sorry...
Nevertheless, I found a solution for me, because I realize that I can parse only the select body of the view, removing the CREATE VIEW part
So if you consider that this issue should be closed, it's up to you.
Thanks.

**Comment by wumpz** [comment]
No. It's a good extension. But I have no time as well now. Leave it open. Cheers Tobias
