### ISSUE TITLE
Modify column with "NULL" or "NOT NULL" is not getting parsed.

### ISSUE THREAD

**Issue by VaibhavJain** [JSQLParser/JSqlParser#599]
### Actual Behavior
On parsing statement ALTER TABLE <TableName> MODIFY <ColumnName> NOT NULL getting ParseException

`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "NOT" "NOT "" at line 1, column 51.
Was expecting one of:
    "XML" ...
    "INTERVAL" ...
    "CHARACTER" ...
    "BIT" ...
    <K_DATETIMELITERAL> ...
    "DOUBLE" ...
    <DT_ZONE> ...
    <S_IDENTIFIER> ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColDataType(CCJSqlParser.java:9265)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpressionColumnDataType(CCJSqlParser.java:9862)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:10042)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:10279)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:156)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54) `
### Expected Behavior
It should identify "NOT NULL"/"NULL" has been added.
### Steps to Reproduce the Problem

  1.Statement stmt = CCJSqlParserUtil.parse("ALTER TABLE TableName MODIFY ColumnName NOT NULL");

### Specifications

  - Version: 1.1
  - Platform: Java 8 on windows
  - Subsystem:

**Comment by wumpz** [comment]
As far as I know is the modify command not supported (yet). Do you want to provide a PR with an initial start supporting this?

**Comment by yarnping** [comment]
@VaibhavJain what kind of db related to this sql statement?

**Comment by fudianchn** [comment]
Verified on 1.1 (the reported version), 4.8, 5.3 and current master `c86cf6a`:

| statement | 1.1 | 4.8 | 5.3 | master |
|---|---|---|---|---|
| `ALTER TABLE TableName MODIFY ColumnName NOT NULL` | fails | fails | parses | parses |
| `ALTER TABLE TableName MODIFY ColumnName NULL` | fails | fails | parses | parses |

`MODIFY` with a column type (`... MODIFY ColumnName VARCHAR(10) NOT NULL`) parses on all four, the gap was only the bare `NULL` / `NOT NULL` form. Deparser round-trips it: `ALTER TABLE TableName MODIFY ColumnName NOT NULL`. Fixed since 5.3. Can this be closed?
