### ISSUE TITLE
Parser does not like two sequential quotes

### ISSUE THREAD

**Issue by arvidj01** [JSQLParser/JSqlParser#601]
### Actual Behavior
When parsing this statement ...

`UPDATE T SET C = null WHERE C = "";`

this exception is generated ...

```
Caused by: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 34.  Encountered: "\"" (34), after : "\""
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:3388)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:17391)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_57(CCJSqlParser.java:15208)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_119(CCJSqlParser.java:15468)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_209(CCJSqlParser.java:15522)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_117(CCJSqlParser.java:15538)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_50(CCJSqlParser.java:15601)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_50(CCJSqlParser.java:11459)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:5535)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:5516)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:5487)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:4856)
	at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:524)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:137)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
```
### Expected Behavior

MySql accepts the statement therefore I was expecting JSqlParser to accept the statement.

### Steps to Reproduce the Problem

In an IntelliJ scratch window with the appropriate class path

```
import net.sf.jsqlparser.statement.Statement
import net.sf.jsqlparser.parser.CCJSqlParserUtil

Statement stmt = CCJSqlParserUtil.parse("UPDATE T SET C = null WHERE C = \"\";");

```
### Specifications

  - Version: 1.2-SNAPSHOT pulled on April 13th
  - Platform: Mac, Java 8, IntelliJ
  - Subsystem:

**Comment by wumpz** [comment]
Jsqlparser does not support double quotes for string literals, only for object names.

**Comment by wumpz** [comment]
So is it valid to habe a zero length object name? May I close this one?

**Comment by manticore-projects** [comment]
Closed as stale and unclear.
Please retest with JSQLParser 4.6 and re-open if still an issue.
