### ISSUE TITLE
JSQLParserException with sql

### ISSUE THREAD

**Issue by coderstory** [JSQLParser/JSqlParser#603]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version: 1.1
  - Platform: spring maybatis  mysql
  - Subsystem: jdk 1.8

## sql:
<insert id="addEmployee" parameterType="com.xx.xx.entity.user.Employee">
        INSERT INTO user_employee
        (id, sex, jobNum, birthday, workPhoneNum, jobStatus, nation, marriageStatus, politicsStatus, educationDegree,
        graduateInstitutions, graduateTime, idCard, major, tecnicalTitle, postId, postType, isPostDirector, groupId, homeAddr, postCode,
        depositBank, bankAccount, homePhoneNum, tencentNum, remarks, workDescription, workDistriction, workAddr, workStartTime,
        onDutyTime, offDutyTime, proTitle, censusRegister, homeCase, emergencyContactName, emergencyContactPhone, emergencyContactAddr,
        probationaryPeriodSalary, salary, baseSalary, performanceSalary, compensation, nonRegularEmployeeTime, regularEmployeeTime,
        contractStartTime, contractEndTime, dimissionTime, salaryEndTime, firstJobTime, socialSecurityStatus, fundStatus,
        commercialInsuranceStatus, commercialInsurance, isAttendance, attendanceType, attendanceTypeAddr,
        physicalCharacter, statement, bankAddress, deptId,signWay)
        VALUES
        (#{id}, #{sex},
        (SELECT CASE WHEN MAX(CAST(a.jobNum as UNSIGNED INTEGER)) IS NULL THEN '1000' ELSE MAX(CAST(a.jobNum as UNSIGNED INTEGER)) + 1 END FROM user_employee a),
        #{birthday}, #{workPhoneNum}, #{jobStatus}, #{nation}, #{marriageStatus}, #{politicsStatus}, #{educationDegree},
        #{graduateInstitutions}, #{graduateTime}, #{idCard}, #{major}, #{tecnicalTitle}, #{postId}, #{postType}, #{isPostDirector}, #{groupId}, #{homeAddr},
        #{postCode}, #{depositBank}, #{bankAccount}, #{homePhoneNum}, #{tencentNum}, #{remarks}, #{workDescription}, #{workDistriction}, #{workAddr},
        #{workStartTime}, #{onDutyTime}, #{offDutyTime}, #{proTitle}, #{censusRegister}, #{homeCase}, #{emergencyContactName}, #{emergencyContactPhone},
        #{emergencyContactAddr}, #{probationaryPeriodSalary}, #{salary}, #{baseSalary}, #{performanceSalary}, #{compensation}, #{nonRegularEmployeeTime},
        #{regularEmployeeTime}, #{contractStartTime}, #{contractEndTime}, #{dimissionTime}, #{salaryEndTime}, #{firstJobTime}, #{socialSecurityStatus},
        #{fundStatus}, #{commercialInsuranceStatus}, #{commercialInsurance}, #{isAttendance}, #{attendanceType}, #{attendanceTypeAddr}, #{physicalCharacter},
        #{statement}, #{bankAddress}, #{deptId}, #{signWay})
    </insert>

## code:
CCJSqlParserUtil.parse(sql);

## error:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.reflect.UndeclaredThrowableException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:364)
	at com.sun.proxy.$Proxy40.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:236)
	at com.ywkj.dao.DaoSupport.save(DaoSupport.java:27)
	at com.ywsoftware.oa.service.user.EmployeeService.addEmployee(EmployeeService.java:49)
	at com.ywsoftware.oa.controller.user.EmployeeController.addEmployee(EmployeeController.java:30)
	at sun.reflect.GeneratedMethodAccessor504.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.reflect.UndeclaredThrowableException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137)
	at sun.reflect.GeneratedMethodAccessor567.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:354)
	... 54 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy58.prepare(Unknown Source)
	at org.apache.ibatis.executor.ReuseExecutor.prepareStatement(ReuseExecutor.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doUpdate(ReuseExecutor.java:46)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
	... 59 more
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at com.ywsoftware.oa.infrastructure.Mybatis.TenantInterceptor.addWhere(TenantInterceptor.java:76)
	at com.ywsoftware.oa.infrastructure.Mybatis.TenantInterceptor.intercept(TenantInterceptor.java:62)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:57)
	at com.sun.proxy.$Proxy58.prepare(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:46)
	at com.ywkj.plugin.PagePlugin.intercept(PagePlugin.java:98)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:57)
	... 64 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 12, column 30.
Was expecting one of:
    "AND" ...
    "THEN" ...
    "AND" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhenThenSearchCondition(CCJSqlParser.java:7729)
	at net.sf.jsqlparser.parser.CCJSqlParser.CaseWhenExpression(CCJSqlParser.java:7434)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6295)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:3064)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:3192)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:3040)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2667)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2815)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:8219)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6663)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:6257)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:6214)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:6176)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:6109)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:6133)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:6101)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:934)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:138)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 74 more

**Comment by wumpz** [comment]
Looking into http://www.mybatis.org/mybatis-3/sqlmap-xml.html#Parameters, it becomes clear that

#{name} is some kind of string replacement and therefore not part of the resulting SQL

JSqlParser does not know how to handle these. You should replace it with e.g. **"?"**.

**Comment by coderstory** [comment]
## error child sql  
SELECT CASE WHEN MAX(CAST(a.jobNum as UNSIGNED INTEGER)) IS NULL THEN '1000' ELSE MAX(CAST(a.jobNum as UNSIGNED INTEGER)) + 1 END FROM user_employee a

https://blog.coderstory.cn/wp-content/uploads/2018/04/TIM截图20180419112824.png

**Comment by wumpz** [comment]
Is this a second problem? In future please create another issue for this. The problem here is that JsqlParser does not understand this multiword type ("unsigned integer").

I will look into this.
