### ISSUE TITLE
parse mysql ddl error

### ISSUE THREAD

**Issue by cai3178940** [JSQLParser/JSqlParser#624]
There is a ParseException when I use `CCJSqlParserUtil.parseStatements(ddl_sql)`.

ddl_sql is :
```
CREATE TABLE `meta_index_field` (
  `indexId` int(11) NOT NULL COMMENT '索引id',
  `fieldId` int(11) NOT NULL COMMENT '字段id',
  `orderNo` int(11) NOT NULL COMMENT '排序号',
  PRIMARY KEY (`indexId`,`fieldId`),
  KEY `i_meta_index_field_0` (`indexId`) USING BTREE,
  KEY `i_meta_index_field_1` (`fieldId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='meta_index_field';
```

This is the exception:
```
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "USING" "USING"
    at line 6, column 42.

Was expecting one of:

    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:9874)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:171)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:250)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)
```

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
