### ISSUE TITLE
Failed to Parse MySQL DDL

### ISSUE THREAD

**Issue by shanyuxiyun** [JSQLParser/JSqlParser#625]
### Actual Behavior

the sql is as follow:
```
CREATE TABLE IF NOT EXISTS `t_category` (
  `id` varchar(32) COLLATE utf8_bin NOT NULL,
  `name` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '名称',
  `code` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '编码',
  `description` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '介绍',
  `parentId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '父类节点',
  `preset` tinyint(1) NOT NULL COMMENT '是否预置',
  `beId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '分销商Id',
  `beCode` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '分销商编码',
  `targetBeId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '目标分销商Id',
  `targetBeCode` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '目标分销商编码',
  `spu` text COLLATE utf8_bin,
  `createTime` datetime COLLATE utf8_bin DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime COLLATE utf8_bin DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

### Expected Behavior

no error.

### Steps to Reproduce the Problem

```
String sqls = FileUtils.readFileToString(new File("test.sql"));
        Statements stmt = CCJSqlParserUtil.parseStatements(sqls);
```

### Exception
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:111)
	 
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "NOT" "NOT "" at line 1, column 17.
Was expecting one of:
    <EOF> 
    ";" ...
    "(" ...
    ";" ...
    ";" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:9257)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:9130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:143)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:109)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "NOT" "NOT "" at line 1, column 17.
Was expecting one of:
    <EOF> 
    ";" ...
    "(" ...
    ";" ...
    ";" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:9257)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:9130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:143)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:109)
 
Process finished with exit code 1
```

### Specifications

  - Version:0.9
  - Platform:win7
  - Subsystem:

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
