### ISSUE TITLE
Parse   Alter table dsky add column (c1 char(1),c2 char(1))

### ISSUE THREAD

**Issue by dskys** [JSQLParser/JSqlParser#628]
### Steps to Reproduce the Problem
  1.error
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.RelObjectName(CCJSqlParser.java:2324)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpressionColumnDataType(CCJSqlParser.java:10751)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:10948)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:11217)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:159)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 9 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 29.

Was expecting one of:
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by manticore-projects** [comment]
Todo: Add support for `ALTER TABLE ...` with multiple ADD/DROP directives.
Duplicate of #1245
