### ISSUE TITLE
Accessing an array column with index operator

### ISSUE THREAD

**Issue by sunilkumarbm** [JSQLParser/JSqlParser#638]
My table has a column with array if Strings as shown below:

```
+--------------------+
|             PAYLOAD   |
+--------------------+
|[Str11, Str12]           |
|[Str21, Str22]           |
|[Str31, Str32]           |
|[Str41, Str42]           |
+--------------------+
```

And my query is as below:
`SELECT PAYLOAD[0] FROM TABLE;`

This query works fine in spark sql. But when I try to parse the query through jSqlParser, it fails with the following error:

```
net.sf.jsqlparser.JSQLParserException
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "[" "[ "" at line 1, column 15.
Was expecting one of:

   <EOF>

   "INTO" ...

   "FROM" ...

   "WHERE" ...

   "FOR" ...

   "UNION" ...

   "GROUP" ...

   "ORDER" ...

   "HAVING" ...

   "INTERSECT" ...

   "EXCEPT" ...

   "MINUS" ...

   "START" ...

   "CONNECT" ...

   ";" ...

   "," ...

   "ORDER" ...

   "ORDER" ...        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16395)

       at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16248)

       at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:271)

       at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:126)

       ... 12 more

Caused by:

net.sf.jsqlparser.parser.ParseException: Encountered " <S_LONG> "1 "" at line 3, column 21.

Was expecting one of:

   <EOF>

   "INTO" ...

   "FROM" ...

   "WHERE" ...

   "FOR" ...

   "UNION" ...

   "GROUP" ...

   "ORDER" ...

   "HAVING" ...

   "INTERSECT" ...

   "EXCEPT" ...

   "MINUS" ...

   "START" ...

   "CONNECT" ...

   ";" ...

   "," ...

   "ORDER" ...

   "ORDER" ...        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16395)

       at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16248)

       at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:271)

       at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:126)

       at spark.sql.SQLScriptDescriptor.parseSQLScript(SQLScriptDescriptor.java:135)

       at spark.sql.JobExecutor.start(JobExecutor.java:144)

       at razorsight.drivers.SqlDriver.main(SqlDriver.java:152)

       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

       at java.lang.reflect.Method.invoke(Method.java:498)

       at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)

       at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)

       at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)

       at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)

       at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

18/07/09 07:07:20 ERROR XDFException: XDF-SQLScriptNotParsable => Embedded exception details: null

The SQL script is not parsable:

ERROR: Exception: XDF-SQLScriptNotParsable => Embedded exception details: null

The SQL script is not parsable:Exception stack trace:

razorsight.exceptions.XDFException: XDF-SQLScriptNotParsable => Embedded exception details: null

The SQL script is not parsable:

       at spark.sql.SQLScriptDescriptor.parseSQLScript(SQLScriptDescriptor.java:220)

       at spark.sql.JobExecutor.start(JobExecutor.java:144)

       at razorsight.drivers.SqlDriver.main(SqlDriver.java:152)

       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

       at java.lang.reflect.Method.invoke(Method.java:498)

       at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)

       at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)

       at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)

       at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)

       at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Is there a way to make this work?

### Specifications

  - Version: 1.0
  - Platform: Linux
  - Subsystem: java, Spark-sql

**Comment by wumpz** [comment]
The problem is, it collides with SQL server [ ] object name quotation. Therefore it is not possible to implement at the moment.
