### ISSUE TITLE
Request: Support CREATE VIEW with WITH clauses

### ISSUE THREAD

**Issue by rupert654** [JSQLParser/JSqlParser#665]
"CREATE VIEW" and "WITH" clauses are supported independently but not together.

This parses:

```
CREATE VIEW foo ("BAR") AS 
SELECT bar from foobar
```

and this parses:

```
WITH temp AS (SELECT temp_bar FROM foobar)
SELECT bar from foobar
```

but not this:

```
CREATE VIEW foo ("BAR") AS 
WITH temp AS (SELECT temp_bar FROM foobar)
SELECT bar from foobar
```

which fails with error:

```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CREATE" "CREATE"
    at line 1, column 1.

Was expecting one of:

    "("
    "ALTER"
    "CALL"
    "COMMIT"
    "DELETE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SELECT"
    "SET"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:208)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseAST(CCJSqlParserUtil.java:62)
... 99 more
```

**Comment by rupert654** [comment]
Wow that was fast! Thanks so much!

**Comment by wumpz** [comment]
Glad I could help. Nevertheless my time is limited at the moment. You know, coding for food ;).  Thx for using Jsqlparser. Cheers Tobias
null
