### ISSUE TITLE
 DB2 Date and Timestamp specific functions

### ISSUE THREAD

**Issue by anuragknit2003** [JSQLParser/JSqlParser#666]
### Actual Behavior

I am trying to parse below DB2 SQL : DELETE FROM TABLE_DEF WHERE COLUMN1=:COLUMN1 AND COLUMN3 BETWEEN CURRENT TIMESTAMP - 1 DAY AND CURRENT TIMESTAMP

Exception: 

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BETWEEN" "BETWEEN"
    at line 1, column 58.

Was expecting one of:

    "."
    ";"
    "AND"
    "LIMIT"
    "ORDER"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 24 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BETWEEN" "BETWEEN"
    at line 1, column 58.

### Expected Behavior

Should be parsed since it works fine against DB2.

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version: 1.2
  - Platform: Windows 7
  - Subsystem:

**Comment by manticore-projects** [comment]
Solved via PR #1252
