### ISSUE TITLE
Parse sql with many statemts

### ISSUE THREAD

**Issue by albertotn** [JSQLParser/JSqlParser#691]
### Actual Behavior
Goes in error

### Expected Behavior
Parse correctly the provided sql

### Steps to Reproduce the Problem

  1.  define a file with following sql:

```
select * from dual;

select
*
from
dual;

select *
from dual;

```
  2. try to parse it with CCJSqlParserUtil.parse()
  3. goes in error

### Specifications

  - Version:  jsqlparser1.3
  - Platform: windows 10 64 bit
  - Subsystem: java 8

**Comment by wumpz** [comment]
CCJSqlParserUtil.parse() is only a single statement parse. You want to use CCJSqlParserUtil.parseStatements(). I included a test using your example.

CCJSqlParserUtilTest.testParseStatementsIssue691

Cheers Tobias

**Comment by wumpz** [comment]
But it should work, if there is a SQL added to it. The parse expects to get at least one imho.

**Comment by albertotn** [comment]
Okay, this is my problem right now, an sql file with:

```
select * from dual;
---comment
```

on two different lines goes in error

**Comment by albertotn** [comment]
You are right, I was on another test case:

-- comment1
-- comment2

a file with this content gives following error:

```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:74)
	at com.gradle.validator.sql.FirstTest.main(FirstTest.java:19)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 2, column 22.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMIT"
    "DELETE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:72)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 2, column 22.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMIT"
    "DELETE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:206)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:72)
	at com.gradle.validator.sql.FirstTest.main(FirstTest.java:19)

```
So if I have a file with comments only gives error, is this correct ?

**Comment by AnEmortalKid** [comment]
That seems like correct behavior to me, based on:

https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L365

> Tokens that are defined as special tokens in the lexical specification are ignored during parsing, but these tokens are available for processing by the tools. A useful application of this is in the processing of comments. -- from JavaCC

And the 3 expected productions:
https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L391

So there must be at least a statement/block/set of statements. Since comments are ignored, nothing is parsed.
