### ISSUE TITLE
Error while parsing alter table max_rows or min_rows in mysql

### ISSUE THREAD

**Issue by 1987bishop** [JSQLParser/JSqlParser#714]
like this:
alter table abc max_rows = 1000;

jsqlparser code:
        String result = SQLUtils.format(sql, dbType);
        System.out.println(result); 
        Statements stmts = CCJSqlParserUtil.parseStatements("alter table abc max_rows = 1000;");
        List<Statement> stmtList = stmts.getStatements();

        System.out.println("size is:" + stmtList.size());
        for (int i = 0; i < stmtList.size(); i++) {

            Statement stmt = stmtList.get(i);

            TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
            List<String> tableList = tablesNamesFinder.getTableList(stmt);

            System.out.println("Tables : " + tableList);
        }

exception:
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154)
	at com.netease.backend.rds.websql.test.rds.TestDruid.main(TestDruid.java:34)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "max_rows" <S_IDENTIFIER>
    at line 1, column 17.

Was expecting one of:

    "ADD"
    "DROP"
    "MODIFY"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:11652)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:11665)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:157)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:430)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "max_rows" <S_IDENTIFIER>
    at line 1, column 17.

Was expecting one of:

    "ADD"
    "DROP"
    "MODIFY"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:11652)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:11665)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:157)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:430)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)

**Comment by wumpz** [comment]
Out of curiosity. What does this do?

    "alter table abc max_rows = 1000;"

Is max_rows a table property?

**Comment by 1987bishop** [comment]
When you create a MyISAM table, MySQL uses the product of the MAX_ROWS and AVG_ROW_LENGTH options to decide how big the resulting table is.

**Comment by 1987bishop** [comment]
https://dev.mysql.com/doc/refman/5.7/en/create-table.html

**Comment by manticore-projects** [comment]
See `UnsupportedStatements` as explain in #1945 (unless you will sponsor or provide a specific implementation of this feature.)
