### ISSUE TITLE
`SELECT column IS NOT NULL` not parsed

### ISSUE THREAD

**Issue by datto-aparrill** [JSQLParser/JSqlParser#720]
Example query:
```sql
SELECT column IS NOT NULL FROM table
```
`CCJSqlParserUtil.parse` throws an error:

```plain
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -javaagent:/opt/idea-IC-182.4892.20/lib/idea_rt.jar=38901:/opt/idea-IC-182.4892.20/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/home/aparrill/Code/jsqlparsertest/target/classes:/home/aparrill/.m2/repository/com/github/jsqlparser/jsqlparser/1.3/jsqlparser-1.3.jar Test
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:55)
	at Test.main(Test.java:7)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IS" "IS"
    at line 1, column 15.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COMMIT"
    "CONNECT"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TRUNCATE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "XML"
    "ZONE"
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IS" "IS"
    at line 1, column 15.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COMMIT"
    "CONNECT"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TRUNCATE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "XML"
    "ZONE"
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
	at Test.main(Test.java:7)

Process finished with exit code 0
```
Using version 1.3

**Comment by datto-aparrill** [comment]
Looking at this more, since conditions are not expressions in the grammar, any bare condition in the select values (Ex. `SELECT column > 4 FROM table`) results in a parse error despite being valid SQL.

**Comment by datto-aparrill** [comment]
Wait, no, `AndExpression` parses for `Condition`... So why doesn't it parse?

**Comment by datto-aparrill** [comment]
...Because `SELECT` tries to match `SimpleExpression` which does not include `AndExpression` or `Condition`, which seems incorrect.

In fact, it seems most usages of `SimpleExpression` are incorrect. For example `INSERT INTO foo VALUES (1 AND 1)` doesn't parse either because the values are `SimpleExpression`.

**Comment by datto-aparrill** [comment]
So it looks like `Expression` is used in contexts that expect a boolean value (`WHERE`, `JOIN ON`, etc), while `SimpleExpression` is used in context that expect a non-boolean value ("SELECT ...`, `UPDATE SET a=...`). They both match different things; for example, only `Expression` matches boolean operations (`AND`, `OR`) and comparisons (`>`, `=`, `IS NULL), while only `SimpleExpression` matches things like string literals, query parameters (`?`).

This doesn't match how any database I'm aware of parses queries. All of them use one type of expression in all contexts, and either coerce non-boolean values or do type analysis. JSqlParser's use of two types of expressions causes it to not be able to parse SQL queries that operate on booleans.

If we decide to use JSqlParser moving forward, I'll likely be working on some patches for this.

**Comment by michael-walker** [comment]
Hi,

Did anyone write a fix, PR for this?

Cheers

**Comment by datto-aparrill** [comment]
We didn't. We decided not to use JSqlParser.

**Comment by michael-walker** [comment]
An interim 'solution' to get around this is wrapping it in a case statement.  `CASE WHEN ... THEN true ELSE false end`

**Comment by datto-aparrill** [comment]
> An interim 'solution' to get around this is wrapping it in a case statement. `CASE WHEN ... THEN true ELSE false end`

This only works if you have control the SQL being parsed, which is a big assumption. Our use case was parsing log messages from production databases, where we don't have control over what the applications run.

**Comment by wumpz** [comment]
A possible solution is provided here: https://github.com/JSQLParser/JSqlParser/issues/767#issuecomment-496091325. However, that is not a final solution, which would require some grammar refactoring.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
