### ISSUE TITLE
Error while parsing virtual columns in create table statement

### ISSUE THREAD

**Issue by 1987bishop** [JSQLParser/JSqlParser#729]
like this:
create table xuhan3(id int not null AUTO_INCREMENT primary key, name char(40), SimpleDate date, `SimpleDate_dayofweek` tinyint(4) GENERATED ALWAYS AS (dayofweek(SimpleDate)) VIRTUAL, KEY `SimpleDate_dayofweek` (`SimpleDate_dayofweek`));

jsqlparser code:
Statements stmts = CCJSqlParserUtil.parseStatements("create table xuhan3(id int not null AUTO_INCREMENT primary key, name char(40), SimpleDate date, `SimpleDate_dayofweek` tinyint(4) GENERATED ALWAYS AS (dayofweek(SimpleDate)) VIRTUAL, KEY `SimpleDate_dayofweek` (`SimpleDate_dayofweek`));");
        List<Statement> stmtList = stmts.getStatements();

        System.out.println("size is:" + stmtList.size());
        for (int i = 0; i < stmtList.size(); i++) {

            Statement stmt = stmtList.get(i);

            TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
            List<String> tableList = tablesNamesFinder.getTableList(stmt);

            System.out.println("Tables : " + tableList);
        }

exception:
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154)
	at com.netease.backend.rds.websql.test.rds.TestDruid.main(TestDruid.java:34)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AS" "AS"
    at line 1, column 148.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "."
    "="
    "BY"
    "CASCADE"
    "CHECK"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:10231)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:169)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:430)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AS" "AS"
    at line 1, column 148.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "."
    "="
    "BY"
    "CASCADE"
    "CHECK"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:10231)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:169)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:430)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)

**Comment by manticore-projects** [comment]
Works with JSQLParser 4.10-Snapshot. [You can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4A8CuALAhgOwGZYAKAKFgtgEsATS+hxpigSQDkpnY2B5TtgKrJksCAKg8A+u1BgAsmA6wACiBZyIIAJqwA0mC3lKAGlh4cAWwCmXW-WAAJTSQAsABgCURiqYDOVCwAHABsrGhwAFxs7BgARaDBvWD8AkLDIq0lwgE8AewAzAHcrKwBrJih2LXZOYhcPWABxRTAQBNjRZAB1CC0AZVEB4nitHgAxLrAwXWI+9WVUeJgPBoA1FhAoAQhkJNN9LQPYfyDQ8KisnDyikvLZ1NDYjMvr4rKvLwBuIA)
