### ISSUE TITLE
Cannot parse CREATE TABLE statement with COMMENT for column definitions

### ISSUE THREAD

**Issue by PraTrick** [JSQLParser/JSqlParser#742]
### Actual Behavior
Fails with the below exception stacktrace.
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "COMMENT" "COMMENT"
    at line 3, column 49.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "="
    "BY"
    "CASCADE"
    "CHECK"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:19398)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:19248)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:10698)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:173)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:83)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)

### Expected Behavior
Parse the CREATE TABLE statement with comment(s) for the column definitions.

### Steps to Reproduce the Problem

  1. CREATE TABLE `table_name` (`id` bigint (20) NOT NULL AUTO_INCREMENT, `another_column_id` bigint (20) NOT NULL COMMENT 'column id as sent by SYSTEM', PRIMARY KEY (`id`), UNIQUE KEY `uk_another_column_id` (`another_column_id`))

### Specifications

  - Version: 1.4
  - Platform: Mac OS X
  - Subsystem:

**Comment by PraTrick** [comment]
Created [PR-743](https://github.com/JSQLParser/JSqlParser/pull/743)
