### ISSUE TITLE
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 82, column 16.

### ISSUE THREAD

**Issue by fushun1990** [JSQLParser/JSqlParser#757]
### Actual Behavior

above code throws and exception:

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 82, column 16.
Was expecting one of:
    "NULL" ...
    "CASE" ...
    "INTERVAL" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:5654)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:5223)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:5179)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:5135)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:5064)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:5092)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:5056)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrderByElement(CCJSqlParser.java:3589)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrderByElements(CCJSqlParser.java:3566)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2062)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:6847)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:5618)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:5223)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:5179)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:5135)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:5064)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:5092)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:5056)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:2349)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:2462)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:2339)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1992)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:6847)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:2908)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2006)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1876)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:111)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 190 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 82, column 16.
Was expecting one of:
    "NULL" ...
    "CASE" ...
    "INTERVAL" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "INTERVAL" ...
    "NULL" ...
    "CASE" ...
    "GROUP_CONCAT" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:5654)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:5223)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:5179)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:5135)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:5064)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:5092)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:5056)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrderByElement(CCJSqlParser.java:3589)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrderByElements(CCJSqlParser.java:3566)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2062)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:6847)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:5618)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:5223)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:5179)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:5135)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:5064)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:5092)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:5056)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:2349)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:2462)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:2339)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1992)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:6847)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:2908)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2006)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1889)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1876)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:111)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)

sql：
SELECT
    t.*
     
      ,CONCAT('CS_CRR_',t.grade) AS MT_CE_MAIN_RULER_CD
     
    FROM (SELECT
    cc.ID AS CIF_ID,
    cc.MT_TENANT_ID AS MT_TENANT_ID,
    cc.NM AS NM,
    cc.APP_ID AS APP_ID,
    cc.LOAN_REMARK,
    cdt_file_cif.CDT_FILE_ID AS CDT_FILE_ID,
    wa.dt_created AS DT_CREATED,
    wa.mt_app_sts_cd AS MT_APP_STS_CD,
    wa.mt_app_typ_cd AS mt_app_typ,
    CASE WHEN JSON_LENGTH(TSK_HIS_HDR_IDS) IS NULL THEN wa.TSK_HDR_ID
    WHEN JSON_LENGTH(TSK_HIS_HDR_IDS) = 0 THEN wa.TSK_HDR_ID
    WHEN TSK_HDR_ID != JSON_UNQUOTE(JSON_EXTRACT(TSK_HIS_HDR_IDS, CONCAT('$[',
    JSON_LENGTH(TSK_HIS_HDR_IDS) - 1, ']'))) THEN wa.TSK_HDR_ID
    ELSE NULL
    END AS TSK_HDR_ID,
    wa.CUST_MGR_ID AS CUST_MGR_ID,
     
     
      (CASE WHEN wa.MT_APP_TYP_CD ='CS_PUSH_APP' THEN (
      CASE wa.mt_app_sts_cd
      
       
        WHEN 'CREATED' THEN 1
        WHEN 'PENDING_REVIEW' THEN 2
        WHEN 'PENDING_DRC1_REVIEW' THEN 3
        WHEN 'PENDING_DRC2_REVIEW' THEN 4
        WHEN 'PENDING_DRC3_REVIEW' THEN 5
        WHEN 'PENDING_PUSH' THEN 6
        WHEN 'MGR_RETURN' THEN 7
        WHEN 'DRC1_RETURN' THEN 8
        WHEN 'DRC2_RETURN' THEN 9
        WHEN 'DRC3_RETURN' THEN 10
        WHEN 'DRC_RETURN' THEN 11
        WHEN 'CS_PUSH_APP_MGR_RETURNED' THEN 12
        WHEN 'CS_PUSH_APP_DRC1_RETURNED' THEN 13
        WHEN 'CS_PUSH_APP_DRC2_RETURNED' THEN 14
        WHEN 'CS_PUSH_APP_DRC3_RETURNED' THEN 15
        WHEN 'CS_PUSH_APP_RETURNED' THEN 16
        WHEN 'CS_PUSH_APP_PUSHED' THEN 17
        WHEN 'APPROVED' THEN 18
        WHEN 'CANCELLED' THEN 19 END)
       
      
      
       
      END) PUCH_APP_ORDER,
     
   
     
     
   
     
     
   
     
     
   
    wa.DT_APP_STS_CHANGED AS DT_APP_STS_CHANGED,
    wa.MT_LOAN_STYLE_TYPE_CD,
     
         

        wa.DT_APP_STS_CHANGED AS DT_OPERATE,
        wa.REF_NO AS REF_NO,

     
     
     
      cs_fac_prc.INT_RATE AS INT_RATE,
      cs_fac_prc.FINAL_INT_RATE AS FINAL_INT_RATE,
     
     
      (SELECT cs_cif_id_no.ID_NO FROM cs_cif_id_no WHERE cs_cif_id_no.APP_ID = cc.APP_ID AND
      cs_cif_id_no.CIF_ID = cc.ID
      ORDER BY (CASE (cs_cif_id_no.MT_CIF_ID_TYP_CD REGEXP '^C*[0-9]+$') WHEN 1 THEN
      CONCAT('Z',cs_cif_id_no.MT_CIF_ID_TYP_CD) ELSE cs_cif_id_no.MT_CIF_ID_TYP_CD END) LIMIT 1)
      ID_NO,
     
     
      JSON_UNQUOTE(JSON_EXTRACT(CONCAT('[',GROUP_CONCAT(CONCAT('"',case when
      cs_cif_rating.MT_RATING_TYP_CD='CS_CRR' then cs_cif_rating.GRADE else null end,'"') ORDER BY
      cs_cif_rating.DT_CREATED DESC),']'),'$[0]')) GRADE,
      JSON_UNQUOTE(JSON_EXTRACT(CONCAT('[',GROUP_CONCAT(CONCAT('"',case when
      cs_cif_rating.MT_RATING_TYP_CD='CS_CRR' then cs_cif_rating.SCORE else null end,'"') ORDER BY
      cs_cif_rating.DT_CREATED DESC),']'),'$[0]')) SCORE,
      JSON_UNQUOTE(JSON_EXTRACT(CONCAT('[',GROUP_CONCAT(CONCAT('"',case when
      cs_cif_rating.MT_RATING_TYP_CD='FINALSCORE' or cs_cif_rating.MT_RATING_TYP_CD='FR' or
      cs_cif_rating.MT_RATING_TYP_CD='PRELOAN' then cs_cif_rating.SCORE else null end,'"') ORDER BY
      cs_cif_rating.MT_RATING_TYP_CD,cs_cif_rating.DT_CREATED DESC),']'),'$[0]')) FRAUDSCORE,
     
     
     
      cf.id FAC_ID,
      cf.TENURE_APPR AS TENURE_APPR,
      cf.FINAL_TENURE_APPR AS FINAL_TENURE_APPR,
      cf.MT_FAC_CD AS MT_FAC_CD,
      cf.MT_TIME_CD AS MT_TIME_CD,
      cf.FINAL_MT_TIME_CD AS FINAL_MT_TIME_CD,
      cf.MT_COUNTY_CD AS MT_CITY_CD,
      cf.LMT_APPR AS LMT_APPR,
      cf.FINAL_LMT_APPR AS FINAL_LMT_APPR,
      (CASE cf.MT_TIME_CD WHEN 'Y' THEN (cf.TENURE_APPR * 12 * 30 + 0.2) WHEN 'M' THEN
      (cf.TENURE_APPR * 30 + 0.1) WHEN 'D' THEN cf.TENURE_APPR ELSE 0 END) DEADLINE,
     
     
      cci.MOBILE_NO AS MOBILE_NO,
     
    wa.TO_TENANT_ID FIN_ID
    FROM v_wf_app_sc wa
    INNER JOIN cs_cif cc ON wa.id = cc.APP_ID AND
    cc.MT_TENANT_ID=wa.MT_TENANT_ID
    INNER JOIN cdt_file_cif ON cdt_file_cif.CIF_ID = cc.ID AND cdt_file_cif.MT_FAC_REL_CD = 'P' AND
    cdt_file_cif.CDT_FILE_ID=wa.CDT_FILE_ID
     
      LEFT JOIN cs_fac cf ON cf.APP_ID = cc.APP_ID AND cf.MT_TENANT_ID = cc.MT_TENANT_ID AND
      cf.STATUS = 'NEW'
     
     
      LEFT JOIN cs_fac_prc ON cs_fac_prc.APP_ID = cc.APP_ID AND cs_fac_prc.fac_id = cf.ID
     
     
      LEFT JOIN cs_cif_indv cci ON cc.ID = cci.CIF_ID AND cc.MT_TENANT_ID = cci.MT_TENANT_ID AND
      cc.APP_ID = cci.APP_ID
     
     
      LEFT JOIN cs_cif_rating ON cs_cif_rating.APP_ID = cc.APP_ID AND cs_cif_rating.cif_id = cc.id
     
    
     
     WHERE wa.MT_TENANT_ID = ?
      AND cc.MT_CIF_TYP_CD = ?
      AND wa.MT_APP_TYP_CD = ?
      
      
      
        AND wa.CUST_MGR_ID IS NOT NULL
      
      
        AND wa.TSK_HDR_ID = ?
        AND (JSON_LENGTH(wa.TSK_HIS_HDR_IDS) IS NULL
        OR JSON_LENGTH(wa.TSK_HIS_HDR_IDS) = 0
        OR wa.TSK_HDR_ID != REPLACE(JSON_EXTRACT(wa.TSK_HIS_HDR_IDS, CONCAT('$[',
        JSON_LENGTH(wa.TSK_HIS_HDR_IDS) - 1, ']')), '"', ''))
      
      
      
      
      
        AND cf.MT_FAC_CD IN
        (
          ?
        ,
          ?
        )
      
      
      
      
      
        AND (
        REPLACE(JSON_EXTRACT(cc.LOAN_REMARK, '$.mtStateCd'), '"', '') IN
        (
          ?
        )
        OR
        REPLACE(JSON_EXTRACT(cc.LOAN_REMARK, '$.mtCityCd'), '"', '') IN
        (
          ?
        )
        )
      
      
      
         AND wa.CUST_MGR_ID in (
          ?
        ,
          ?
        )
      
      
         AND wa.mt_app_sts_cd in (
          ?
        ,
          ?
        ,
          ?
        ,
          ?
        ,
          ?
        ,
          ?
        ) 
   
    
     
      GROUP BY cc.APP_ID,cc.id
     
    ) t
    
     
     WHERE  (t.ID_NO = UPPER(?) OR t.NM = ? OR t.MOBILE_NO = ?)
      
      
      
      
      
        AND IFNULL(t.GRADE, '-') in (
          ?
        ,
          ?
        )
      
      
        AND
        (
          
              (FLOOR(t.DEADLINE) BETWEEN ? AND
              ?)
            
        )
      
      
      
      
      

      
      
        AND
        (
          
          
            (
            
              t.FRAUDSCORE > ? and t.FRAUDSCORE <= ?
            
            
            )
          
          
          
        
          
          OR
            (
            
            
              t.FRAUDSCORE >= 0 and t.FRAUDSCORE <= ?
            
            )
          
          
          
        )
      

      
        AND
        (
          
              (t.INT_RATE BETWEEN ? AND ?)
            
        )
      
      
        AND
        (
          
              (t.LMT_APPR BETWEEN ? AND ?)
            
        )
      
      
      
      
      
        
        
      
      
      
        AND TO_DAYS(?) >= TO_DAYS(t.DT_CREATED)
      
      
      
        AND TO_DAYS(t.DT_CREATED) >= TO_DAYS(?) order by DT_CREATED ASC LIMIT ?

Parameters：
 1000(String), I(String), CS_PUSH_APP(String), 044e4e60e38448ad91c83fcc51af168a(String), P110833(String), P110919(String), 110000(String), 110000(String), 3a4c16cf328b4f1695e79e6ea6643e35(String), 171b29669788450e84db14815828ba8d(String), DRC_RETURN(String), CS_PUSH_APP_MGR_RETURNED(String), CS_PUSH_APP_DRC1_RETURNED(String), CS_PUSH_APP_DRC2_RETURNED(String), CS_PUSH_APP_DRC3_RETURNED(String), PENDING_DRC2_REVIEW(String), 111(String), 111(String), 111(String), D(String), C(String), 360(String), 3960(String), 38(String), 59(String), 38(String), 1(String), 11(String), 10000(String), 110000(String), 2019-02-27 00:00:00.0(Timestamp), 2019-02-01 00:00:00.0(Timestamp), 10(Integer)

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version:jsqlparser-0.9.5
  - Platform: jdk8, mysql，windows
  - Subsystem:

**Comment by wumpz** [comment]
Could you try again with a more recent version?

**Comment by wumpz** [comment]
can we close this issue?
