### ISSUE TITLE
CCJSqlParserUtil.parseCondExpression gets an incorrect result of exp "COUNT(TRIM(a) = 'a')"

### ISSUE THREAD

**Issue by wukaikailive** [JSQLParser/JSqlParser#788]
Version:V2.0
```
CCJSqlParserUtil.parseCondExpression("COUNT(TRIM(a))")
```
Get ```COUNT(TRIM(a))```,That's correct！

But
```
CCJSqlParserUtil.parseCondExpression("COUNT(TRIM(a) = 'a')")
```
Just get ```COUNT```,That's incorrect!

Is there any solution?

**Comment by wumpz** [comment]
There is only a limited set of functions that accepts relations as parameters due to performance issues. The parse method parses as much as possible.

**Comment by wukaikailive** [comment]
But this usage is real. Would you consider supporting it?

**Comment by wukaikailive** [comment]
I found that  ```COUNT(TRIM(a) - 'a')``` or ```COUNT(TRIM(a) + 'a')``` would get the right result, but using operators such as ```>,<,=``` would get the wrong result, so this might be a bug?

**Comment by ulyn** [comment]
It's the same problem.

`SELECT SEX,SUM(AGE <=16) FROM TABLE GROUP BY SEX`

**Comment by yuzhougit** [comment]
I found a similar issue when parse below statement

SELECT `NAME` = 'dgadmin' AS IS_SUPER  FROM  `AD_USER`

**Comment by yuzhougit** [comment]
> I found a similar issue when parse below statement
> 
> SELECT `NAME` = 'dgadmin' AS IS_SUPER FROM `AD_USER`

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:43)
	at com.whimsoft.base.common.CommonCodeGeneratorTest.testJSqlParser(CommonCodeGeneratorTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 1, column 15.

**Comment by bigfacewo** [comment]
> I found a similar issue when parse below statement
> 
> SELECT `NAME` = 'dgadmin' AS IS_SUPER FROM `AD_USER`

JSqlParser does not seem to support the existence of Boolean expressions in SELECT lists

**Comment by manticore-projects** [comment]
[Sample 1 tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgCltATgSwFssBDWASlgF5YByYm8gKADEAlAeQFlY1iAjADYBTFMQJDGAbiA+)

[Last sample also tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEB2BDAtgU1gXlgcgCYHNFdkBLebWAQWFhIGcB9OgVwAdUAnAKADEAlAPIBZWEQbM6nLgG4gA+)
