### ISSUE TITLE
Failed to parse valid "SELECT" statement containing a column named `limit`

### ISSUE THREAD

**Issue by dgloeckner** [JSQLParser/JSqlParser#790]
### Actual Behavior
Parsing of `SELECT limit FROM mytable` fails.

```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:34)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:52)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:40)
	at net.sf.jsqlparser.statement.select.SelectTest.testLimitColumnNameForOracle(SelectTest.java:1593)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
```

### Expected Behavior
SQL statement can be parsed.

### Steps to Reproduce the Problem
Execute a test similar to the following:

```
 @Test
    public void testLimitColumnNameForOracle() throws JSQLParserException {
        // 'limit' is not a restricted keyword in Oracle.
        String sql = "SELECT limit FROM (SELECT * FROM table2 WHERE col1 = 'val')";
        assertSqlCanBeParsedAndDeparsed(sql);
    }

    @Test
    public void testLimitColumnInWhereClauseForOracle() throws JSQLParserException {
        // 'limit' is not a restricted keyword in Oracle.
        String sql = "SELECT * FROM table2 WHERE limit > 200";
        assertSqlCanBeParsedAndDeparsed(sql);
    }
```

**Comment by dgloeckner** [comment]
Hi guys! I proposed a fix for this issue. Please see the PR.

**Comment by AnEmortalKid** [comment]
@wumpz also closeable

![image](https://user-images.githubusercontent.com/3474369/85235063-b25cfb00-b3d7-11ea-850e-cf250e6d2d88.png)
