### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by Allurx** [JSQLParser/JSqlParser#842]
# Describe the bug
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("

# To Reproduce
## Example SQL
``` mysql
SELECT a.id                                                   lendId,
       a.lend_code                                            lendCode,
       a.amount,
       a.remaining_principal                                  remainingPrincipal,
       a.interest_rate                                        interestRate,
       date_add(a.lend_time, INTERVAL a.repayment_period DAY) lendEndTime,
       a.lend_time                                            lendTime
FROM risk_lend a
WHERE a.loan_id = 1
``` 
## Exception
``` java
Cause: com.github.pagehelper.PageException: 处理排序失败: net.sf.jsqlparser.JSQLParserException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 91 common frames omitted
Caused by: com.github.pagehelper.PageException: 处理排序失败: net.sf.jsqlparser.JSQLParserException
	at com.github.pagehelper.parser.OrderByParser.converToOrderBySql(OrderByParser.java:64)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getPageSql(AbstractHelperDialect.java:173)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:98)
	at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:168)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:104)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy255.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 96 common frames omitted
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:43)
	at com.github.pagehelper.parser.OrderByParser.converToOrderBySql(OrderByParser.java:52)
	... 103 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 6, column 24.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "DESCRIBE"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20951)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20798)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:41)
	... 104 common frames omitted
```

# System
 - mysql 8.0.13-commercial
- jdk 1.8
- com.github.pagehelper:pagehelper:5.1.8
      com.github.jsqlparser:jsqlparser:1.2
# additional
When I execute this sql statement, jsqlparser does not seem to recognize the **date_add** function.

**Comment by Allurx** [comment]
@wumpz 
Why is this issue closed?

**Comment by wumpz** [comment]
Because it was solved. Look into the commit. There are tests.
Could be that I did not deploy the actual snapshot.

**Comment by Allurx** [comment]
Ok, thank you very much.

**Comment by wumpz** [comment]
I deployed the actual version. Could you check it?

**Comment by Allurx** [comment]
@wumpz 
Thank you very much, jsqlparser-3.0-20190827.204503-3.jar perfectly solved my problem. Now everything is working fine. When will the official release of 3.0 be released to the maven central repository?

**Comment by wumpz** [comment]
You are right to ask. There are a lot of changes already waiting for release. I think I will do it within this week.
