### ISSUE TITLE
Some SQL cannot be parsed

### ISSUE THREAD

**Issue by chenzhx666** [JSQLParser/JSqlParser#848]
**Describe the bug**
Some SQL cannot be parsed.

**To Reproduce**
1.  SELECT IF (USER_ID>10 AND SEX=1,1,0)  FROM  TABLE
2. Parsing this SQL using JSqlParser with this statements
3. net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IF" "IF"

**Comment by wumpz** [comment]
This if function does not (yet) support complex boolean expressions. 

`SELECT IF (USER_ID>10,1,0) FROM TABLE`

works as expected.

**Comment by chenzhx666** [comment]
Can you optimize it?Make it supportive?

**Comment by wumpz** [comment]
At the moment I have not enough time. PRs are welcome. If I can spend a minute, I will look into it.

**Comment by shenodaguirguis** [comment]
I have a similar problem with Select stmt being in the Select clause (like with MULTISET operator for oracle nested tables), for example:
`select c1, multiset(select * from table where cond = 10) from T1 where cond2 = 20");`
parsing this results in:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 20.

Any work around?

**Comment by wumpz** [comment]
@shenodaguirguis I could not recreate your problem. The parser is working successful on your statements. 

@chenzhx666 The fix does now support more complex expression as parameters. Your statement is parsed now.

**Comment by shenodaguirguis** [comment]
what version should I use to get that fix? I tried reloading 1.1 and here is the error stack:

CCJSqlParserManager jSqlParserManager = new CCJSqlParserManager();
    Select select = (Select) jSqlParserManager.parse(new StringReader("select c1, multiset(select * from table where cond = 10) from T1 where cond2 = 20"));

> net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.linkedin.queryrewrite.ExampleMainTest.testJSQLParser(ExampleMainTest.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 20.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "VALUE" ...
    "HAVING" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "INTERSECT" ...
    "CAST" ...
    "EXCEPT" ...
    "MINUS" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	... 23 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 20.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "VALUE" ...
    "HAVING" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "INTERSECT" ...
    "CAST" ...
    "EXCEPT" ...
    "MINUS" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
	at com.linkedin.queryrewrite.ExampleMainTest.testJSQLParser(ExampleMainTest.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by wumpz** [comment]
Do you use version 1.1? The actual release is 3.0.

**Comment by shenodaguirguis** [comment]
Yes, release 3.0 works, thanks a lot!
