### ISSUE TITLE
Support for "RENAME TO" is no more available in 3.0

### ISSUE THREAD

**Issue by eolivelli** [JSQLParser/JSqlParser#860]
I am upgrading HerdDB (https://github.com/diennea/herddb) from 0.9.7 to 3.0.
And now it seems that jSQLParser refuses to parse DDL queries like

`ALTER TABLE tblspace1.tsql MODIFY COLUMN k1 int RENAME TO l2`

The error is:
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at herddb.sql.DDLSQLPlanner.parseStatement(DDLSQLPlanner.java:234)
	... 30 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "TO" "TO"
    at line 1, column 56.
Was expecting one of:
    "("
    "+"
    ","
    "-"
    "."
    "::"
    ";"
    "="
    "BY"
    "CASCADE"
    "CHECK"
    "COLLATE"
    "COMMENT"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <EOF>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:85)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 32 more
```

is there any workaround or alternative syntax ?

**Comment by eolivelli** [comment]
PR on downstream project: https://github.com/diennea/herddb/pull/481

**Comment by eolivelli** [comment]
Moving to 'ALTER TABLE tblspace1.tsql CHANGE k1 l2 int'

**Comment by wumpz** [comment]
However the original statement should work as well. I will look into it.

**Comment by eolivelli** [comment]
It was a trick, we were using the column definition and decode keywords 'rename' and 'to''.

There is no much value is supporting that kind of hacks

**Comment by wumpz** [comment]
Ok. Agreed.
