### ISSUE TITLE
JSqlParser cannot parser with assign operator ":="

### ISSUE THREAD

**Issue by krime** [JSQLParser/JSqlParser#873]
JSqlParser cannot parse assign operator ":=". For example, following statements are valid in MySQL:

`select id, (@rid:=@rid+id) as rid from t, (select (@rid:=0) as rid) r order by id asc`

However, an attempt to parse the query with:

```java
String sql = "select id, (@rid:=@rid+id) as rid from t, (select (@rid:=0) as rid) r order by id asc";
Select select = (Select) CCJSqlParserUtil.parse(sql);
```
Comes with:
```text
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"
    at line 1, column 17.

Was expecting one of:

    "&"
    ")"
    "."
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:9189)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:8931)
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:8884)
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:8847)
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:8793)
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:8769)
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:8762)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:4090)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:4278)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:4081)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3588)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3795)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3477)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3470)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 39 more
```

My jsqlparser version is 3.0.

**Comment by haakonflatval-cognite** [comment]
I second this. Are there any thoughts on adding this feature in the future?

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
