### ISSUE TITLE
About  the use of "with as" grammar probleam

### ISSUE THREAD

**Issue by xiearthur** [JSQLParser/JSqlParser#874]
An error occurred when I tried to use the with syntax

my sql is:
```
with rn as (
  select rownum rn
  from dual
  connect by level <= (select max(cases) from t1))
select pname
from t1, rn
where rn <= cases
order by pname
```

ERROR is:

```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:130)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.getWithSelect(CCJSqlParserUtil.java:94)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseSqlAst(CCJSqlParserUtil.java:79)
	at net.sf.jsqlparser.parser.CCJSqlParserUtilTest.parseSqlAst(CCJSqlParserUtilTest.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: net.sf.jsqlparser.parser.ParseException
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20965)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20812)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:230)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:128)
	... 29 more
Caused by:
net.sf.jsqlparser.parser.ParseException
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20965)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20812)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:230)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:128)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.getWithSelect(CCJSqlParserUtil.java:94)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseSqlAst(CCJSqlParserUtil.java:79)
	at net.sf.jsqlparser.parser.CCJSqlParserUtilTest.parseSqlAst(CCJSqlParserUtilTest
```

**Comment by wumpz** [comment]
I created a test from your sql and at least JSqlParser V3.1-SNAPSHOT parses it without any problems.

**Comment by wumpz** [comment]
Should I close this issue?
