### ISSUE TITLE
JSqlParser does not support "AS" statement in selection

### ISSUE THREAD

**Issue by bingrao** [JSQLParser/JSqlParser#879]
**Describe the bug**
Just use "CCJSqlParserUtil.parse(sql)" to parse the "sql" and return with an exception. 

**To Reproduce**
1. Input SQL: SELECT DISTINCT T1.creation FROM department AS T1 JOIN management AS T2 ON T1.department_id  =  T2.department_id JOIN head AS T3 ON T2.head_id  =  T3.head_id WHERE T3.born_state  =  'Alabama';
2. Parsing this SQL using JSqlParser with this statements
3. Exception

Exception in thread "main" java.lang.Exception: Exception while parsing following sql 
 department AS  
 Cause of exception is 
 net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "department" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"

	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.utils.ParsingUtils$.validateSql(ParsingUtils.scala:30)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.DataFrame.create(DataFrame.scala:68)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.DataFrame.<init>(DataFrame.scala:50)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.DataFrame.addFromTable(DataFrame.scala:211)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.DataFrame.create(DataFrame.scala:129)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.DataFrame.<init>(DataFrame.scala:50)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.SqlToDfConversion$$anonfun$start$1.apply(SqlToDfConversion.scala:84)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.SqlToDfConversion$$anonfun$start$1.apply(SqlToDfConversion.scala:81)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at io.github.mvamsichaitanya.codeconversion.sqltodataframe.SqlToDfConversion$.start(SqlToDfConversion.scala:80)
	at MainRun$.main(MainRun.scala:22)
	at MainRun.main(MainRun.scala)

Process finished with exit code 1

**Expected behavior**

CCJSqlParserUtil.parse(sql) should return with no exceptions. 

**System**
 - Database you are using:  just parse the sql query
- Java Version: 1.8
- JSqlParser version: 3.0

**Comment by wumpz** [comment]
Using JSqlParser 3.0 I am able parse this statement successfully. However I used:

Statements parseStatements = CCJSqlParserUtil.parseStatements("select `...");`

**Comment by bingrao** [comment]
Thanks so much for your quick reply. I made a mistake.  It has been fixed out.

**Comment by wumpz** [comment]
Never mind. Thx for using JSqlParser. ;)
