### ISSUE TITLE
Mysql ParseException

### ISSUE THREAD

**Issue by cyping258** [JSQLParser/JSqlParser#893]
Describe the bug
JSqlParser failed to parse mysql8 "SELECT" statement with "IN" clause.

To Reproduce

SQL: SELECT * FROM schedule_info info WHERE (info.employee_id,info.schedule_date) IN ((1,'2019-10-01'),(1,'2019-10-02'));

Exception:

Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 40, column 25.

Was expecting one of:

    "&"
    "&&"
    ")"
    "::"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:6779)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:6687)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:6658)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:5675)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3387)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3560)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3253)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3246)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:119)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)

System

Database you are using
mysql 8
Java Version
JDK 1.8
JSqlParser version
2.0

**Comment by wumpz** [comment]
Could you first try to use a more recent version of JSqlParser, if this issue was already adressed?

**Comment by sivaraam** [comment]
I happened to check whether a similar query works without issues in version 3.1 of the library and found that the parser does **fail** to parse the query.

**Tested query**
```sql
select * from employee as e where (emp_id, emp_name) in ((1, 'andrew'), (3, 'john'));
```

**Code**
```java
    public static void main (String[] args) throws JSQLParserException {
        Statement st = CCJSqlParserUtil.parse(
                "select * from employee as e where (emp_id, emp_name) in ((1, 'andrew'), (3, 'john'));"
        );
        System.out.println(st);
    }
```

**Exception**
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
    ...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 42.

Was expecting one of:

    "&"
    "&&"
    ")"
    "::"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "["
    "^"
    "|"

```
