### ISSUE TITLE
Encountered unexpected token: "drop" "DROP"

### ISSUE THREAD

**Issue by hongchq** [JSQLParser/JSqlParser#918]
**Describe the bug**

**To Reproduce**
1. Example SQL：ALTER TABLE "user_table_t" ALTER COLUMN name drop NOT NULL;
2. Parsing this SQL using JSqlParser with this statements
3. Exception：
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "drop" "DROP"
    at line 1, column 46.

Was expecting one of:

    "BIT"
    "CHAR"
    "CHARACTER"
    "DOUBLE"
    "INTERVAL"
    "SET"
    "SIGNED"
    "TYPE"
    "UNSIGNED"
    "XML"
    <DT_ZONE>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_IDENTIFIER>

        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
        at net.sf.jsqlparser.parser.CCJSqlParser.ColDataType(CCJSqlParser.java:12866)
        at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpressionColumnDataType(CCJSqlParser.java:13663)
        at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:13943)
        at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:14374)
        at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:153)
        at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
        at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:23)
**Expected behavior**

**System**
 - Database you are using：postgres
- Java Version
- JSqlParser version

**Comment by dracenliu** [comment]
`drop` is a keyword

**Comment by wumpz** [comment]
So if you want to create a column named **drop**, then you have at least in the actual version of JSqlParser to double-quote it.

**Comment by hongchq** [comment]
> `drop` is a keyword

I know,but Please look carefully.

my sql is：
ALTER TABLE "user_table_t" ALTER COLUMN name drop NOT NULL;

means： Modify column  ‘’name‘’ to be nullable ，not name ‘drop’

**Comment by hongchq** [comment]
> So if you want to create a column named **drop**, then you have at least in the actual version of JSqlParser to double-quote it.
my sql is：
ALTER TABLE "user_table_t" ALTER COLUMN name drop NOT NULL;

means： Modify column ‘’name‘’ to be nullable ，not name ‘drop’

**Comment by wumpz** [comment]
Oops. Misreading your original SQL. I will look into it.
