### ISSUE TITLE
JSqlParser v3.0 doesn't support descending indexes in MySQL 8

### ISSUE THREAD

**Issue by FoxInNorth** [JSQLParser/JSqlParser#924]
**Describe the bug**
JSqlParser v3.0 doesn't support descending indexes in MySQL 8. 
Descending indexes feature start be supported from MySQL 8.

Reference:  https://dev.mysql.com/doc/refman/8.0/en/descending-indexes.html

**To Reproduce**
When use JSqlParser parse below creation table SQL, there was exception:

CREATE TABLE test_descending_indexes (
  c1 INT, c2 INT,
  INDEX idx1 (c1 ASC, c2 ASC),
  INDEX idx2 (c1 ASC, c2 DESC),
  INDEX idx3 (c1 DESC, c2 ASC),
  INDEX idx4 (c1 DESC, c2 DESC)
);

Exceptions:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ASC" "ASC"
    at line 3, column 18.

Was expecting one of:

    "("
    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnsNamesList(CCJSqlParser.java:13098)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:11869)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 30 more

And for DESC keyword, similar error message:

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "DESC" "DESC"
    at line 5, column 25.

Was expecting one of:

    "("
    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.ColumnsNamesList(CCJSqlParser.java:13098)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:11993)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 30 more

**Expected behavior**
Need recognize ASC & DESC keywords in index creation.

**System**
 - Database you are using:   MySQL 8
- Java Version: Java 8
- JSqlParser version: 3.0

**Comment by wumpz** [comment]
Will be solved through issue #936.

**Comment by wumpz** [comment]
Ups. I think not yet.
