### ISSUE TITLE
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BETWEEN" "BETWEEN"

### ISSUE THREAD

**Issue by hiwepy** [JSQLParser/JSqlParser#925]
Describe the bug
Statement statement = CCJSqlParserUtil.parse(sql); get this bug

To Reproduce
Step 1:

```sql
select m.id as jsdmid,
                m.dmrq,
                m.dmkssj,
                m.dmjssj,
                m.dmfs,
                m.gzid,
                m.fqdmzb,
                m.fqdmdd,
                m.cjsj,
        m.gzmc as xsmc,
        n.bjid,
        TO_CHAR(ROUND(decode(p.zrs, 0, 0, p.qdrs /p.zrs*100), 2),'fm9999999990.00')||'%' as qdl
        from GXXS_KQ_DMGZJLB m
        inner join GXXS_KQ_DMGZB n on m.gzid = n.id
        inner join (
        select count(t1.id) as zrs,
        sum(case when dmzt=1 then 1 else 0 end) as qdrs,
        t1.jsdmid
        from GXXS_KQ_DMJLB t1
        group by t1.jsdmid
        )p on p.jsdmid=m.id
        where m.sfzdy = '1'
        and m.jsid = ?
         
         
            AND to_date(m.dmrq||' '||m.dmkssj||':00','yyyy-mm-dd hh24:mi:ss')
            between to_date(?||':00','yyyy-mm-dd hh24:mi:ss')
            and to_date(?||':59','yyyy-mm-dd hh24:mi:ss')
```

Step 2:

```
try {
			
            Statement statement = CCJSqlParserUtil.parse(sql);
            if (null != statement && statement instanceof Select) { 
            	Select select = (Select) statement;
            	 
            }
		} catch (JSQLParserException e) {
			throw new MybatisException(String.format("Failed to process, please exclude the tableName or statementId.\n Error SQL: %s", e, sql), e);
		}
```

Error like ：

```
Exception in thread "main" org.apache.ibatis.exception.MybatisException: Failed to process, please exclude the tableName or statementId.
 Error SQL: net.sf.jsqlparser.JSQLParserException
	at org.apache.mybatis.dbperms.Test2.main(Test2.java:67)
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at org.apache.mybatis.dbperms.Test2.main(Test2.java:61)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BETWEEN" "BETWEEN"
    at line 1, column 810.

Was expecting one of:

    "&"
    "&&"
    ")"
    "."
    "::"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:7600)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:7475)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:7446)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:6425)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3794)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 2 more

```

**Comment by wumpz** [comment]
This is a hard one to solve. The problem here is this: **?||**. If you are writing this with a space after the question mark, all works fine. But without it it collides with some PostgreSQL json operator **?|**. 

You now a parsers tokenizer will always try to find the largest token.

**Comment by wumpz** [comment]
So can we close this one as I don't see any solution at the moment. Do you? PRs are wellcome.
