### ISSUE TITLE
Jsqlparser cannot parse 'show tables from database' statement 

### ISSUE THREAD

**Issue by pravari1** [JSQLParser/JSqlParser#937]
**Describe the bug**
`Statement stmt = CCJSqlParserUtil.parse("SHOW TABLES FROM db");`

`Gives below error:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"
    at line 1, column 13.

Was expecting one of:

    ";"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:23448)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:23294)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:88)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)`

**To Reproduce**
1. show tables from db
2. as mentioned above

**Expected behavior**
Should be able to parse 'show tables from database' statement

**System**
 - Mysql
- Java 8
- JSqlParser 2.1

**Comment by wumpz** [comment]
PRs are wellcome.

**Comment by wumpz** [comment]
At least since version 3.0 there some work was already done for show statements, but exactly yours it not yet supported.

**Comment by wumpz** [comment]
So any progress here or do you want to somehow in a not PR-ish way support this feature?
