### ISSUE TITLE
oracle 11g - select ... pivot clause

### ISSUE THREAD

**Issue by iszilagyigit** [JSQLParser/JSqlParser#98]
It looks like the oracle 11g select ... pivot is not supported.
See: http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10002.htm#CHDCEJJE

example sql:

select * from (
   select times_purchased, state_code
   from customers t
)
pivot 
(
   count(state_code)
   for state_code in ('NY','CT','NJ','FL','MO')
)
see also: http://www.oracle.com/technetwork/articles/sql/11g-pivot-097235.html

Maybe this could be added for example as table references where inner join, 
outer join etc is handled.

Some extract from oracle 11 sql language reference (maybe it helps to add
the pivot support at the right place):

table_reference :=  query_table_expression [ pivot_clause | unpivot_clause ]
} [ flashback_query_clause ]
  [ t_alias ]

query_table_expression::=
{ query_name
| [ schema. ]
  { table [ partition_extension_clause
          | @ dblink
          ]
  | { view | materialized view } [ @ dblink ]
  } ["sample_clause"]
| (subquery [ subquery_restriction_clause ])
| table_collection_expression
}

pivot_clause::=
table_reference PIVOT
  ( aggregate_function ( expr ) [[AS] alias ]
      [, aggregate_function ( expr ) [[AS] alias ] ]...
    pivot_for_clause
    pivot_in_clause
  )

pivot_for_clause ::= 
FOR { column
    | ( column [, column]... )
    } 

pivot_in_clause ::=
IN ( { { { expr
         | ( expr [, expr]... )
         } [ [ AS] alias]
       }...
     | subquery
     | ANY [, ANY]...
     }
   )

**Comment by wumpz** [comment]
I close this issue, till you provide additional informations.

**Comment by iszilagyigit** [comment]
Sorry for the late answer:

Most of the cases is working but not when the whole pivot query is a 
parameter for a function (in example bellow is a parameter to to_char).
I admit it's unusual.

SELECT to_char( 
SELECT col1 FROM (SELECT COL1 FROM customers t) PIVOT (count(state_code) FOR state_code IN ('NY', 'CT', 'NJ', 'FL', 'MO')) ORDER BY times_purchased 
) FROM DUAL

however the query inside the TO_CHAR can be parsed. 

Trace:
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:42)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:51)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:39)
	at net.sf.jsqlparser.test.select.SelectTest.testPivotSubquery2(SelectTest.java:1489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 15.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "||" ...
    "^" ...
    "::" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "::" ...
    "^" ...
    "||" ...
    "::" ...
    "^" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:10143)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:10013)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	... 22 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 15.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "||" ...
    "^" ...
    "::" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "ANY" ...
    "::" ...
    "^" ...
    "||" ...
    "::" ...
    "^" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:10143)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:10013)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:51)
	at net.sf.jsqlparser.test.TestUtils.assertSqlCanBeParsedAndDeparsed(TestUtils.java:39)
	at net.sf.jsqlparser.test.select.SelectTest.testPivotSubquery2(SelectTest.java:1489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

testPivotXmlSubquery1 -- pass
testPivotSubquery2 -- fails

    public void testPivotXmlSubquery1() throws JSQLParserException {
        assertSqlCanBeParsedAndDeparsed("SELECT * FROM (SELECT times_purchased, state_code FROM customers t) PIVOT (count(state_code) FOR state_code IN ('NY', 'CT', 'NJ', 'FL', 'MO')) ORDER BY times_purchased");
        
    }

    public void testPivotSubquery2() throws JSQLParserException {
        assertSqlCanBeParsedAndDeparsed("SELECT to_char( SELECT col1 FROM (SELECT times_purchased, state_code FROM customers t) PIVOT (count(state_code) FOR state_code IN ('NY', 'CT', 'NJ', 'FL', 'MO')) ORDER BY times_purchased ) FROM DUAL");
    }

**Comment by wumpz** [comment]
OK. I will reopen this issue and look into it.

**Comment by wumpz** [comment]
Does your SQL realy work in Oracle. I used SQL Fiddle and this one did not work:
SELECT to_char( select 1 from dual ) FROM DUAL
but this one works
SELECT to_char( (select 1 from dual) ) FROM DUAL

http://sqlfiddle.com/#!4/d41d8/39832

Adding this additional parenthesis in your pivot function sql does help as well in using JSqlParser.

**Comment by iszilagyigit** [comment]
You're right, sorry for the missleading bug report. 
In fact some complex view definition parse failed and  it looked like is because of the 
pivot but at the end it's a keyword issue. 

Parsing error is caused because of the "open" column name.
```java
    public void testSelectPivot1fails() throws JSQLParserException { //fails because of open column name
        String testSql = "select trunc(nvl(finished,0)/(nvl(inprogress,0)+nvl(open,0)+nvl(finished,0)) * 100,1) from self_status"
        		+ "		       pivot (sum(counter) for eval_status in ('finished' finished,'open' open,'inprogress' inprogress)) where team = t.team and periodid = t.periodid";
    	Statement parsed = CCJSqlParserUtil.parse(new StringReader(testSql));
    	System.out.println(parsed);
    }

    public void testSelectPivot1ok() throws JSQLParserException { //ok because open column name changed to opencol
        String testSql = "select trunc(nvl(finished,0)/(nvl(inprogress,0)+nvl(opencol,0)+nvl(finished,0)) * 100,1) from self_status"
        		+ "		       pivot (sum(counter) for eval_status in ('finished' finished,'open' opencol,'inprogress' inprogress)) where team = t.team and periodid = t.periodid";
    	Statement parsed = CCJSqlParserUtil.parse(new StringReader(testSql));
    	System.out.println(parsed);
    }
