### ISSUE TITLE
Parsing the `CAST` function will give an error

### ISSUE THREAD

**Issue by qq592304796** [JSQLParser/JSqlParser#987]
**Exception SQL**

`SELECT     
CAST(REPLACE(wrdi.deliver_no, '#', '') AS UNSIGNED) AS deliver_no_num,
wrdi.*
FROM wms_receipt_detail_item wrdi
WHERE wrdi.detail_id = 170005
AND wrdi.`status` IN
(  
        1
,
        2
,
        3
)
ORDER BY deliver_no_num, wrdi.pre_ssu_qty, wrdi.c_t DESC`

**Exception information**

`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 4, column 59.

Was expecting:

    <S_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.ColDataType(CCJSqlParser.java:12854) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.CastExpression(CCJSqlParser.java:10499) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:9567) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:9400) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:9353) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:9316) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:9262) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:9238) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:9231) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:4268) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:4465) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:4259) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3760) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:479) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:135) ~[jsqlparser-3.1.jar:na]
	... 147 common frames omitted`

**System**
 - mysql 8.0
- Java 11.0.7
- JSqlParser 3.1

**Comment by wumpz** [comment]
JSqlParser 4 parses this.

**Comment by bala28** [comment]
**System:**
Java 11
Oracle 12C
JSqlParser 4.3

**Query:**
SELECT TO_CHAR(CAST(SYSDATE AS TIMESTAMP WITH LOCAL TIME ZONE),'HH:MI:SS AM TZD') FROM DUAL;

**Exception:** 
Encountered unexpected token: "(" "("
    at line 1, column 15.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ACTIVE"
    "ALGORITHM"
    "ARCHIVE"
    "ARRAY"
    "AS"
    "AT"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "CHECKPOINT"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "COSTS"
    "CYCLE"
    "DBA_RECYCLEBIN"
    "DESC"
    "DESCRIBE"
    "DISABLE"
    "DISCONNECT"
    "DIV"
    "DO"
    "DUMP"
    "DUPLICATE"
    "EMIT"
    "ENABLE"
    "END"
    "EXCLUDE"
    "EXTRACT"
    "FALSE"
    "FILTER"
    "FIRST"
    "FLUSH"
    "FN"
    "FOLLOWING"
    "FORMAT"
    "FULLTEXT"
    "GROUP"
    "HAVING"
    "HISTORY"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "JSON"
    "KEY"
    "LAST"
    "LEADING"
    "LINK"
    "LOCAL"
    "LOG"
    "MATERIALIZED"
    "NO"
    "NOLOCK"
    "NULLS"
    "OF"
    "OPEN"
    "OVER"
    "PARALLEL"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "QUERY"
    "QUIESCE"
    "RANGE"
    "READ"
    "RECYCLEBIN"
    "REGISTER"
    "REPLACE"
    "RESTRICTED"
    "RESUME"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SEQUENCE"
    "SESSION"
    "SHUTDOWN"
    "SIBLINGS"
    "SIGNED"
    "SIZE"
    "SKIP"
    "START"
    "SUSPEND"
    "SWITCH"
    "SYNONYM"
    "SYSTEM"
    "TABLE"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TIMEOUT"
    "TO"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TRY_CAST"
    "TYPE"
    "UNQIESCE"
    "UNSIGNED"
    "USER"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_NEXTVAL>
    <K_STRING_FUNCTION_NAME>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>
