### ISSUE TITLE
can not parse case in where when using multi condition.

### ISSUE THREAD

**Issue by zhou-hao** [JSQLParser/JSqlParser#989]
**Describe the bug**

**To Reproduce**
```sql
select t.key from t
           where (
              case
                when (t.key = '1' or t.key = '3') then t.value = '2' or t.value = '3'
                when t.key = '2' then t.value = '3'
              end
         )
```

```text
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "case" "CASE"
    at line 1, column 32.

Was expecting one of:

    "!"
    "("
    "NOT"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:7535)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:7475)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:7528)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:7475)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:7446)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:6425)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3794)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3973)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3649)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3642)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)

```
**Expected behavior**

**System**
 - postgresql 11
- java8
- JSqlParser 3.1

**Comment by manticore-projects** [comment]
Works with 4.1 ad later.
You can [test it online here and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuA6A1gUwJ4CgBiAlA8gLIKYDqAEiLiLABSyQCComsb7HbFIAcnQigywAvLADkARjGtOsuZ3y4BadCPEBmMbACUM+bOiU+SAG4BDADYBXVGrEAmafvaKB567dFjNe-d2OCql6Ovs5shrxuljZ2PvK8ACI6mADcQA+)
