### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>

### ISSUE THREAD

**Issue by torobcheh** [JSQLParser/JSqlParser#995]
We have a table in the database, which have a column named **leading**
We cannot parse a sql, which references this column. Seems that the parser could not parse it, cause of the keyword LEADING

Example 
String sql = "SELECT leading  from prd_reprint";
Select select = (Select)CCJSqlParserUtil.parse(sql);

throws

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:229)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)

tried also variants with table alias, or using functions around the columns does not work

same exception with
placing, both and trailing

/* | tk=<K_PLACING> | tk=<K_BOTH> | tk=<K_LEADING> | tk=<K_TRAILING> */

**System**
 - Oracle
- 1.8
- 3.1

**Comment by torobcheh** [comment]
same exception with
placing, both and trailing

/*      | tk=<K_PLACING> | tk=<K_BOTH> | tk=<K_LEADING> | tk=<K_TRAILING> */

**Comment by AnEmortalKid** [comment]
Seems that those are commented out: https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L1178

Didn't see a comment above them but they were introduced around here: https://github.com/JSQLParser/JSqlParser/pull/702/files

**Comment by AnEmortalKid** [comment]
```
File "Node.java" does not exist.  Will create one.
File "SimpleNode.java" does not exist.  Will create one.
File "CCJSqlParserTreeConstants.java" does not exist.  Will create one.
File "CCJSqlParserVisitor.java" does not exist.  Will create one.
File "CCJSqlParserDefaultVisitor.java" does not exist.  Will create one.
File "JJTCCJSqlParserState.java" does not exist.  Will create one.
Annotated grammar generated successfully in J:\Workspaces\JSqlParser\target\javacc-1592524933941\node\JSqlParserCC.jj
Java Compiler Compiler Version 7.0.4 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file J:\Workspaces\JSqlParser\target\javacc-1592524933941\node\JSqlParserCC.jj . . .
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.
Warning: Choice conflict involving two expansions at
         line 3545, column 25 and line 3547, column 25 respectively.
         A common prefix is: "BOTH" "+"
         Consider using a lookahead of 3 or more for earlier expansion.
File "Provider.java" does not exist.  Will create one.
File "StringProvider.java" does not exist.  Will create one.
File "StreamProvider.java" does not exist.  Will create one.
File "TokenMgrException.java" does not exist.  Will create one.
File "ParseException.java" does not exist.  Will create one.
File "Token.java" does not exist.  Will create one.
File "SimpleCharStream.java" does not exist.  Will create one.
```

Looks like uncommenting causes choice conflicts.
